### ISSUE TITLE
Some tweets show an error.

### ISSUE THREAD

**Issue by MarisaKirisame-ze** [dimdenGD/OldTwitter#100]
**Describe the bug**
Certain Tweets won't load, and instead, show an error.

**To Reproduce**
Go to a tweet's page. In particular, this one: https://twitter.com/_EuClaire/status/1672992231622602752

**Expected behavior**
It should load normally.

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/86389939/8dcefedd-50eb-43eb-b9dd-8eca94ab91b0)

**Browser**
Google Chrome Version 114.0.5735.199 (Official Build) (64-bit)

**Comment by dimdenGD** [comment]
Fixed in https://github.com/dimdenGD/OldTwitter/commit/2d6cf42e1a02bdd51c70a1d54ece5fd5f47bf6f7

**Comment by thepwrtank18** [comment]
![image](https://github.com/dimdenGD/OldTwitter/assets/57580668/b3a6d46d-8014-4873-8ddd-22b0723ad233)

**Comment by thepwrtank18** [comment]
you're in for a really bad game of whack a mole

**Comment by dimdenGD** [comment]
when u post these u should always include tweet link

**Comment by thepwrtank18** [comment]
https://twitter.com/MrUncannyGame/status/1675635182269874179

**Comment by dimdenGD** [comment]
it works fine for me

**Comment by dimdenGD** [comment]
Pushed possible fix: https://github.com/dimdenGD/OldTwitter/commit/e24558b70900a39a8165f0b74b01bd28cd8a46e5, try with it

**Comment by thepwrtank18** [comment]
It looks like directly opening the Tweet works, but opening it on your timeline gives the same error.
![image](https://github.com/dimdenGD/OldTwitter/assets/57580668/4c1454cb-4237-4fe3-bbd8-233dce20989f)

**Comment by dimdenGD** [comment]
Just pushed another fix

**Comment by thepwrtank18** [comment]
![image](https://github.com/dimdenGD/OldTwitter/assets/57580668/db126069-d5cd-461b-93a9-f77257210b08)
Looks like it's showing the actual error now, Elon's stupid rate limits.
