### ISSUE TITLE
Soft/smooth navigation

### ISSUE THREAD

**Issue by aubymori** [dimdenGD/OldTwitter#102]
I really like this extension, but I wish I could check my notifications or go to someone's profile without losing my place in my timeline. I would like the navigation to be smooth, AKA done in JS rather than having the page refresh every time you visit a new page.

**Comment by TorutheRedFox** [comment]
would probably fix the annoying white flashes too

**Comment by dimdenGD** [comment]
Due to how extension is made this is simply impossible without basically a complete rewrite. Use middle mouse button to open tab when you want to check notifications or see profile
