### ISSUE TITLE
Profile and Tweet issues

### ISSUE THREAD

**Issue by emeraldongithub** [dimdenGD/OldTwitter#103]
**Describe the bug**
When i go to see a thread, it says "Sorry, this page does not exist". I go to my profile, it works, but the tweets don't show and instead say "Sorry this page doesn't exist"

**To Reproduce**
Go to any thread, or any Twitter profile.

**Expected behavior**
It's supposed to load the actual tweets and threads.

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/99167692/ed5e4d7a-2867-4d44-b25f-7f9f47fa819b) 
![image](https://github.com/dimdenGD/OldTwitter/assets/99167692/100f5ab8-5f56-4eae-8d89-2b7b19d644ef)

**Browser**
Google Chrome version 114.0.5735.199 (64-bit)

**Comment by emeraldongithub** [comment]
![image](https://github.com/dimdenGD/OldTwitter/assets/99167692/8f70d83e-5f92-421b-987b-25e3ed07de7a)
another error, viewing an tweet from the timeline will not load the tweet

**Comment by LPFan12** [comment]
Are you running 1.7.1? It got fixed in 1.7.2(Or should be at least, it works for me) which officially released before you opened the issue, so most likely an invalid report.
