### ISSUE TITLE
Old Twitter seems to allow ads to go through on replies, even with an ad blocker

### ISSUE THREAD

**Issue by SupDos** [dimdenGD/OldTwitter#104]
This isn't 100% reproducible, on 2 different browsers with 2 different Twitter accounts checking the exact same tweet replies, there might be one account where I get the ad, but not on the other one

[image1](https://github.com/dimdenGD/OldTwitter/assets/6813986/dc2d5047-ec64-44a9-826e-88f44a189cd9) and [image2](https://github.com/dimdenGD/OldTwitter/assets/6813986/ec80861f-cbe3-4b8f-bc28-a7ad5600b35f), showing the ad changing - it's not a reply to the tweet, switching to new Twitter doesn't show it and viewcounts are obviously an indicator it's an ad

[Ad disappears](https://github.com/dimdenGD/OldTwitter/assets/6813986/c2345cdf-24bc-4b1a-a76b-2eb66dddb0e3) in new Twitter

[Same tweet as above](https://github.com/dimdenGD/OldTwitter/assets/6813986/50b5a060-ed27-42c5-9222-da7c6fe573cb) but on a different account, doesn't have the ad

[Another tweet screenshot](https://github.com/dimdenGD/OldTwitter/assets/6813986/3f729939-b8ba-4746-9c32-f1947dbc48f3)

Tested on Firefox only, can't test Chrome atm since it's still not updated

**Comment by squabbled** [comment]
I'm getting the same issue on Firefox 114.0.2 (Windows 10) with uBlock Origin and Pi-Hole. My theory is the promoted label is missing from the post so uBO doesn't pick up on it. Just a guess.
![image](https://github.com/dimdenGD/OldTwitter/assets/40838711/cb61981b-2828-4301-8479-9f2ac9148551)
![image](https://github.com/dimdenGD/OldTwitter/assets/40838711/31e5b5a6-6b49-4eff-9645-51f4ee15b35e)
![image](https://github.com/dimdenGD/OldTwitter/assets/40838711/713a5f91-d8dc-42de-a694-8e36987c72f8)

**Comment by the-j-master** [comment]
Seen this, too, on LibreWolf 107.0-1 (Windows 10 22H2). A few refreshes seem to stop the ads for one or two tweets, but they come back with time.
![image](https://github.com/dimdenGD/OldTwitter/assets/98195560/85592cfa-2623-4253-a9b6-89fcd0d1e39c)
Can also confirm it occurring on Chromium-based browsers, with ungoogled-chromium 114.0.5735.199:
![image](https://github.com/dimdenGD/OldTwitter/assets/98195560/8399c35c-dfee-4a6d-b86b-9c194f45b7eb)
Mostly leaving this for posterity at this point, as I did notice that dimden has been made aware of the issue already.

**Comment by dimdenGD** [comment]
Fixed
