### ISSUE TITLE
Display original source of retweets instead of old style RT

### ISSUE THREAD

**Issue by codemasher** [dimdenGD/OldTwitter#106]
Hey, could you please add an option to show the original retweeted tweets instead of the old style `RT @author`?

Edit 1: Wait, I just noticed that it sometimes properly shows retweets and then other times it shows old style RT??? A bug perhaps?
Edit 2: So in the home timeline retweets are displayed properly, when reading lists, it shows old style RTs.

**Comment by dimdenGD** [comment]
Fixed

**Comment by codemasher** [comment]
Thank you!
