### ISSUE TITLE
Optional icons for blue checks

### ISSUE THREAD

**Issue by codemasher** [dimdenGD/OldTwitter#108]
Similar to https://github.com/eramdam/BetterTweetDeck/commit/27bf2e6d26632c1b8cb96a281892e25da6087872 and https://github.com/eramdam/BetterTweetDeck/commit/430856efde3362631cd2587c603f9fc7dbaeff3a

**Comment by dimdenGD** [comment]
What do you mean by this? You already can enable/disable blue checkmark in settings

**Comment by codemasher** [comment]
BetterTweetdeck had an option to replace the paid blue checks with a different icon, e.g. 🤡 (see the first linked commit in the OP). Granted, now that most blue checkmarks are paid for and there's no way to tell apart which ones were restored "for free" after the removal desaster, it makes less sense now. It would be a fun addition nevertheless though.

**Comment by dimdenGD** [comment]
Oh, I don't think this will be added
