### ISSUE TITLE
Profile information is wrong on Home timeline when having more than one account

### ISSUE THREAD

**Issue by ladymihonya** [dimdenGD/OldTwitter#109]
**Describe the bug**
When having multiple accounts on multiple containers and/or private tabs, the home timeline will keep profile information for one account and show it for all others, even if you're logged on another account on another container/private tab.

**To Reproduce**
Install extension.
Go to your home timeline with account 1. 
Go to a private tab or container, connect to account 2.
Home timeline will show account 1's profile information on top left instead of account 2's.

**Expected behavior**
Home timeline should be correctly displaying profile information for all accounts, even within a single instance with containers and private tabs.

**Screenshots**
![firefox_Tbjk0zdBwT](https://github.com/dimdenGD/OldTwitter/assets/6630467/6622a935-4b47-4740-b9d1-ca7b75077ebd)
![firefox_jZIri0cTRy](https://github.com/dimdenGD/OldTwitter/assets/6630467/db61040f-1405-464f-b313-9451b3e144ca)

Second tab is a container, using a different account than the first tab and still displays former account's information.

**Browser**
Firefox 114.0.2

**Comment by Ashdemai** [comment]
This a problem. Don't want to confuse myself as the other account. Hopefully it's going to be addressed with the now growing popularity of the extension. Dev did a good job overall I'm impressed.

**Comment by dimdenGD** [comment]
I don't know how these private tabs/containers work but this is because of caching inside `browser.storage.local`

**Comment by BanementI** [comment]
Can confirm this happened to me as well.
> I don't know how these private tabs/containers work but this is because of caching inside `browser.storage.local`

More info about how they work can be found here https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers
For some reason, `browser.storage.local` isn't separated between containers, which seems to be a [known issue](https://github.com/mozilla/multi-account-containers/issues/44). Might need to change how you do the caching.

**Comment by dimdenGD** [comment]
Since I have no plans for switching from browser.storage.local, I don't know if this will ever be fixed

**Comment by Ashdemai** [comment]
> Since I have no plans for switching from browser.storage.local, I don't know if this will ever be fixed

That sucks, but I understand.

**Comment by ladymihonya** [comment]
> Since I have no plans for switching from browser.storage.local, I don't know if this will ever be fixed

Understandable.
