### ISSUE TITLE
Stuck in URL loop when opening Twitter after installation

### ISSUE THREAD

**Issue by danielkapica** [dimdenGD/OldTwitter#110]
**Describe the bug**
Browser continuesly tries to open https://twitter.com/i/flow/login?redirect_after_login=%2Fold%2Fsettings but fails and results in loop

**To Reproduce**
open twitter.com
or
select extension and select settings

**Expected behavior**
The login/settings should be opening

**Screenshots**
<img width="1260" alt="image" src="https://github.com/dimdenGD/OldTwitter/assets/138490791/0cc18f99-0163-49b3-ac9c-420a832aee40">

<img width="1260" alt="image" src="https://github.com/dimdenGD/OldTwitter/assets/138490791/8c5655d7-73f8-4911-bbb7-e33b7e565b50">

**Browser**
Tried 2 browsers:
Google Chrome 114.0.5735.198 on MacOS Ventura 13.5 Beta
Firefox 114.0.2 (64-bit) on MacOS Ventura 13.5 Beta

**Comment by andrigamerita** [comment]
@danielkapica This bug happened to me too but only if the extension was active before having an active session on twitter.com. I disabled the extension, opened twitter.com, logged in, and only then re-enabled the extension. At that point, a new tab opened in the browser that redirected me to twitter settings and the old layout was applied, no more redirect loops.

**Comment by Konahrik13** [comment]
Also having this issue, Twitter cannot load at all for me. It just endlessly refreshes itself so quickly that nothing loads on the page.

**Comment by dimdenGD** [comment]
Uninstall, login, install again

**Comment by Konahrik13** [comment]
Are you saying login to Twitter? I can't because I don't have an account.

**Comment by Konahrik13** [comment]
Well that sucks, was hoping I could access Twitter with it and get by without an account.
