### ISSUE TITLE
'TypeError: o is undefined' when visiting media tab of particular users

### ISSUE THREAD

**Issue by bbogdn2** [dimdenGD/OldTwitter#111]
**Describe the bug**
When viewing the photos & videos tab of this particular user, it shows `TypeError: o is undefined`.

**To Reproduce**
Visit this [twitter user's page](https://twitter.com/gogo_zubu/media) and go to the photos & videos tab.

**Expected behavior**
A feed containing their media should appear.

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/133264129/9172c6b5-b8e4-4946-8693-c10bb6ce99c1)

**Browser**
Firefox 114.0.2 (64-bit)

**Comment by SuruIde** [comment]
Showing error `TypeError: Cannot read properties of undefined (reading ’legacy’)` for me. It's also happening on [this other user's media tab](https://twitter.com/karystmania/media).

![Screenshot_2841](https://github.com/dimdenGD/OldTwitter/assets/75902790/fc41d4a8-5725-42c7-8057-b0336cb54d6d)
