### ISSUE TITLE
Change text and icon color to white based on color

### ISSUE THREAD

**Issue by Arcadius2006** [dimdenGD/OldTwitter#112]
some colors dont mesh well with dark text, maybe implement a system that detects if a color is too dark for the text to be made white and readable
![image](https://github.com/dimdenGD/OldTwitter/assets/93880348/c5bea338-5cdc-43a7-ac7b-d373db2dbe31)

**Comment by codenoid** [comment]
holy f dude, this is fire @dimdenGD

**Comment by dimdenGD** [comment]
Looks pretty readable to me, there's already such system in place
