### ISSUE TITLE
The share tweet button does not work.

### ISSUE THREAD

**Issue by BCSmiles** [dimdenGD/OldTwitter#113]
**Describe the bug**
When attempting to share a tweet there is no prompt to send the tweet to other users or to other social media platforms.

**To Reproduce**
Click the three dots at the bottom of any tweet then click 'Share tweet'.

**Expected behavior**
A list of users and other social media platforms should appear.

**Browser**
Firefox 110.0 (64-bit).

**Comment by dimdenGD** [comment]
This feature doesn't work in Firefox but works on Chromium and Webkit browsers. I've made it to not display this button if it's not supported, it seems that Firefox might be adding it soon
