### ISSUE TITLE
Add toggle for switching between old/new UI

### ISSUE THREAD

**Issue by ksbrar** [dimdenGD/OldTwitter#12]
Spawned by my other question about lists, it would be nice to have a toggle for switching back and forth between the new UI and old UI for e.g. when Twitter adds some new feature that isn't supported yet - saves the user a trip to their extensions settings.

**Comment by dimdenGD** [comment]
There's  
![old](https://lune.dimden.dev/29a6f8523e.png)  
this button in old twitter  
  
and  
![new](https://lune.dimden.dev/5f8b26f7e7.png)
in new

**Comment by ksbrar** [comment]
Ah, totally missed that. Thanks!
