### ISSUE TITLE
Option to separate normal tweets and retweets into different timelines

### ISSUE THREAD

**Issue by KevlarCaviar** [dimdenGD/OldTwitter#120]
<img width="671" alt="newtwitter tabs" src="https://github.com/dimdenGD/OldTwitter/assets/106205344/d8ccc237-0adf-4263-9194-c837bd2a3f05">

This is probably easier said than done, but it's the one feature that regular Twitter (with the Control Panel extension) has that I always find myself missing whenever I try out alternative layouts. OldTwitter is far from unusable without it, obviously, but with this it'd go from "great" to "superior to new Twitter in every way" in my book.

**Comment by SabreRunner** [comment]
Second. I would like the option of "Without RTs but with QTs" and any combination of that and likes.
If possible, I would also love a "Chronological order but from the last tweet I read last time" though I admit that might be a tall order.

**Comment by dimdenGD** [comment]
Added!
![image](https://github.com/dimdenGD/OldTwitter/assets/26517362/85e42720-163a-4e40-badf-b4268954b7e4)
There's also gonna be a quick-switch too

**Comment by SabreRunner** [comment]
Thank you, you gorgeous legendary individual!
