### ISSUE TITLE
Add current Twitter "Go to" keyboard shortcuts

### ISSUE THREAD

**Issue by Tina-otoge** [dimdenGD/OldTwitter#125]
Current Twitter shortcuts are very usable, they take a lot of inspiration for Vim and make a lot of sense for a power-user
![image](https://github.com/dimdenGD/OldTwitter/assets/9400466/10e5373d-6173-4bf0-892d-e146e29f91a3)

I especially grew accustomed to the "g+<letter>" shortcuts, for "go-to <something>", I use those 3 daily:
- g+h -> Go to Home
- g+n -> Go to Notifications
- g+m -> Go to Messages

I would love to see an option to enable the current Twitter shortcuts, or at least the "g+<letter>" subset, thankfully you do not seem to use the G letter for any shortcut right now so it could even be added to the current set of shortcuts.

**Comment by dimdenGD** [comment]
Added! New hotkeys:
`G+H` - Home  
`G+N` - Notifications  
`G+M` - Mentions  
`G+P` - Profile  
`G+L` - Likes  
`G+I` - Lists  
`G+M` - Messages  
`G+S` - Settings  
`G+B` - Bookmarks
