### ISSUE TITLE
Twitter website flashes black and white with extension if you're signed out of Twitter for your browser (SEIZURE WARNING IF YOU'RE GOING TO REPRODUCE THE BUG)

### ISSUE THREAD

**Issue by mmkthecoolest** [dimdenGD/OldTwitter#127]
**_DISCLAIMER: I don't use Twitter often nor do I have an account. I just wanted to see if viewing tweets without logging in worked_**

**Describe the bug**
The web browser content flashes black and white with the extension enabled when you're signed out of Twitter.

**To Reproduce**
1. Sign out of your Twitter account
2. Try to load up a Twitter profile without a Twitter account signed in like [this one](https://twitter.com/vinnyvinesauce)

**Expected behavior**
Either it shows the login screen or it shows the twitter profile.

**Browser**
Firefox 114.0.2

**Comment by leiste375** [comment]
Same bug. However, it's the browser reloading the page in rapid succession, producing a flashing effect.

**Comment by Omoeba** [comment]
I can reproduce this issue with Firefox 115.0

**Comment by dimdenGD** [comment]
Fixed
