### ISSUE TITLE
Group messages will not load 

### ISSUE THREAD

**Issue by Aronjlove** [dimdenGD/OldTwitter#129]
**Describe the bug**
Group messages will not load.

**To Reproduce**
Click the Messages button, click a group message in the list, click load more, and watch as nothing happens.

**Expected behavior**
When clicking load more, the group message should load just like a direct message

**Browser**
Windows 11 running Microsoft Edge Version 114.0.1823.67 (Official build) (64-bit)

**Comment by dimdenGD** [comment]
Should be fixed now
