### ISSUE TITLE
Frequently need to refresh the page

### ISSUE THREAD

**Issue by ksbrar** [dimdenGD/OldTwitter#13]
This happens inconsistently but enough to be annoying. I e.g. click on a link to another tweet and the page hangs on the Twitter logo until I manually refresh.

**Comment by dimdenGD** [comment]
never happened to me, can you record this happening and also show errors in console

**Comment by ksbrar** [comment]
![msedge_gjrSgtax4P](https://user-images.githubusercontent.com/4261338/187803252-09916fa0-5b1e-4833-bcb5-65fa0ca6a741.gif)

**Comment by dimdenGD** [comment]
I've noticed that you don't have "Who to follow" window, did you modify extension anyhow? Error on that code line is related to that window

**Comment by dimdenGD** [comment]
Alright, I don't know why it happens but I tried to fix it by making it reload page on error like this.  
  
You can try new version by removing extension installed from chrome web store and [installing last version manually](https://github.com/dimdenGD/OldTwitter#manual-installation), because it takes like 3-5 days to get new version up in store
  
Tell me if it fixed it

**Comment by dimdenGD** [comment]
Applied fix to all pages, check again

**Comment by ksbrar** [comment]
Nah unfortunately still happens on that first load

**Comment by dimdenGD** [comment]
Yeah idk then

**Comment by dimdenGD** [comment]
I have started getting this bug and could finally fix it!

**Comment by ksbrar** [comment]
Better than before but still happens for me :P

**Comment by dimdenGD** [comment]
Are you sure you tried this with latest version? It's not released on chrome web store yet

**Comment by ksbrar** [comment]
Downloaded latest from GH and so far it works perfectly. Thanks!

**Comment by dimdenGD** [comment]
Update released on Chrome Web Store

**Comment by ksbrar** [comment]
FYI I still do occasionally encounter this issue if I'm aggressively clicking through threads and what not. But it is rare.
