### ISSUE TITLE
Expanded Tweets Link Leads to "New Twitter" Layout for Tweet Detail View

### ISSUE THREAD

**Issue by nilsgarland** [dimdenGD/OldTwitter#130]
**Describe the bug**
Within the Twitter feed there is a restriction on the amount of characters displayed in a Tweet. The Tweet includes a link to a detail view of the Tweet. The bug arises when clicking the link, and the layout then reverts back to the new layout. 

**To Reproduce**

1. Go to Twitter feed in old layout, find tweet with too many characters. The tweet will include a link to the detail view at the end of the text. Click the link.

![](https://ajeuwbhvhr.cloudimg.io/colony-recorder.s3.amazonaws.com/files/2023-07-03/be8d2e8a-892a-4f2f-bd83-861121948aec/ascreenshot.jpeg?tl_px=1405,222&br_px=2898,1062&force_format=png&width=560&wat_scale=50&wat=1&wat_opacity=0.7&wat_gravity=northwest&wat_url=https://colony-recorder.s3.us-west-1.amazonaws.com/images/watermarks/FB923C_standard.png&wat_pad=262,139)

2. Opened link should now have new layout

![](https://ajeuwbhvhr.cloudimg.io/colony-recorder.s3.amazonaws.com/files/2023-07-03/75fa7780-b966-4deb-a210-4b74001ab4c6/ascreenshot.jpeg?tl_px=581,132&br_px=2074,972&force_format=png&width=560&wat_scale=50&wat=1&wat_opacity=0.7&wat_gravity=northwest&wat_url=https://colony-recorder.s3.us-west-1.amazonaws.com/images/watermarks/FB923C_standard.png&wat_pad=262,139)

Tweet in example: https://twitter.com/i/web/status/1675950486548099073 (Just opening a detailed view seems to replicate the issue as well)

**Expected behavior**
The tweet detail view should still use the old layout.

**Browser**
Brave v1.52

**Comment by dimdenGD** [comment]
Now long tweets should show up fully
