### ISSUE TITLE
Unable to  See All of Other User's Following Tab

### ISSUE THREAD

**Issue by MookseZero** [dimdenGD/OldTwitter#131]
**Describe the bug**
Unable to see all of a user's following tab with only a hundred to several hundred available to view instead of over a thousand.

**To Reproduce**
After reaching a limit, I reach the 'Load More' button. And whenever I click, it won't load more users to view.

**Expected behavior**
Whenever scrolling through a user's following tab, I expect to see all of who they're following.

**Browser**
Version 114.0.5735.143 (Official Build) (64-bit) / ChromeOS

**Comment by dimdenGD** [comment]
Works fine for me, on which user this happened to you?

**Comment by MookseZero** [comment]
Sorry for not responding sooner. This development has been happening on both my personal phone and laptop. That's why I switched to the Old Twitter Layout extension to see more followers. Anything I should know or that you want to ask of me?
