### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'legacy')

### ISSUE THREAD

**Issue by KingGamingYT** [dimdenGD/OldTwitter#134]
I encountered this bug upon going back in my browser from my notifications to a tweet.
I'm using chrome 114.0.5735.199
![image](https://github.com/dimdenGD/OldTwitter/assets/45918062/64541f73-0717-4485-b9b7-12c674af8303)

**Comment by dimdenGD** [comment]
link to tweet

**Comment by KingGamingYT** [comment]
> link to tweet
https://twitter.com/WorklessAlt/status/1675821687420461056

**Comment by KingGamingYT** [comment]
update: seems the user got suspended, kek.
