### ISSUE TITLE
SyntaxError When Opening Tweet in New Tab

### ISSUE THREAD

**Issue by sixdearcs** [dimdenGD/OldTwitter#137]
**Describe the bug**
I received a Syntax Error; "SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data"

**To Reproduce**
When on home page, click a tweet with middle mouse button to open it in a new tab.

**Expected behavior**
I expected to see the tweet in a new tab, I did not experience this.

**Screenshots**
(https://cdn.discordapp.com/attachments/1123345310253580500/1125597008414126110/oldtwt_error.png)

**Browser**
Firefox 114

**Comment by dimdenGD** [comment]
This was fixed
