### ISSUE TITLE
I’m having an issue where videos stay blurred when I click on them.

### ISSUE THREAD

**Issue by nickfan01** [dimdenGD/OldTwitter#138]
The video clearly plays, but it's still blurred.

**Comment by dimdenGD** [comment]
Could you give me link to any tweet with video like this? NSFW is fine

**Comment by ouwou** [comment]
ran into this too. firefox 117 and v1.7.3

https://twitter.com/MihajlovicMike/status/1675989567650910208
![firefox_dAEXxOzzeh](https://github.com/dimdenGD/OldTwitter/assets/26526779/90769f82-453c-4d36-8cd6-ae01fe7b7287)

**Comment by dimdenGD** [comment]
Thanks, fixed
