### ISSUE TITLE
Can't view a tweet when the first tweet of the thread was deleted.

### ISSUE THREAD

**Issue by Kleadron** [dimdenGD/OldTwitter#139]
If you create a thread or reply to a tweet and the first tweet or the tweet you replied to was deleted, it results in a "TypeError: tweetData is undefined" error when you try to view the reply.

I'm using firefox 114.0.2.

**Comment by dimdenGD** [comment]
Can you give me link to any tweet like this?

**Comment by Kleadron** [comment]
Sorry for responding late, I didn't get any notifications for this issue. 

Here's an example I made that reproduces the issue: https://twitter.com/kleadron/status/1677797246837071872

**Comment by dimdenGD** [comment]
Seems that I already fixed this somehow in beta
