### ISSUE TITLE
Support for twitter circles?

### ISSUE THREAD

**Issue by lambda-makes-things** [dimdenGD/OldTwitter#14]
Idk if this can be done but if it can that would be neat

**Comment by dimdenGD** [comment]
[Added](https://github.com/dimdenGD/OldTwitter/commit/7e359bb2e5195b7d28fbdbdd6c6e3c6ddddeb5d5).  
Since I'm working on different languages support, release to browser extension sites will be delayed, expect to see this feature in around a week

**Comment by dimdenGD** [comment]
Update finally released on Chrome Web Store
