### ISSUE TITLE
Quick switching between algo and chrono tabs

### ISSUE THREAD

**Issue by Arcadius2006** [dimdenGD/OldTwitter#142]
add a button (or two buttons) in the main menu that lets you switch between the Algorythmic and Chronological timelines

**Comment by DavidSM64** [comment]
Would love this as a feature. Twitter does do some weird stuff, but I'm actually a fan of having the "For you" along with the regular chronological timeline.

**Comment by dimdenGD** [comment]
Added!
![image](https://github.com/dimdenGD/OldTwitter/assets/26517362/2909e52c-bb05-49ca-9d66-5c22ea7ef852)
