### ISSUE TITLE
Zoomin and sizing issues on mobile

### ISSUE THREAD

**Issue by Ristellise** [dimdenGD/OldTwitter#144]
**Describe the bug**
If using a mobile sized form factor (such as Any phone, it refuses to resize to a smaller windows)

**To Reproduce**
Sizing can be replicated by shrinking browser size, but can be better emulated via [devtools mobile simulation](https://developer.chrome.com/docs/devtools/device-mode/)

**Expected behavior**
Old twitter should resize to mobile twitter correctly.

**Screenshots**
No Screenshots, but it looks like the extensions's old twitter but looks like it was for desktop viewing.

**Browser**
![Screenshot_20230704_172543_Kiwi Browser](https://github.com/dimdenGD/OldTwitter/assets/7894419/b5481cb8-6283-4e8f-9326-de78952d7398)

**Extra**  
I don't expect this to be fixed anytime soon since it probably is a not too high priority (and the fact that I'm using a weird version of chromium)

**Comment by TorutheRedFox** [comment]
i mean this layout never was intended for anything but desktop use

mobile had a dedicated layout of its own

**Comment by dimdenGD** [comment]
Added support for phones
