### ISSUE TITLE
GET https://twitter.com/manifest.json net::ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by UsamaEjaz0** [dimdenGD/OldTwitter#145]
![image](https://github.com/dimdenGD/OldTwitter/assets/45048065/e7bab516-a9a0-402a-b2e9-beabe049224e)

**Comment by dimdenGD** [comment]
This is not a bug and it's blocked on purpose

**Comment by dimdenGD** [comment]
If you mean Twitter not loading, it'd be separate bug, not about manifest.json
