### ISSUE TITLE
@ mentions at the beginning of a tweet don't appear

### ISSUE THREAD

**Issue by WannaBeDev64** [dimdenGD/OldTwitter#146]
OldTwitter:
![vivaldi_37hSKBBz3v](https://github.com/dimdenGD/OldTwitter/assets/62036967/ebf4e01a-adb1-4a50-987d-849d1bebf133)
Normal Twitter:
![vivaldi_4UIy5lBAqB](https://github.com/dimdenGD/OldTwitter/assets/62036967/c2f5769b-fdea-4182-9a51-212182cf697d)

Link to tweet: https://twitter.com/bedescarlet/status/1674940460685557760?s=20

**Comment by Arcadius2006** [comment]
i'd love to see this fixed, it breaks SO MANY tweets
