### ISSUE TITLE
Profile names don't wrap if they exceed the width of the profile container

### ISSUE THREAD

**Issue by NazrinUFO** [dimdenGD/OldTwitter#147]
On the left, full name is "Alfonso Fan Club President" but gets cut off at "Alfonso Fan Club".
![image](https://github.com/dimdenGD/OldTwitter/assets/1322447/0b6cfe2c-264f-4b47-a3ce-4c5ab53b59a1)

**Comment by dimdenGD** [comment]
This won't be fixed as size of that container is fixed
