### ISSUE TITLE
TypeError: can’t access property "timeline", data.data.user.result.timeline_v2 is undefined

### ISSUE THREAD

**Issue by thepwrtank18** [dimdenGD/OldTwitter#151]
**Describe the bug**
When attempting to see the tweets of a protected account you don't have access to, it says "TypeError: can’t access property "timeline", data.data.user.result.timeline_v2 is undefined".

**To Reproduce**
1. Go to a protected profile who's tweets you can't access
2. See error

**Expected behavior**
It should say something along the lines of this:
![image](https://github.com/dimdenGD/OldTwitter/assets/57580668/9397ce16-30e0-47a9-9336-3a0558d08bfa)

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/57580668/aaab0080-9c69-449d-8763-b506afbb28c6)

**Browser**
Firefox Developer Edition 115.0b9 (64-bit)

**Comment by dimdenGD** [comment]
This was fixed
