### ISSUE TITLE
Logging in to a new account doesn't show it and OldTwitter gets confused

### ISSUE THREAD

**Issue by Chew** [dimdenGD/OldTwitter#152]
**Describe the bug**
I logged in to a new account. The home feed shows tweets from this account, but "Profile" shows the old account's profile. When trying to switch to the old account, the new account doesn't show, and the old account says "You are already signed in to this account!" Switching to a secret third account and back fixes it, but the newly logged into account still isn't there (despite being there on new twitter) 

**To Reproduce**
1. Be signed in pre-Old Twitter
2. Install Old Twitter
3. Click "Manage Accounts"
4. Log in to new account
5. Be in weird limbo

**Expected behavior**
I expected me to be able to use the new account like normal.

**Screenshots**
n/a

**Browser**
Arc Version 0.110.1 (39837)
Chromium Engine Version 114.0.5735.198

**Comment by dimdenGD** [comment]
Fixed
