### ISSUE TITLE
download hotkey does nothing

### ISSUE THREAD

**Issue by fluid-decanter** [dimdenGD/OldTwitter#153]
Download hotkey seems to do nothing at all.

Some examples of tweets I have tested on include:
video https://twitter.com/clotifiles/status/1676242072939155468
single image without text https://twitter.com/NoContextBrits/status/1676131950879289347
single image with text https://twitter.com/BrianManookian/status/1562457880288038915
multiple images https://twitter.com/senatorshoshana/status/1666892555944882176

It doesn't seem to matter whether I disable adblockers or disable "Always show original quality images" extension setting.
Using Firefox 114.0.2

**Comment by dimdenGD** [comment]
Fixed
