### ISSUE TITLE
Notification Bubble won't disappear

### ISSUE THREAD

**Issue by DaniJam05** [dimdenGD/OldTwitter#16]
**Describe the bug**
Notification Bubble won't disappear after checking notifications, only disappears while on the notifications page

**Screenshots**
![image](https://user-images.githubusercontent.com/116296016/197001470-e78f417a-d357-42c7-8bb8-67153460ccd4.png)
![image](https://user-images.githubusercontent.com/116296016/197001606-2d323236-4638-4f33-bc3b-411d5ecafc87.png)
![image](https://user-images.githubusercontent.com/116296016/197001699-dd542577-2fa4-4144-83a2-4758249a9333.png)

**Browser**
Opera GX LVL4

**Comment by dimdenGD** [comment]
Do you get any errors when browser tries to request this?  
![img](https://lune.dimden.dev/96fb6b2c37.png)  
Open Devtools with F12 and go to Network devtools tab and then go to Notifications page with unread notifications
