### ISSUE TITLE
Adding a New Account breaks Interface

### ISSUE THREAD

**Issue by ApfelSkai** [dimdenGD/OldTwitter#160]
Bug Description and Reproduction:
After logging into a second account using "Manage Accounts", the dropdown will not show the additional profile until after cycling the profiles in the normal twitter interface. Swapping to the new profile will break the OldTwitter interface forcing default twitter until after >1 page refreshes.

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/77424641/8f4b21e2-cfe1-4bbd-8809-bede7e8ec291)

**Browser**
Opera Chromium version:113.0.5672.127

**Comment by dimdenGD** [comment]
I know this doesn't directly fixes it, but after adding the new account it should correctly appear on OldTwitter after 5-15 minutes. This entire issue is caused by caching

**Comment by dimdenGD** [comment]
Fixed
