### ISSUE TITLE
Option to replace the "Twitter.com" in links copied via "Copy link to tweet" with vxtwitter.com for easy embedding on other services.

### ISSUE THREAD

**Issue by GarnetSunset** [dimdenGD/OldTwitter#161]
When clicking the top button here, it would be cool if we had the option to copy the link as a vxtwitter.com link since that can embed in telegram/discord etc. Since the embed function is broken as of a couple days ago.

![image](https://github.com/dimdenGD/OldTwitter/assets/13430434/766f9b70-8025-4df3-9c2b-00d77c347f63)

**Comment by fivefivefiver** [comment]
Adding to that: it would also be cool if clicking "Copy Link" stripped away all the tracking parameters after the ? character in the URL

**Comment by dimdenGD** [comment]
Pretty sure it already does that

**Comment by fivefivefiver** [comment]
Oh! So it does! See, that's how good this extension is: it takes care of my problems before I even know they need to be fixed!

**Comment by BloodDragooner2** [comment]
> Pretty sure it already does that

Tried on firefox (librewolf), and unfortunately, no, it doesn't append `vx` or some other server to the link, which is what the poster was wondering about.

**Comment by dimdenGD** [comment]
I was replying to this:
> Adding to that: it would also be cool if clicking "Copy Link" stripped away all the tracking parameters after the ? character in the URL

**Comment by dimdenGD** [comment]
Added
![image](https://github.com/dimdenGD/OldTwitter/assets/26517362/d6a1ef21-4233-48d9-b0a1-b11ef33097bb)
