### ISSUE TITLE
All link colors are color #NaNNaNNaN

### ISSUE THREAD

**Issue by chillycontro** [dimdenGD/OldTwitter#162]
**Describe the bug**
When on any other person's Twitter profile page, the link color is set to an invalid hex code (#NaNNaNNaN), turning every link on the page black, and the "Tweet" button turns into a mere border.

**To Reproduce**
Go to basically anybody's Twitter profile page.

**Expected behavior**
The link color on the page is either the viewed user's personal link color choice or their former link color.

**Screenshots**
![OldTwitter-Bug1](https://github.com/dimdenGD/OldTwitter/assets/28816808/0aed60f3-ad44-4093-8865-e699ed8ad083)
![OldTwitter-Bug2](https://github.com/dimdenGD/OldTwitter/assets/28816808/51a70fb5-f854-4c47-a412-b8a9062617de)

**Browser**
Mozilla Firefox version 115.0 (64-bit)

**Comment by dimdenGD** [comment]
This doesn't happen to me on Firefox 115

**Comment by dimdenGD** [comment]
Can you check if this is fixed for you on beta?
