### ISSUE TITLE
Timeline is limited

### ISSUE THREAD

**Issue by Saberleo456** [dimdenGD/OldTwitter#163]
**Describe the bug**
Scrolling down far enough causes the timeline to refuse to load further tweets. Somewhere between 500 and 1000 tweets down the see more tweets function stops.

**To Reproduce**
as I hoped to use this to get through rate limiting, I kept scrolling down and only made it 7 hours down, I was hoping for at least 24 hours worth of posts... which with my following could be up to 2000 tweets.

**Expected behavior**
I expected it to continue refreshing older tweets or at least have a limit known for how far back you can scroll before it refuses to serve more old tweets.

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/31599095/46a4e814-a682-47c0-bdf8-e4c7c0e7b541)

**Browser**
Vivaldi 6.1.3035.111 (Stable channel) (64-bit)

**Comment by dimdenGD** [comment]
This seems to be a limitation with current API endpoint I use, unfortunately if I switch to new one there will be no rate limit bypass for home page

**Comment by dimdenGD** [comment]
They're not interchangable and use entirely different format for pagination

**Comment by dimdenGD** [comment]
Seems that Twitter is lowering that limit to 200 so I am fully switching to new API. That fixes this issue.
