### ISSUE TITLE
Unable to use twitter with OldTwitter extension

### ISSUE THREAD

**Issue by jlt525** [dimdenGD/OldTwitter#164]
**Describe the bug**
I am unable to load twitter when using the OldTwitter extension.
I have only been able to access the OldTwitter settings page, but it does not seem to be loading properly (missing images, trends, user card says "loading". see screenshot)
Using `?newtwitter=true` to load the original twitter does work.

**To Reproduce**
1. Install OldTwitter extension
2. Visit https://twitter.com/home

**Expected behavior**
Twitter homepage loads

**Screenshots**
Trying to load the homepage:
![2023-07-05-072020_1623x985_scrot](https://github.com/dimdenGD/OldTwitter/assets/35385142/e3676a55-6a0f-4be1-b5bf-fc71a091e293)

OldTwitter settings page:
![image](https://github.com/dimdenGD/OldTwitter/assets/35385142/a4ec9010-321b-4c37-8dee-c00b81283eaa)

Trying to visit a profile:
![2023-07-05-073556_1623x985_scrot](https://github.com/dimdenGD/OldTwitter/assets/35385142/c85c735e-1ef0-4909-8ce1-9d42405a682e)

**Browser**
Firefox 115.0

**Comment by dimdenGD** [comment]
Are you logged in?

**Comment by jlt525** [comment]
yes, I'm logged in.

**Comment by dimdenGD** [comment]
No idea then, none of the errors in console are helpful and it works fine for me

**Comment by jlt525** [comment]
I found the issue. For some reason uBlock Origin was stopping OldTwitter from working even when turned off. I've reconfigured it and OldTwitter works now.
