### ISSUE TITLE
[ Firefox Bug ] Profile color synchronization doesn't work.

### ISSUE THREAD

**Issue by ktg5** [dimdenGD/OldTwitter#165]
**Describe the bug**
Profile color synchronization doesn't work on Firefox, defaulting to just black for the links.

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/42522603/56f56866-c297-41b0-90cb-55933ab8f356)

**To Reproduce**
Go to any profile.

**Expected behavior**
Change profile links to either "Default link color" or the link color the user has set it to.

**Browser**
Firefox 115.0

**Comment by ktg5** [comment]
Interesting... The same issue happened to a friend of mine who uses Firefox. I'm unsure how to accurately reproduce this issue then.

**Comment by dimdenGD** [comment]
This should be fixed on beta, can you try it out?

**Comment by ktg5** [comment]
Oh, my bad! Somehow did get a notification about this.
But yes it does work now, thank you!
