### ISSUE TITLE
Probably way outside the scope of this, but (late) 2010 Twitter style

### ISSUE THREAD

**Issue by K4sum1** [dimdenGD/OldTwitter#172]
I really like this style, it's hard to find good screenshots though.
https://api.time.com/wp-content/uploads/2014/12/2010-twitter.jpg
https://www.tamurajones.net/img/screens/TwitterNewTwitterHome.png
https://stopdesign.com/wp-content/uploads/2010/09/newtwitter_home_dp_profile_ded.png

**Comment by dimdenGD** [comment]
This is too much work and won't be done
