### ISSUE TITLE
Extension doesn't work on minimum listed Firefox version (48)

### ISSUE THREAD

**Issue by K4sum1** [dimdenGD/OldTwitter#174]
**Describe the bug**
The extension doesn't seem to even attempt to load with Firefox 48

**To Reproduce**
Install extension on Firefox 48

**Expected behavior**
Extension works

**Screenshots**
![ScreenShot_20230706063448](https://github.com/dimdenGD/OldTwitter/assets/77039240/df43b1dc-8a4e-4dad-afbe-8a937c2cea3e)

**Browser**
Firefox 48.0.2

**Comment by dimdenGD** [comment]
I don't know why Firerox says it'll work with such old version, probably because of Manifest used, but it won't work with version older than about 100 and I don't have plans to make it work with such old versions due to modern APIs used

**Comment by K4sum1** [comment]
haha old browser go brrrrr
![ScreenShot_20230706064725](https://github.com/dimdenGD/OldTwitter/assets/77039240/1ceea8a2-6e75-43bd-aa11-94f1321f98b4)

**Comment by TorutheRedFox** [comment]
> haha old browser go brrrrr ![ScreenShot_20230706064725](https://user-images.githubusercontent.com/77039240/251440438-1ceea8a2-6e75-43bd-aa11-94f1321f98b4.png)

based Mypal user

**Comment by K4sum1** [comment]
I actually use Waterfox G5, but I do have a variety of browsers for compatibility testing.

**Comment by TorutheRedFox** [comment]
same
