### ISSUE TITLE
resize Tweet TextBox when writting a reply tweet

### ISSUE THREAD

**Issue by Scowl821** [dimdenGD/OldTwitter#176]
Allow users to be able to resize the reply text-box, both in height and width, so that people can see the totality of the tweet to their heart's content, instead of just the last 2 lines.

Currently the text-box leaves a lot of be desired. and a scroll bar is not very intuitive.
![image](https://github.com/dimdenGD/OldTwitter/assets/76181880/1f10b145-0916-4918-ad81-6d4b9e091fea)
![image](https://github.com/dimdenGD/OldTwitter/assets/76181880/f61859ef-2b1e-42f6-94a0-3910d96187a6)

**Comment by dimdenGD** [comment]
Added slider for replies, won't be added for main tweet composer though
