### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading ’legacy’)

### ISSUE THREAD

**Issue by ktg5** [dimdenGD/OldTwitter#180]
**Describe the bug**
Media tab is replaced with `TypeError: Cannot read properties of undefined (reading ’legacy’)`

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/42522603/fb0ead6b-ff36-4270-890c-a24d524815ea)
[Link to profile](https://twitter.com/xxxsoiu1/media)

**Browser**
Brave v1.52.129 | Chromium 114.1.52.129

**Comment by dimdenGD** [comment]
Fixed
