### ISSUE TITLE
tweets not loading when clicked

### ISSUE THREAD

**Issue by Reckssaurus** [dimdenGD/OldTwitter#181]
**Describe the bug**
when I click a tweet and open it, this shows up and then it fixes itself for a bit and then it happens again.
**Screenshots**
If applicable, add screenshots or video to help explain your problem.

![Captura de tela 2023-07-07 020828](https://github.com/dimdenGD/OldTwitter/assets/138847552/7f011956-bbe3-4d14-9f53-c517bc719722)

**Browser**
firefox

**Comment by dimdenGD** [comment]
This was fixed on beta already
