### ISSUE TITLE
Feature Request: Autoload new tweets

### ISSUE THREAD

**Issue by JaxxArmstrong** [dimdenGD/OldTwitter#183]
Instead of having to click on the text 'See New Tweets' at the top when it finds new tweets I'd very much like to see it autoloads the new tweets (live feed), please.

I've been using https://github.com/anomalyce/twitter-idle-autorefresh for the new Twitter layout and it works great, but not so much using your quite good addon. The addon mentioned bypasses Twitter's only-refresh-when-focused and thus creates a live feed every X seconds.

**Comment by dimdenGD** [comment]
Added. This is experimental and kinda buggy though
