### ISSUE TITLE
Subtle Animations 

### ISSUE THREAD

**Issue by LorshZontek** [dimdenGD/OldTwitter#188]
Basically just smaller subtle animations like on the legacy twitter layout just for some things to feel smoother, but also the option to disable them for those either on lower end systems or just for those that don't want them, video is an example of some.

https://github.com/dimdenGD/OldTwitter/assets/51148276/354efa07-62a7-40f9-9e05-b692a758927e

**Comment by dimdenGD** [comment]
Added animations you showed on video and more
