### ISSUE TITLE
feat: Auto refresh/scroll/update timeline

### ISSUE THREAD

**Issue by mangkoran** [dimdenGD/OldTwitter#189]
First of all, thank you very much for creating this extension. Since the death of old TweetDeck, I switched to use this extension.

I have a feature request regarding auto update. Currently we need to click "see new tweets" to load new tweets. With auto update, timeline could be automatically updated in certain interval.

My guess is that this should be a simple addition, as it seems Twitter itself has periodically check for new tweets. It is just we need to click "see new tweets" to load them.

![image](https://github.com/dimdenGD/OldTwitter/assets/57625126/ec645c97-05e1-40b1-b950-11203b3d1334)

**Comment by dimdenGD** [comment]
This was added already in beta

**Comment by mangkoran** [comment]
May I know which commit?

**Comment by dimdenGD** [comment]
https://github.com/dimdenGD/OldTwitter/commit/83884ec0855056c8985048c45c92c9a38252b3fc
