### ISSUE TITLE
Scrolling on a tweet is janky

### ISSUE THREAD

**Issue by madeline-xoxo** [dimdenGD/OldTwitter#19]
**Describe the bug**
When scrolling on a tweet, it scrolls the whole tweet "frame" instead of scrolling to the comments.

**To Reproduce**
Click on a tweet with more than 6 or so replies, then scroll while your cursor is not over the tweet.

**Expected behavior**
While this is *technically* intended behaviour, its supposed to scroll the comments once the frame has reached the top of the screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/62841684/200824701-4ab7d240-0b67-4aff-9e14-252b6557a423.png)
![image](https://user-images.githubusercontent.com/62841684/200824743-b2278de5-ee8a-4ace-b65d-39aed7f250ac.png)
(doesn't scroll any further)

**Browser**
Firefox, latest

**Comment by dimdenGD** [comment]
With your version you can hover your mouse on tweet frame to scroll.
But I [fixed it](https://github.com/dimdenGD/OldTwitter/commit/e5b44360bc24d6745572c61aa43f63d03df65334) and now in next update you'll be able to scroll at any cursor position. Keep in mind it can take up to a week to receive new update
