### ISSUE TITLE
Changing colours only works for our profiles, is there a way to make it website wide?

### ISSUE THREAD

**Issue by xinomp** [dimdenGD/OldTwitter#191]
Unless this is a bug, could this be an option in the future?

**Comment by dimdenGD** [comment]
![image](https://github.com/dimdenGD/OldTwitter/assets/26517362/aeb2aa33-b44f-4bba-91c2-1bc9d507c8e9)

**Comment by xinomp** [comment]
It doesn't work for me

**Comment by dimdenGD** [comment]
Works fine for me

**Comment by homosexuayla** [comment]
also doesn't work for me

the only way i could fix it is putting the color as a custom css var
like --link-color: rgb(255 120 180)

**Comment by xinomp** [comment]
This actually worked for me

**Comment by TorutheRedFox** [comment]
possible duplicate of my issue? (#96)

**Comment by dimdenGD** [comment]
If someone has Discord, you can help me to debug this issue, my username on discord is `dimden`
