### ISSUE TITLE
Adblocker not working with OldTwitter extension in Microsoft Edge

### ISSUE THREAD

**Issue by ashjaylk** [dimdenGD/OldTwitter#192]
**Describe the bug**
I'm encountering an issue where the adblocker, specifically uBlock Origin (21), is not effectively blocking ads when used in conjunction with the OldTwitter extension. Both extensions are downloaded from the Microsoft Edge Addon Store.

**Steps to reproduce:**

1. Install uBlock Origin (21) and the OldTwitter extension from the Microsoft Edge Addon Store.
2. Navigate to Twitter.
3. Observe that ads are not being blocked by the adblocker.

**Browser**
Microsoft Edge 
Version 114.0.1823.43 (Official build) (64-bit)

**Comment by dimdenGD** [comment]
This was fixed in beta already
