### ISSUE TITLE
apparently some tweets couldn't be loaded

### ISSUE THREAD

**Issue by homosexuayla** [dimdenGD/OldTwitter#194]
the extension gave me this error and said to report it here
`TypeError: Cannot read properties of undefined (reading ’ext’) at appendTweet (chrome-extension://ojicfkfbknneblggkkkdjjkenahkmgni/scripts/helpers.js:1194:19) at renderTimeline (chrome-extension://ojicfkfbknneblggkkkdjjkenahkmgni/layouts/profile/script.js:1034:63) at updateTimeline (chrome-extension://ojicfkfbknneblggkkkdjjkenahkmgni/layouts/profile/script.js:360:5) at undefined (OldTwitter v1.7.3)`

**Comment by dimdenGD** [comment]
fixed
