### ISSUE TITLE
Quote of tweet from suspended account results in error

### ISSUE THREAD

**Issue by Volpeony** [dimdenGD/OldTwitter#195]
**Describe the bug**
A quote tweet featuring a tweet from a suspended account results in a screen displaying TypeError: tweet.quoted_status is undefined

**Screenshots**
![error 1](https://github.com/dimdenGD/OldTwitter/assets/111623749/266285f9-cb0d-44fd-9811-32902941e1b8)
![error 2](https://github.com/dimdenGD/OldTwitter/assets/111623749/33d84cf7-234b-4652-9961-01e0c748a674)

**Browser**
FireFox 114.0.2

**Links**
[Link to profile/tweet or other page where bug happens.](https://twitter.com/Teloss32/status/1588658845701705728)

**Comment by dimdenGD** [comment]
This was fixed already in beta
