### ISSUE TITLE
Loading gif doesn't exist or can't load correctly

### ISSUE THREAD

**Issue by Arcadius2006** [dimdenGD/OldTwitter#197]
**Describe the bug**
Title does that pretty well

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/93880348/8a0baa05-72ba-496e-9bd1-fd74170bed0a)

**Browser**
Google Chrome, Version 114.0.5735.199 (64-bit)

**Comment by Arcadius2006** [comment]
note that the tweets themselves load fine, it's just about the gif not being there

**Comment by dimdenGD** [comment]
do u get any errors in console

**Comment by Arcadius2006** [comment]
ohhhhhhh shit i havent checked for that

sorry

**Comment by Arcadius2006** [comment]
doesnt matter though since it works now
