### ISSUE TITLE
Something Something notifications couldn't load

### ISSUE THREAD

**Issue by Arcadius2006** [dimdenGD/OldTwitter#198]
**Describe the bug**
I can't, most of the details are in the nerdy error text

**Screenshots and error**
![image](https://github.com/dimdenGD/OldTwitter/assets/93880348/b383513c-4fc0-4e83-96a3-96b37927af3a)
`ReferenceError: arrayInsert is not defined at chrome-extension://obnieeijfmamhnbhlpendnbjpjhofcdn/layouts/notifications/script.js:140:25 at Array.forEach (<anonymous>) at renderNotifications (chrome-extension://obnieeijfmamhnbhlpendnbjpjhofcdn/layouts/notifications/script.js:136:40) at async updateNotifications (chrome-extension://obnieeijfmamhnbhlpendnbjpjhofcdn/layouts/notifications/script.js:306:5) (OldTwitter v1.7.3)`

**Browser**
Google Chrome, Version 114.0.5735.199 (64-bit)

**Links**
[THE twitter notification page.](https://twitter.com/notifications)

**Comment by Arcadius2006** [comment]
the issue has been resolved for me, but it'd be good to check on anyway

**Comment by dimdenGD** [comment]
This happened to me once after arrayInsert function was just added but didn't happen since so it was probably some code cache issue
