### ISSUE TITLE
Ads appear in the reply section of tweets.

### ISSUE THREAD

**Issue by EZ2Alpa** [dimdenGD/OldTwitter#199]
**Describe the bug**
When I look at the replies normally, I see ads.
Is this a bug?

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/139020260/0084a5cd-0abe-499c-b272-0b6feff043d8)

**Browser**
Google Chrome Ver.114.0.5735.199（Official Build）

**Comment by dimdenGD** [comment]
This was fixed in beta

**Comment by EZ2Alpa** [comment]
I see that this has been fixed in the beta release. I'm using the chrome extension version 1.7.2. I wonder why it was released...maybe it's just me...?

**Comment by dimdenGD** [comment]
Current latest version is 1.7.3, it's not released on extension stores right now and can only be installed from code

**Comment by EZ2Alpa** [comment]
so you mean the latest version (1.7.3) of the chrome extension version is not released now. I'll be waiting for the update. 
Good luck with the development!
