### ISSUE TITLE
twitter circles support

### ISSUE THREAD

**Issue by jkrosado** [dimdenGD/OldTwitter#20]
i can't tweet to my circle in oldtwitter

**Comment by dimdenGD** [comment]
You can:  
![gif](https://lune.dimden.dev/7973dc8fd6.gif)

**Comment by jkrosado** [comment]
oh, i used the tweet button where it doesn't appear
<img width="622" alt="Screen Shot 2022-11-11 at 6 22 28 PM" src="https://user-images.githubusercontent.com/26725277/201443656-e97508ed-83f0-4b4f-9188-0bae2f114e76.png">

**Comment by dimdenGD** [comment]
Yeah that one doesn't have all features of tweeting, have to use one on homepage
