### ISSUE TITLE
Account signed in on incognito + tweets don't show on incognito with plugin

### ISSUE THREAD

**Issue by MrSkullium** [dimdenGD/OldTwitter#200]
**Describe the bug**
Whenever you open a tweet with incognito, your account still shows up as well as the tweets not loading (will also go in an infinite login loop if you click on another link). However this doesn't apply when you turn the plugin off for incognito as you will not be be signed in (as it should be) as well as being able to view the tweet (Twitter silently removed the requirement to be signed in order to view tweets)

**Screenshots**
Here is the a tweet with the addon enabled for incognito. Notice my account still being logged in on a freshly opened tab.
![Screenshot (1864)](https://github.com/dimdenGD/OldTwitter/assets/66441517/fb83eac4-f9f0-4288-90f4-8a51d6aa5eda)

Here is a tweet without the plugin enabled for incognito. 
![Screenshot (1865)](https://github.com/dimdenGD/OldTwitter/assets/66441517/d43b13fe-e897-45c9-9510-6e1280243e20)

**Browser**
Firefox 84.0b8 (I know it's very outdated but shouldn't effect it too much as it works normally otherwise)

**Comment by dimdenGD** [comment]
There's nothing I can do about this, its just how caching in extension works, do not have extension enabled in incognito as it doesnt work without account
