### ISSUE TITLE
Some tweets couldn't be loaded due to errors.

### ISSUE THREAD

**Issue by ebonyraven** [dimdenGD/OldTwitter#201]
**Describe the bug**
Tried to scroll to the earliest posts on someone's Twitter and nothing before a certain date loaded. The error pop-up said to copy the text below and send it here. 
TypeError: Cannot read properties of undefined (reading ’ext’) at appendTweet (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/scripts/helpers.js:1185:19) at renderTimeline (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/layouts/profile/script.js:1018:63) at updateTimeline (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/layouts/profile/script.js:344:5) at undefined (OldTwitter v1.7.2)

**Browser**
chrome , Version 114.0.5735.199

**Links**
https://twitter.com/Reyhans_Art

**Comment by dimdenGD** [comment]
This was fixed on beta already
