### ISSUE TITLE
Feature request: Filter out non-followed posts

### ISSUE THREAD

**Issue by JaxxArmstrong** [dimdenGD/OldTwitter#203]
Is there a tag on the posts in your Twitter feed that would make it possible for your addon to filter out the posts that shows up that aren't coming from any of the ones you are currently following, please?

If so, please add that as an option.

**Comment by dimdenGD** [comment]
Already exists, choose "Reverse chronological" timeline type in settings

**Comment by JaxxArmstrong** [comment]
Well, I have it set on option, but it still incorporates posts from not-followed-Twitter-users.

**Comment by dimdenGD** [comment]
Are you sure you don't have "Reverse chronological with friends likes" enabled

**Comment by JaxxArmstrong** [comment]
![Twitter settings screenshot 1](https://github.com/dimdenGD/OldTwitter/assets/13659704/754988dc-defc-4d46-b151-c50dc7256d4f)

**Comment by dimdenGD** [comment]
I don't think what you're saying is possible since it just shows tweets API gives to oldtwitter

**Comment by JaxxArmstrong** [comment]
Unfortunately, it's quite possible. How do I completely reset your addon's settings, please?  I cleared all of Twitters local storage, cookies etc.

**Comment by dimdenGD** [comment]
you can only do that by uninstalling and installing again

**Comment by JaxxArmstrong** [comment]
So, I've cleaned out all cookies, Local storage etc for Twitter.com.  I've also removed and re-added the addon and set the proper timeline.

Still the same issue that tweets from users I don't follow shows up in my timeline. All users with the green symbol.
