### ISSUE TITLE
Tweets not loading when opened

### ISSUE THREAD

**Issue by 13thsinnr** [dimdenGD/OldTwitter#207]
TypeError: Cannot read properties of undefined (reading ’ext’) at appendTweet (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/scripts/helpers.js:1182:49) at renderTimeline (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/layouts/profile/script.js:1018:63) at updateTimeline (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/layouts/profile/script.js:344:5) at undefined (OldTwitter v1.7.2)

**Comment by dimdenGD** [comment]
This was fixed in beta
