### ISSUE TITLE
Download media not working.

### ISSUE THREAD

**Issue by lostinnowhere** [dimdenGD/OldTwitter#211]
I click [Download Media] but nothing happen

Firefox 115.0.1 (64-bit)

![image](https://github.com/dimdenGD/OldTwitter/assets/139092087/71e3077a-9eb9-43b2-bb1f-d7269507b1b9)

**Comment by dimdenGD** [comment]
You didn't include link to tweet as said in bug template, I can't reproduce this

**Comment by lostinnowhere** [comment]
Firefox's Enhance tracking protection in Strict mode prevented OldTwitter from downloading media files. I think I'll have to manually turn it off whenever I wanna download media files.
![image](https://github.com/dimdenGD/OldTwitter/assets/139092087/259527f4-9fd4-44ae-b322-93ce4e0d723d)
