### ISSUE TITLE
Korean Translation Update

### ISSUE THREAD

**Issue by Wintiger0222** [dimdenGD/OldTwitter#212]
The Korean translation was strange, so I translated it again as close as possible to Twitter in 2015. Due to the nature of the Korean language, some text should be inverted, so I would like to ask if it is possible. (If you search for todo in the json file, you can se my note)
[messages.zip](https://github.com/dimdenGD/OldTwitter/files/11998533/messages.zip)

(P.S. my twitter account is @han_erin)

**Comment by dimdenGD** [comment]
Implementing this right now, also @han_erin on twitter says user doesn't exist

**Comment by Wintiger0222** [comment]
sorry, there was misstypo. It's [@han_eirin](https://twitter.com/han_eirin). 
And I a little updated the json file. I was in a hurry to translate at work, so I missed some things.
Next time, I'll use pull request.
[messages.zip](https://github.com/dimdenGD/OldTwitter/files/12002170/messages.zip)

**Comment by dimdenGD** [comment]
Added and fixed TODOs, thanks
