### ISSUE TITLE
Option to view high resolution images

### ISSUE THREAD

**Issue by Davr1** [dimdenGD/OldTwitter#22]
It would be nice if you could change the viewer image resolution, or have it set to the original resolution by default. Other extensions, which are unfortunately incompatible, do it by appending parameters to the url: 
`https://pbs.twimg.com/media/XXXXXXXXXXX?format=...&name=...`
where format is either `jpg` or `png`
and name is one of `thumb` `small` `medium` `900x900` `large` `4096x4096` `orig` (note that orig doesn't work with png)

**Comment by dimdenGD** [comment]
Thank you for bringing this up. I [added](https://github.com/dimdenGD/OldTwitter/commit/7fa08eb2ef87b67b3d912417b6c7e2072d4111ef) setting that will be enabled by default to show original images.  
Keep in mind that it can take up to a week to receive new update.
