### ISSUE TITLE
Some videos still autoplay even when autoplay is disabled.

### ISSUE THREAD

**Issue by iiv3** [dimdenGD/OldTwitter#221]
I always disable video autoplay, old and new twitter.

However when using OldTwitter v1.7.3 , some videos still play.

The few that I checked seems to be .mp4 files without sound and "new twitter" tags them as "GIF"

I'm using linux Chromium build.

Here is an example tweet:
https://twitter.com/radsechrist/status/1678273843432157184

**Comment by dimdenGD** [comment]
They play because they're gifs not videos, just encoded into mp4, having option to not play gifs would be other issue which already exists: https://github.com/dimdenGD/OldTwitter/issues/86

**Comment by iiv3** [comment]
I understand that twitter threats them as gifs, but 
technically mp4 is video format using video codec (usually h264).

GIF is something entirely different (like using 8 bit palette color).

The "new twitter" also disables autoplay for both "gif" and "normal" videos with a single option.

So far I love the extension, but I can't use it like that.

**Comment by dimdenGD** [comment]
Added option to disable GIF autoplay
