### ISSUE TITLE
Switching between Old / New not working in macOS?

### ISSUE THREAD

**Issue by ylluminate** [dimdenGD/OldTwitter#222]
**Describe the bug**
control/command-alt/option-0 not switching between old and new Twitter.

**Screenshots**
Not really applicable - it's a rather simple issue.

**Browser**
Both Chrome 114.0.5735.198 and Ungoogled Chromium 114.0.5735.198.

**Links**
Generally.

**Comment by dimdenGD** [comment]
it's letter O, not number 0

**Comment by ylluminate** [comment]
Alright so `control-option-o` (letter o) does indeed work. I suppose the instructions should use the small letter `o` to differentiate better since it is not actually a capital (shift-o) and it would help one to discern the not-`0` differential.
