### ISSUE TITLE
User defined extension click action

### ISSUE THREAD

**Issue by ylluminate** [dimdenGD/OldTwitter#223]
I think it would be nice to have the option to make left-click of the extension icon toggle/switch between Old and New Twitter vs going to options/settings. We already have the right click → `Open settings` which is more intuitive to get settings for this, so I think UX wise, toggling the extension's state between on and off would be more intuitive.

**Comment by dimdenGD** [comment]
This won't be done since it requires 1 more permission, there's already a button to go to new Twitter on bottom-right of page. You can also use `CTRL+ALT+O` hotkey.
