### ISSUE TITLE
I can't see my own tweets

### ISSUE THREAD

**Issue by Exorcism0666** [dimdenGD/OldTwitter#224]
**Describe the bug**
The fact that I've made my account private means I can't see my own tweets

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/46537034/d03d797c-8abd-4fcd-9b43-45503ccdf198)

**Browser**
Ungoogled-Chrome

**Links**
https://twitter.com/Exorcism0666

**Comment by dimdenGD** [comment]
version of oldtwitter?

**Comment by dimdenGD** [comment]
this was fixed on 1.7.3.1 and its pending approval on chrome web store already

**Comment by Exorcism0666** [comment]
oh nice tysm!
