### ISSUE TITLE
unable to view my own tweets when logged into private acct

### ISSUE THREAD

**Issue by bloodtypeoh** [dimdenGD/OldTwitter#225]
**Describe the bug**
refer to title

**Screenshots**
![Screenshot 2023-07-10 at 5 01 31 PM](https://github.com/dimdenGD/OldTwitter/assets/130262567/7a74778e-9390-4c0d-b924-8e0d0bf7a682)

**Browser**
Chromium Engine Version 114.0.5735.198

**Links**
[not linking my private sorry!](https://twitter.com/acct_username)

**Comment by dimdenGD** [comment]
oldtwitter version?

**Comment by bloodtypeoh** [comment]
v1.7.3

**Comment by dimdenGD** [comment]
this was fixed on 1.7.3.1 and its pending approval on chrome web store already

**Comment by bloodtypeoh** [comment]
got it, thank you!
