### ISSUE TITLE
[Visual Bug] Incorrect icon border radius and color on certain pages

### ISSUE THREAD

**Issue by NoelleCoolGirl** [dimdenGD/OldTwitter#228]
When on the [user bookmarks tab](https://twitter.com/i/bookmarks), the user icon in the left-cell is given the border color 'white', instead of var(--background-color). 

Additionally, the icon loads as un-rounded when using the rounded icons option in the settings, before updating to be rounded. I don't know if it's related, but once the source for the image is included after loading, the radius is also adjusted accordingly.

![weird bug](https://github.com/dimdenGD/OldTwitter/assets/139192699/d3da0679-98d3-4a9d-beb3-a5a6f7a3bdd1)

As of right now, I've only seen this appear on this one page, but I will update this page or submit a new report if I catch it anywhere else! Thank you all for your work :]

[ I am using Firefox 115.0.1 ]

**Comment by dimdenGD** [comment]
Fixed
