### ISSUE TITLE
Site wont open if extension is removed

### ISSUE THREAD

**Issue by Tenzubushi** [dimdenGD/OldTwitter#23]
**Describe the bug**
Once u uninstall / remove the extension (Old twitter) from your browser to use the normal UI, the original site gets broken until you reinstall / re-enable the extension, softlocking myself into the old twitter theme.

**To Reproduce**
(using operaGX).  install the extension trough chrome store, Use it normally and tweet something, uninstall the extension while leaving a window open using the extension, reload the site, now the original URL with the original site says :
"Something went wrong, but don’t fret — let’s give it another shot." 
(a button saying "try again" will appear, which once clicked will reload the site with no changes)
(after doing this, the site will be broken no matter what browser i use) 
(Account used in phone will remain normal with no issue)

**Expected behavior**
Twitter site should open normally when the extension on my browser is uninstalled.

**Screenshots**
![image_2022-11-21_032218920](https://user-images.githubusercontent.com/117323515/202979495-b417ca57-8dca-4195-8e30-f56ca285fb3f.png)
![image_2022-11-21_032331435](https://user-images.githubusercontent.com/117323515/202979683-0ede86bb-3814-4495-89a6-a8b12627d29c.png)

**Browser**
OperaGX, most updated version till this date (november 21 2022).

**Comment by Tenzubushi** [comment]
i just tried uninstalling the extension then restarting my pc, but still not working.
plus i try to use some of the other extensions that do the same, such as "good twitter"
and keeps appearing that broken site.

**Comment by dimdenGD** [comment]
Weird, I tested it on Opera, Firefox and Chrome and never had any issues with uninstalling it, everything goes back to normal twitter just after.
The thing is that extensions don't really have any control of what happens after you uninstall extension (they can only set uninstall url, that's it)
If you said it happens only in Opera GX and twitter works in other browsers I'd say that it's a weird bug in Opera's code, but you're saying it happens in all browsers, so I really have no idea why. I have zero control over what happens after uninstallation

**Comment by Tenzubushi** [comment]
hm, i had the theory that the exstension changed or added some kind of
files into my pc when using it and when i uninstalled it the remaining
files made my browser go crazy.... but if you say that the extension only
changes the URL then im really confused.
im not really complaining about your extension, is actually pretty nice but
loosing the option to go back feels odd to me
thanks for the help anyways bro

**Comment by Tenzubushi** [comment]
would it help if i show you some code in the inspector window? maybe there
is something happening

**Comment by dimdenGD** [comment]
You can show I guess
Btw extensions cant even change files on computer unless it prompts to change specific folder

**Comment by Tenzubushi** [comment]
okay, i will share everything i can, should i dm you via twitter?

**Comment by dimdenGD** [comment]
You can do it wherever you want btw I'm talking from Github page and you seem to use emails and there's option to upload files here https://github.com/dimdenGD/OldTwitter/issues/23

**Comment by TukangM** [comment]
instruction unclear. won't fix #1130 issue
