### ISSUE TITLE
Write new tweet input form is buggy

### ISSUE THREAD

**Issue by Wintiger0222** [dimdenGD/OldTwitter#236]
**Describe the bug**
![Cap 2023-07-11 22-48-30-088](https://github.com/dimdenGD/OldTwitter/assets/24960466/a7dd04c1-52d6-4a9c-a0eb-8a4e488ff841)
![Cap 2023-07-11 22-48-20-920](https://github.com/dimdenGD/OldTwitter/assets/24960466/359b8ab3-113e-4300-b252-da8941b1c8af)
![image](https://github.com/dimdenGD/OldTwitter/assets/24960466/76e9da26-842c-491d-8268-dc2251c2f287)

When window size is little narrow, new tweet input  form's width work's strangely.

**Browser**
Chrome 114.0.5735.199

**Links**
It happend at home

**Comment by dimdenGD** [comment]
Works fine for me on small window
![image](https://github.com/dimdenGD/OldTwitter/assets/26517362/f2fc7266-e770-49bd-93df-cc552d37b3aa)

**Comment by Wintiger0222** [comment]
https://github.com/dimdenGD/OldTwitter/assets/24960466/1151dc82-1aa7-4572-8fe6-a6c87c1e2faa
It happen when left cells are still stick on left window, but center cell is larger than it's original size
I'm now using stable 1.7.3.3

**Comment by Wintiger0222** [comment]
https://github.com/Wintiger0222/OldTwitter/commit/122473eda91486a3b2a7a7afc3e8d00889e874b4
I fixed this issue in this commit.
