### ISSUE TITLE
bug with tweet that are longer than 280 characters

### ISSUE THREAD

**Issue by omelettejoyeuse** [dimdenGD/OldTwitter#237]
tweets with more than 280 character appear buggy and you can't see the tweet past the 280 character limit.

![bug 1](https://github.com/dimdenGD/OldTwitter/assets/68649435/25bf679b-a859-4b52-9e6e-041f0a891a0f)
![bug 2](https://github.com/dimdenGD/OldTwitter/assets/68649435/6968925c-7b7d-4c17-bfca-cbfc20ba2a48)
![original tweet](https://github.com/dimdenGD/OldTwitter/assets/68649435/e36a682a-12f3-46af-9544-2bb5902b0499)

**Browser**
Google Chrome Version 114.0.5735.199

**Links**
[see from my profile.](https://twitter.com/omelettejoyeuse)
[original tweet](https://twitter.com/omelettejoyeuse/status/1678411182523179017)

**OldTwitter version 1.7.3**

**Comment by dimdenGD** [comment]
Fixed
