### ISSUE TITLE
Some tweets couldn't be loaded due to errors

### ISSUE THREAD

**Issue by HaPearu** [dimdenGD/OldTwitter#238]
TypeError: Cannot read properties of null (reading ’append’) at appendTweet (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/scripts/helpers.js:2874:31) at async updateReplies (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/layouts/tweet/script.js:185:13) at 1678356557770420227 (OldTwitter v1.7.3.1)

**Comment by HaPearu** [comment]
TypeError: Cannot read properties of null (reading ’append’) at appendTweet (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/scripts/helpers.js:2874:31) at async updateReplies (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/layouts/tweet/script.js:176:29) at async chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/layouts/tweet/script.js:1029:13 at 1678356399905206273 (OldTwitter v1.7.3.1)

**Comment by dimdenGD** [comment]
Does this repeatedly happen on every refresh

**Comment by HaPearu** [comment]
No. It went away but I reported it anyway just in case it's something you need to fix.
