### ISSUE TITLE
Trying to load "Favorites" (or likes) menu causes a "Something went wrong" error

### ISSUE THREAD

**Issue by SuperNoahPlushes** [dimdenGD/OldTwitter#24]
**Describe the bug**
Clicking the favorites button (with the number underneath) caused an error to occur.

**To Reproduce**
Go onto any (i presume) tweet and click the favorites button.

**Expected behavior**
A list to show up with the users who have liked my tweet.

**Screenshots**
![image](https://user-images.githubusercontent.com/89299730/203491844-f3221907-7792-4ef6-81d5-b6f20608f7a9.png)
![image](https://user-images.githubusercontent.com/89299730/203491875-73f17862-e872-4cc5-8863-705f3012804b.png)
and the text was 
ReferenceError: mainTweetLikers is not defined at appendTweet (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/scripts/helpers.js:1258:26) at async TweetViewer.updateLikes (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/scripts/tweetviewer.js:244:25) (OldTwitter v1.6.5.2)

**Browser**
Opera GX LVL 4 (core: 92.0.4561.64)
![image](https://user-images.githubusercontent.com/89299730/203492209-4b42f72f-bc2e-46eb-89b4-94f0f4aaa9c0.png)
*however* at the time of the error the version was: LVL 4 (core: 91.0.4516.106)
![image](https://user-images.githubusercontent.com/89299730/203492185-c444036a-2fdf-4763-8c10-3df49b1ae3f8.png)

Hope this helps!

**Comment by SuperNoahPlushes** [comment]
update, it seems to only sometimes happen, not sure what causes it. ill update you if i figure it out

**Comment by dimdenGD** [comment]
This was already fixed in 1.6.5.3, reinstall extension to get updated
