### ISSUE TITLE
trending toggle

### ISSUE THREAD

**Issue by marciebeans** [dimdenGD/OldTwitter#241]
the trending section is constantly full of the twitter userbase's absolute brain rot...would love a toggle to turn it off! especially since blocking it with adblock doesn't work for me for some reason, there's currently no way to not see it.

thanks for this extension, btw, it's the only thing keeping this site usable lol

**Comment by dimdenGD** [comment]
![image](https://github.com/dimdenGD/OldTwitter/assets/26517362/45c5b642-09ba-42d5-a7ea-d6b9b63d0220)
Already exists
