### ISSUE TITLE
Hide Threads/Who to Follow not working

### ISSUE THREAD

**Issue by SenselessVirus** [dimdenGD/OldTwitter#242]
The new "Hide Threads" and "Hide Who to Follow" settings refuse to work, I've tried everything to try and refresh the browser so the settings apply but it never works, it just acts like the boxes aren't ticked.
![Clipboard02](https://github.com/dimdenGD/OldTwitter/assets/139281426/f315e4ad-b063-4fcc-96f9-572d11fd51be)

**Browser**
Mozilla Firefox v115.0.2 (64-bit)

**Links**
https://twitter.com/old/settings, https://twitter.com/home

**OldTwitter version**
Running OldTwitter v1.7.3.3b

**Comment by dimdenGD** [comment]
Works fine for me. If you have Discord you can help debugging this, my username is `dimden`
