### ISSUE TITLE
`Rate limit exceeded`

### ISSUE THREAD

**Issue by ktg5** [dimdenGD/OldTwitter#243]
**Describe the bug**
Got rate limited once again, this time it showed up a different error/message.

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/42522603/c7344f15-90d0-45d0-a390-3ab7c78fc154)

**Links**
[Link to profile](https://twitter.com/_ktg5)

**OldTwitter version**
OldTwitter v1.7.3.3

**Browser**
Brave v1.52.129 | Chromium 114.1.52.129

**Comment by dimdenGD** [comment]
Happy birthday, this is impossible to fix though

**Comment by ktg5** [comment]
Actually just as I reported this issue it didn't show up anymore. Very interesting...  (Also thank you!)
