### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by liarsatsuki** [dimdenGD/OldTwitter#25]
TypeError: Error in invocation of i18n.detectLanguage(string text, function callback): No matching signature. at appendTweet (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/scripts/helpers.js:972:125) at renderTimeline (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/layouts/home/script.js:348:23) at updateTimeline (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/layouts/home/script.js:197:9) at 1596552861495701504 (OldTwitter v1.6.5.3)

**Comment by dimdenGD** [comment]
Thanks for reporting, fixed
