### ISSUE TITLE
Twitter fails to load

### ISSUE THREAD

**Issue by yavko** [dimdenGD/OldTwitter#250]
**Describe the bug**
whenever opening twitter its blank and says "Something went wrong, but don’t fret — let’s give it another shot."

**Screenshots**
If applicable, add screenshots or video to help explain your problem.
![image](https://github.com/dimdenGD/OldTwitter/assets/15178513/e24a2372-6cd0-4ac4-b40c-13ac44867e55)

**Browser**
![image](https://github.com/dimdenGD/OldTwitter/assets/15178513/dbcfe3ea-e63f-44e4-84de-bdf29f77eff4)

**Links**
everywhere

**OldTwitter version**
1.7.3.3c

**Comment by dimdenGD** [comment]
do you gets errors in console (F12 -> Console)

**Comment by yavko** [comment]
![image](https://github.com/dimdenGD/OldTwitter/assets/15178513/a903d078-f674-4eb8-9a81-309ec26d110f)
![image](https://github.com/dimdenGD/OldTwitter/assets/15178513/1218742f-3b16-4362-97a6-aabb379bd75c)
seems the js is from the extension

**Comment by yavko** [comment]
Also it seems that only happens when not logged in

**Comment by dimdenGD** [comment]
This extension doesn't work without account

**Comment by yavko** [comment]
> This extension doesn't work without account

Ah
