### ISSUE TITLE
Can't login to twitter when not loggined

### ISSUE THREAD

**Issue by seiya-git** [dimdenGD/OldTwitter#251]
**Describe the bug**
Error page is displayed, no login form

**Screenshots**
![IMG](https://github.com/dimdenGD/OldTwitter/assets/7394323/5f62ae69-37ee-4f43-a2fa-5cf04b590254)

**Browser**
Firefox 116 beta

**Links**
twitter.com

**OldTwitter version**
1.7.7.3c

**Comment by dimdenGD** [comment]
Works for me on Firefox 115

**Comment by seiya-git** [comment]
@dimdenGD it's happening on fresh Firefox install with only add-on installed

**Comment by dimdenGD** [comment]
Fixed
