### ISSUE TITLE
Translation to the Swahili Language

### ISSUE THREAD

**Issue by IanoNjuguna** [dimdenGD/OldTwitter#252]
I'd like to make a contribution to this project by translating the extension into the Kiswahili Language.

**Comment by IanoNjuguna** [comment]
@dimdenGD I've started to work on the contribution. Any heads up before I dig in deeper?

**Comment by dimdenGD** [comment]
Hi, you can read everything you need to know about extension translation here: https://github.com/dimdenGD/OldTwitter/tree/master/_locales#readme

**Comment by IanoNjuguna** [comment]
Sure thing.
