### ISSUE TITLE
replies not working

### ISSUE THREAD

**Issue by molliemauk** [dimdenGD/OldTwitter#254]
getting "Sorry, you are not authorized to see this status." on replies to own tweets as well as others. using firefox. oldtwitter v1.7.3.3c screenshot below.

![sorry](https://github.com/dimdenGD/OldTwitter/assets/139420797/c65df9e9-a205-48dc-8ee9-ab2cba404361)

**Comment by Muffinmaker2** [comment]
![image](https://github.com/dimdenGD/OldTwitter/assets/107619523/2ce1c545-624a-4eb8-baed-1eaf91824abd)
same here :(

**Comment by citrusfields** [comment]
<img width="339" alt="Screenshot 2023-07-13 at 16 41 29" src="https://github.com/dimdenGD/OldTwitter/assets/135016619/0c64129b-56ee-4a40-8989-1b37bace5565">
 
i'm having the same issue. started getting it today while i was locked/private. unlocked my account and reinstalled the extension but it persists

**Comment by dimdenGD** [comment]
Fixed
