### ISSUE TITLE
Unable to retweet while OldTwitter is active

### ISSUE THREAD

**Issue by cyanindya** [dimdenGD/OldTwitter#255]
**Describe the bug**
As the title itself explains. I think it started... this morning, when I noticed that I have been unable to retweet stuffs at all while using OldTwitter. I tried to do it in all of my accounts, and in both timeline and user profiles alike. Can't RT, but can like just fine.

I tried to check the console while attempting to RT from my private account (screenshot below), and it seems that something is failing from the Twitter API.

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/19756942/77f57253-b266-4466-adf5-4b09f35e1349)

**Browser**
Google Chrome Version 114.0.5735.199

**Links**
-

**OldTwitter version**
1.7.3.3

**Comment by CrimsonHellRider** [comment]
Also happening to me, can't retweet on Old Twitter, though Likes/Favorites work okay.

Browser: Google Chrome Version 114.0.5735.199 (Official Build) (64-bit)

OldTwitter version: 1.7.3.3

**Comment by dimdenGD** [comment]
Fixed
