### ISSUE TITLE
More UI customizations

### ISSUE THREAD

**Issue by dimdenGD** [dimdenGD/OldTwitter#257]
- [x] Option to select tweet text font
- [x] Options to add Me, Lists, Bookmarks and other things to navbar
- [x] User-friendly color editing
- [x] Profile custom CSS?

**Comment by aloneunix** [comment]
Don't know about whole custom CSS, but how about making a feature to upload just a background picture for a profile, like how it was back in 2013? This bg would appear in account's profile and home timeline

**Comment by swoonet** [comment]
Main things I'd like is a floating download button on top of the image, change naming format of downloaded media, and to change scroll functionality to cycle images instead of zoom.

**Comment by SabreRunner** [comment]
[] A Mark as read button that hides a tweet from the feed(?)
