### ISSUE TITLE
Internal: Unspecified on profiles.

### ISSUE THREAD

**Issue by MarisaKirisame-ze** [dimdenGD/OldTwitter#262]
**Describe the bug**
When I go to a profile, it says "Internal: Unspecified".

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/86389939/984d2ed3-ddc9-4abe-8b5d-908019a99f9a)

**Browser**
Google Chrome Version 114.0.5735.199 (Official Build) (64-bit)

**Links**
https://twitter.com/2huPosting

**OldTwitter version**
OldTwitter 1.7.3.4

**Comment by swoonet** [comment]
It appears to be doing this on bookmarks and searches too.

**Comment by dimdenGD** [comment]
This is just Twitter having some random issues, nothing really to fix
