### ISSUE TITLE
List cannot be found

### ISSUE THREAD

**Issue by InfiniteRizard** [dimdenGD/OldTwitter#263]
Trying to access my Lists, I get an error that the List cannot be found.

![image](https://github.com/dimdenGD/OldTwitter/assets/129249574/5ad8d30f-8c05-4e72-8f74-ecf311c68e86)

**Browser**
Opera GX (gonna copy the entire text): Your version is LVL 5 (core: 100.0.4815.44)

**OldTwitter version**
v1.7.3.4

**Comment by dimdenGD** [comment]
Link to list?

**Comment by InfiniteRizard** [comment]
It fixed itself like a day after. I'm gonna close this.
