### ISSUE TITLE
[BUG]Old Twitter doesn't work when opening twitter space

### ISSUE THREAD

**Issue by Shiva953** [dimdenGD/OldTwitter#264]
**Describe the bug**
A link to a twitter space(eg - https://twitter.com/i/spaces/1OwGWwwDmlDGQ ) opens the default twitter theme instead of using old twitter despite of the fact that its enabled. This isn't the case when opening the twitter homepage.

**Screenshots**
Twitter Homepage[Old Twitter works fine]
<img width="912" alt="Screenshot 2023-07-15 at 12 22 29 PM" src="https://github.com/dimdenGD/OldTwitter/assets/120790871/6567ff15-58ff-49cb-8bba-015f4e6eb15f">

Twitter Space[Old Twitter disappears]
<img width="1381" alt="Screenshot 2023-07-15 at 12 22 48 PM" src="https://github.com/dimdenGD/OldTwitter/assets/120790871/84c2fb2c-c6d3-49c3-b5bc-f43e026346a9">

**Browser**
Google Chrome
Version 114.0.5735.198 (Official Build) (arm64)

**Links**
https://twitter.com/i/spaces/1OwGWwwDmlDGQ

**OldTwitter version**
v1.7.3.4

**Comment by dimdenGD** [comment]
OldTwitter won't be supporting Twitter Spaces.
