### ISSUE TITLE
Setting profile link color responds with an error

### ISSUE THREAD

**Issue by jexxinium** [dimdenGD/OldTwitter#266]
**Describe the bug**
When trying to set the color of the links on the profile, an error shows up saying "Error setting link color" after clicking the "Sync" button.

**Screenshots**
https://github.com/dimdenGD/OldTwitter/assets/91823966/cb858127-810f-457a-a008-596940592519

**Browser**
[Firefox 115 on Windows 10](https://www.whatismybrowser.com/detect/what-version-of-firefox-do-i-have)

**Links**
[Settings page.](https://twitter.com/old/settings)

**OldTwitter version**
Running [OldTwitter](https://github.com/dimdenGD/OldTwitter) v1.7.3.4 (last version: 1.7.3.4).

**Comment by Nightcaat** [comment]
Getting this on both Firefox 115.0.2 and Edge 114.0.1823.82 on Windows 10 with OldTwitter v1.7.3.4

**Comment by dimdenGD** [comment]
Fixed

**Comment by jexxinium** [comment]
Thank you, when will you release the update?

**Comment by dimdenGD** [comment]
This should work even without updating
