### ISSUE TITLE
Minor changes in Japanese translation and translation to Korean

### ISSUE THREAD

**Issue by Nyankodasu** [dimdenGD/OldTwitter#27]
Minor changes were made to Japanese and translated into Korean.
Please apply them.
Also, this is just a small request, so don't worry about it too much, but I'll send you a link to my translator change Github to [Twitter](https://mobile.twitter.com/Nyankodasu1234)

[messages_japan.zip](https://github.com/dimdenGD/OldTwitter/files/10128581/messages_japan.zip)  
[messages_korea.zip](https://github.com/dimdenGD/OldTwitter/files/10128582/messages_korea.zip)

**Comment by Nyankodasu** [comment]
https://twitter.com/Nyankodasu1234

**Comment by dimdenGD** [comment]
Thanks
