### ISSUE TITLE
Circle reply says I'm replying to MY circle when I reply to someone elses circle-tweet

### ISSUE THREAD

**Issue by dstN** [dimdenGD/OldTwitter#270]
**Describe the bug**
Twitter Circle-Reply I did to another Users Circle-Tweet shows up as it was a tweet in MY circle

**Screenshot**
I'm replying  to a Circle-Tweet from "otherUser" and the notice at the bottom says it's a tweet in **MY** circle.
![image](https://github.com/dimdenGD/OldTwitter/assets/960879/ac3f427b-a029-4ffd-8f64-0014747ba30b)

**Extra Info**
If the "otherUser" is replying to his own circle-tweet it's correct again.

**Browser**
Chrome Version 114.0.5735.199

**Links**
Not possible, because circle-tweet.

**OldTwitter version**
"Running [OldTwitter](https://github.com/dimdenGD/OldTwitter) v1.7.3.4 (last version: 1.7.3.4)."

**Comment by dimdenGD** [comment]
Fixed where possible
