### ISSUE TITLE
Bidirectional text

### ISSUE THREAD

**Issue by AhmadFudl** [dimdenGD/OldTwitter#271]
Bidirectional text tweets is fucked up left goes to right and right goes to left it's a mess

Tweet Example
![image](https://github.com/dimdenGD/OldTwitter/assets/57303112/a1c3e25e-3892-4e24-84bf-bce82f8cac23)

How it should look like
![image](https://github.com/dimdenGD/OldTwitter/assets/57303112/8ba79b63-f1a7-487c-a6df-0b23d302840a)

**Browser**
Chrome

**Links**
https://twitter.com/ahmadalfy/status/1681404824955305992

**OldTwitter version**
Running [OldTwitter](https://github.com/dimdenGD/OldTwitter) v1.7.3.4 (last version: 1.7.3.4).

**Comment by dimdenGD** [comment]
Fixed

**Comment by AhmadFudl** [comment]
how long does it take for the fix to be released on chrome @dimdenGD

**Comment by dimdenGD** [comment]
Probably a week or so
