### ISSUE TITLE
Bookmarks page is broken (TypeError: b.full_text is undefined)

### ISSUE THREAD

**Issue by JohnDDuncanIII** [dimdenGD/OldTwitter#272]
**Describe the bug**
The bookmarks page doesn't load and throws `TypeError: b.full_text is undefined` at

`renderBookmarks()` ... `bigFont: b.full_text.length < 75`

**Screenshots**
![Screenshot 2023-07-19 at 5 17 48 PM](https://github.com/dimdenGD/OldTwitter/assets/9257785/dc84f420-8f66-4e57-a336-de4909d403ab)

**Browser**
Firefox 115.0.2 (64-bit) on macOS Ventura M1

**Links**
https://twitter.com/i/bookmarks

**OldTwitter version**
`1.7.3.4`

**Comment by dimdenGD** [comment]
Fixed
