### ISSUE TITLE
_Missing: No status found with that ID.

### ISSUE THREAD

**Issue by MegaTeam89** [dimdenGD/OldTwitter#273]
**Describe the bug**
Tweet does not load because of an issue with the plugin: _Missing: No status found with that ID.

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/35517436/3dfe97e5-054b-42e6-b001-db89e330703c)

**Browser**
Firefox 115.0.2 (64-bit)

**Links**
[Link to profile/tweet or other page where bug happens.](https://twitter.com/KoopsReturns/status/1681385817887866891)

**OldTwitter version**
1.7.3.4

**Comment by dimdenGD** [comment]
It means tweet was deleted, there's no issue

**Comment by MegaTeam89** [comment]
While there is no issue, I think you should at the very least make it so the error message says that the tweet was deleted?
