### ISSUE TITLE
User media count

### ISSUE THREAD

**Issue by serveral1** [dimdenGD/OldTwitter#274]
Is there a chance a numerical media counter display could be added? Like right next to the "Photos and Videos" section of the page. Something akin to what the main twitter UI has whenever you click on a profile's media tab.
![2023-07-20_13-52-54](https://github.com/dimdenGD/OldTwitter/assets/10162026/b34c9aae-b85f-40ae-b179-0295ca1b3f5a)
Find it really useful to have that info visually available for artist archival purposes.

**Comment by dimdenGD** [comment]
added option
