### ISSUE TITLE
Can´t access Bookmarks

### ISSUE THREAD

**Issue by celestiallele** [dimdenGD/OldTwitter#276]
**Describe the bug**
I got the issue for some days now and can not reach my bookmarks

**Screenshots**
![bookmarkserror](https://github.com/dimdenGD/OldTwitter/assets/140071564/a44935a7-e5de-4f77-8b9c-3d641c6d92f1)

**Browser**
Opera GX v. 100.0.4815.44

**Links**

**OldTwitter version**
 v1.7.3.4

**Comment by aloneunix** [comment]
I have the same issue on v1.7.3.4, but on master it works.
I think 4e4251a27c39b6e5791fb76ee29f0d8ec2c01c94 fixed it.

**Comment by dimdenGD** [comment]
yeah it got fixed already
