### ISSUE TITLE
Show suspension messages

### ISSUE THREAD

**Issue by thepwrtank18** [dimdenGD/OldTwitter#282]
Under the URL `https://twitter.com/i/api/graphql/W4Tpu1uueTGK53paUgxF0Q/HomeTimeline?variables=%7B%22count%22%3A40%2C%22cursor%22%3A%22DAABCgABF10nZ9nAJxEKAAIXXG7Sq5pwAAgAAwAAAAEAAA%22%2C%22includePromotedContent%22%3Atrue%2C%22latestControlAvailable%22%3Atrue%2C%22withCommunity%22%3Atrue%7D&features=%7B%22rweb_lists_timeline_redesign_enabled%22%3Atrue%2C%22responsive_web_graphql_exclude_directive_enabled%22%3Atrue%2C%22verified_phone_label_enabled%22%3Afalse%2C%22creator_subscriptions_tweet_preview_api_enabled%22%3Atrue%2C%22responsive_web_graphql_timeline_navigation_enabled%22%3Atrue%2C%22responsive_web_graphql_skip_user_profile_image_extensions_enabled%22%3Afalse%2C%22tweetypie_unmention_optimization_enabled%22%3Atrue%2C%22responsive_web_edit_tweet_api_enabled%22%3Atrue%2C%22graphql_is_translatable_rweb_tweet_is_translatable_enabled%22%3Atrue%2C%22view_counts_everywhere_api_enabled%22%3Atrue%2C%22longform_notetweets_consumption_enabled%22%3Atrue%2C%22responsive_web_twitter_article_tweet_consumption_enabled%22%3Afalse%2C%22tweet_awards_web_tipping_enabled%22%3Afalse%2C%22freedom_of_speech_not_reach_fetch_enabled%22%3Atrue%2C%22standardized_nudges_misinfo%22%3Atrue%2C%22tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled%22%3Atrue%2C%22longform_notetweets_rich_text_read_enabled%22%3Atrue%2C%22longform_notetweets_inline_media_enabled%22%3Atrue%2C%22responsive_web_media_download_video_enabled%22%3Afalse%2C%22responsive_web_enhance_cards_enabled%22%3Afalse%7D&fieldToggles=%7B%22withAuxiliaryUserLabels%22%3Afalse%2C%22withArticleRichContentState%22%3Afalse%7D` (that's a mouthful), it gives the following data if the account is temporarily suspended (and it's loaded from the Twitter client):

```
            "entries": [
              {
                "entryId": "messageprompt-read-only-prompt",
                "sortIndex": "1683545442056404992",
                "content": {
                  "entryType": "TimelineTimelineItem",
                  "__typename": "TimelineTimelineItem",
                  "itemContent": {
                    "itemType": "TimelineMessagePrompt",
                    "__typename": "TimelineMessagePrompt",
                    "content": {
                      "contentType": "TimelineInlinePrompt",
                      "headerText": "Your account is locked",
                      "bodyText": "After careful review, we determined your account broke the Twitter Rules. Your account is temporarily in read-only mode, which means you can’t Tweet, Retweet, or Like content. Most accounts regain full access in a week, but it could take longer.",
                      "headerRichText": {
                        "text": "Your account is locked",
                        "entities": []
                      },
                      "bodyRichText": {
                        "text": "After careful review, we determined your account broke the Twitter Rules. Your account is temporarily in read-only mode, which means you can’t Tweet, Retweet, or Like content. Most accounts regain full access in a week, but it could take longer.",
                        "entities": [
                          {
                            "fromIndex": 59,
                            "toIndex": 72,
                            "ref": {
                              "type": "TimelineUrl",
                              "url": "https://help.twitter.com/rules-and-policies/twitter-rules",
                              "urlType": "ExternalUrl"
                            }
                          }
                        ]
                      }
                    },
                    "impressionCallbacks": [
                      {
                        "endpoint": "/1.1/onboarding/fatigue.json?flow_name=read-only-prompt&fatigue_group_name=RemediationBannerFatigueGroup&action_name=impression&scribe_name=impression&display_location=home&served_time_secs=1690223486&injection_type=inline_message"
                      }
                    ]
                  },
                  "clientEventInfo": {
                    "component": "read-only-prompt",
                    "details": {
                      "timelinesDetails": {
                        "injectionType": "Message"
                      }
                    }
                  }
                }
              },
```

The new Twitter client uses this to show this message:
![image](https://github.com/dimdenGD/OldTwitter/assets/57580668/7ae7f926-eee5-4520-a515-19f67196796b)

It should be possible to make a message like this in OldTwitter, and gray out liking, retweeting, etc to prevent unnecessary API calls.

**Comment by dimdenGD** [comment]
OldTwitter doesn't use `/W4Tpu1uueTGK53paUgxF0Q/HomeTimeline` endpoint
