### ISSUE TITLE
Remove every trace of "X"

### ISSUE THREAD

**Issue by Dacatzgoescodin5267** [dimdenGD/OldTwitter#283]
Since dumbass elon musk replaces twitter with X i want to have all the stupid "X" shit off with this extention

**Comment by homolol** [comment]
example: favicon

**Comment by Dacatzgoescodin5267** [comment]
> example: favicon

Do somethinng useful instead of being an dumbass elon musk ass kisser

**Comment by dimdenGD** [comment]
There's already no traces of X anywhere in extension

**Comment by radixliner** [comment]
I already clear some cache on Firefox but it's still there, except Chromium
![image](https://github.com/dimdenGD/OldTwitter/assets/44131738/89fefda3-36e9-49cc-afa7-ed69b5f7a365)

**Comment by jonm58** [comment]
please block https://abs.twimg.com/favicons/twitter.3.ico
![屏幕截图 2023-07-25 125730](https://github.com/dimdenGD/OldTwitter/assets/73036321/2544f8f2-4246-4254-adcb-6817bb242f2a)

**Comment by radixliner** [comment]
> please block https://abs.twimg.com/favicons/twitter.3.ico ![屏幕截图 2023-07-25 125730](https://user-images.githubusercontent.com/73036321/255793487-2544f8f2-4246-4254-adcb-6817bb242f2a.png)

Thanks. but sometimes is not show up and I don't even know how I can save those Request Blocking on Inspector, so I use uBlock instead

**Comment by ericpa06** [comment]
Since there is already a thread about favicon, could there an option keeping the 2015-2023 twitter favicon? 

![th-1682551640](https://github.com/dimdenGD/OldTwitter/assets/6937720/cf98592d-58a4-4b3f-ab89-ccb5681ae83f)

 I'm not a fan of this really old twitter favicon the extension use. Also, thank you very for your project!

**Comment by dimdenGD** [comment]
> Since there is already a thread about the favicon, could there be an option that enables to us to use the 2015-2023 twitter favicon?
> 
> ![th-1682551640](https://user-images.githubusercontent.com/6937720/255825154-cf98592d-58a4-4b3f-ab89-ccb5681ae83f.jpg)
> 
> I'm not a fan of this really old twitter favicon the extension currently uses. Also, thank you very for your project!

There's already such option in settings

**Comment by ericpa06** [comment]
Oh, I found the option, thank you very much. For anyone that might be reading, it's the "Use new logo as tab icon". Thank you very much!
