### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'core')

### ISSUE THREAD

**Issue by araghon007** [dimdenGD/OldTwitter#288]
**Describe the bug**
The bellow thread doesn't load with the error "TypeError: Cannot read properties of undefined (reading 'core')"

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/10870921/1563d61f-68df-4dcb-9f30-d7b7a889e3b9)
![image](https://github.com/dimdenGD/OldTwitter/assets/10870921/4da0ca4d-96c6-4c59-8df5-8202836af63d)
Might be caused by this(?)
![image](https://github.com/dimdenGD/OldTwitter/assets/10870921/02f73116-3290-406a-bd01-4a0ee1ba9cb4)

**Browser**
Include your browsers name and it's version.

**Links**
https://twitter.com/rahaeli/status/1593819064161665024
Works from this point on: 
https://twitter.com/rahaeli/status/1593879218542489600

**OldTwitter version**
v1.7.3.4

**Comment by dimdenGD** [comment]
Was fixed in beta already
