### ISSUE TITLE
Timeout: Unspecified at 1598768346635603968 (OldTwitter v1.6.5.5) 7 Dec, 2022

### ISSUE THREAD

**Issue by bencov** [dimdenGD/OldTwitter#29]
**Describe the bug**
Was looking at a twitter profile (@ludwigahgren) and error message came up. i see no errors

Timeout: Unspecified at 1598768346635603968 (OldTwitter v1.6.5.5)

**Browser**
Microsoft Edge
Version 107.0.1418.62 (Official build) (64-bit)
(gross, i know)

**Comment by dimdenGD** [comment]
Does it keeps happening after refresh?
