### ISSUE TITLE
Antialiasing for image previews

### ISSUE THREAD

**Issue by WannaBeDev64** [dimdenGD/OldTwitter#291]
previewed images that are high res are very crunchy. Antialiasing is only applied when you click on the image to expand it, or if the image has been quote retweeted.
this happens when the tweet appears on the timeline or when you're on its page. 

preview: 
![vivaldi_LmJBsnAwyR](https://github.com/dimdenGD/OldTwitter/assets/62036967/d37c509a-95e1-4ffa-acc7-cd58e610e460)
expanded:
![vivaldi_MAJQu09l33](https://github.com/dimdenGD/OldTwitter/assets/62036967/7a5c0571-01db-4f4c-bc3f-054265f352b4)
Link to tweet: https://vxtwitter.com/kiku1569/status/1683945082993647616

If it matters, my display is 1080p.

**Comment by dimdenGD** [comment]
There's nothing really to be done about it, but you can disable "Always show original quality images" option in settings and they should be less crispy
