### ISSUE TITLE
"X" logo appears briefly on refresh

### ISSUE THREAD

**Issue by WannaBeDev64** [dimdenGD/OldTwitter#297]
**Describe the bug**
When reloading a page, the mark of the beast (the "X" logo) appears for a short amount of time. 

**Screenshots**
https://github.com/dimdenGD/OldTwitter/assets/62036967/b1e8451b-fca3-40dc-81ec-9b95fd335352

**Browser**
Vivaldi 5.7.2921.63 (Stable channel) (64-bit) 

**Links**
N/A

**OldTwitter version**
v1.7.3.4

**Comment by dimdenGD** [comment]
This was fixed in beta already
