### ISSUE TITLE
X logo jumpscare

### ISSUE THREAD

**Issue by yezenhawari** [dimdenGD/OldTwitter#298]
**The problem**
The X logo shows up for a split second in the Twitter tab before displaying the Twitter logo

![image](https://github.com/dimdenGD/OldTwitter/assets/135471943/384401a9-32e4-4f7f-b03f-81744d634747)

**Browser**
Using Microsoft Edge

**Steps to recreate**
1. Click on the Twitter home button
2. The X logo appears briefly in the Chrome tab

**OldTwitter version**
v1.7.3.4 & v1.7.4

**Comment by yezenhawari** [comment]
Duplicate of #297 (1-minute difference lol)

**Comment by dimdenGD** [comment]
Should be fixed now
