### ISSUE TITLE
Lists not showing up

### ISSUE THREAD

**Issue by DraXer** [dimdenGD/OldTwitter#301]
List are not showing up when I visit the lists page

![image](https://github.com/dimdenGD/OldTwitter/assets/33878612/11adfac7-ffdb-4926-adf9-bb75cb5fc52a)

**Comment by dimdenGD** [comment]
Press F12 and go to Console and show errors

**Comment by DraXer** [comment]
![image](https://github.com/dimdenGD/OldTwitter/assets/33878612/ed0fb29f-08c9-4026-a0e4-84b2f46de42c)
