### ISSUE TITLE
The bookmarks page does not load ⚠️

### ISSUE THREAD

**Issue by Om-Thorat** [dimdenGD/OldTwitter#302]
**Describe the bug**
The bookmarks page does not load, It's just stuck on a white screen with larry.
![image](https://github.com/dimdenGD/OldTwitter/assets/76207818/d2095c89-ff2c-4a87-a5f1-414891be4f1b)

**Browser**
Firefox Version 115.0.2 (64-bit)

**Links**
https://twitter.com/i/bookmarks

**OldTwitter version**
v1.7.3.4 

**Console error**
![image](https://github.com/dimdenGD/OldTwitter/assets/76207818/6125538a-ddb7-4f2b-896b-98920f16492b)
![image](https://github.com/dimdenGD/OldTwitter/assets/76207818/d1080e3a-b5fc-45c3-a924-0497dbcd08a6)

**Comment by dimdenGD** [comment]
Was fixed in beta

**Comment by Om-Thorat** [comment]
Oops! my bad, Thanks
