### ISSUE TITLE
Algo V2 can't load

### ISSUE THREAD

**Issue by Arcadius2006** [dimdenGD/OldTwitter#303]
**Describe the bug**
Switching the timeline mode to Algo V2 doesn't make any tweets load

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/93880348/bf0cc330-e74f-4e4d-ba8b-34a4fbf67a09)

**Browser**
Google Chrome Version 115.0.5790.110

**Links**
[You'll never guess where](https://twitter.com/home)

**OldTwitter version**
1.7.4 (Newest Master)

**Comment by Arcadius2006** [comment]
nvm had to reload extension

**Comment by dimdenGD** [comment]
open console and show errors

**Comment by Arcadius2006** [comment]
i can't now, i reloaded everything (and that fixed it for some reason)
