### ISSUE TITLE
Feature request:  Temporarily stop auto-refresh when write-Tweet box is open

### ISSUE THREAD

**Issue by JaxxArmstrong** [dimdenGD/OldTwitter#311]
I haven't looked at it and it might be hard to detect, but the auto-refresh interferes when you're trying to write a Tweet as it auto-refreshes like it supposed to and thus removing the write-Tweet box that's on-top and effectively removes all text you put into the box.

**Comment by dimdenGD** [comment]
Auto-refresh of what? Timeline autorefresh already doesn't reload timeline when you're writing something, and theres no autorefresh settings that would clear main tweet composer on top of home page

**Comment by JaxxArmstrong** [comment]
Interesting because that's what's happening on my side of things. I'll triple-check it with a clean Firefox profile in a bit. Thank you for the quick response.

**Comment by JaxxArmstrong** [comment]
With a clean firefox profile and with only your addon running it still auto-refreshes, but the write-Tweet box does NOT disappear.

I'm going to go through and check for the offending addon on my side.

I apologize for wasting your time. Thank you again for a great addon.
