### ISSUE TITLE
Show Controls on GIFs

### ISSUE THREAD

**Issue by bekorn** [dimdenGD/OldTwitter#315]
Many artists I follow use the GIF format to bypass video compression and I would like to see those GIFs larger. I can fullscreen videos, and images are zoomable thanks to the custom viewer, but GIFs are missing such an option. My initial thought was to enable the custom viewer for the GIFs as well, but that would be a confusing UX I guess. So what about making the controls enabled by default? I'm talking about this option (which is disabled unless there is a `controls` attribute on the `<video>`):
![image](https://github.com/dimdenGD/OldTwitter/assets/5175163/0688a24f-6c38-4779-9a98-98b49b6c89ae)

This enables controls similar to video and most importantly double click to fullscreen.

**Comment by dimdenGD** [comment]
I don't think this will be added, it'll make GIFs to be confused with normal videos and as you show on screenshot you already can enable controls when you need them with context menu (which I don't think lot of people use). Also beta version has ability to pause gifs by pressing on them which makes this even more pointless apart from fullscreen mode
