### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by derreka** [dimdenGD/OldTwitter#317]
Hi! I added and translated the missing strings for the Spanish translation. Please contact me on twitter (@elderreka) if I missed or fucked up something

[messages.txt](https://github.com/dimdenGD/OldTwitter/files/12207622/messages.txt) (Uploaded as .txt so github accepts it lol)

Oh, and cool app btw, you're doing god's work here ^^

Edit: minor translation fix

**Comment by dimdenGD** [comment]
Thank you
