### ISSUE TITLE
X logo jumpscare

### ISSUE THREAD

**Issue by thepwrtank18** [dimdenGD/OldTwitter#318]
**Describe the bug**
When you open up Twitter, you get jumpscared by the X logo before it returns back to OldTwitter.

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/57580668/b56017f4-01f8-460c-9bad-190ce2ccfd8a)

**Browser**
Firefox Developer Edition 116.0b8 (64-bit)

**Links**
All across Twitter.

**OldTwitter version**
v1.7.3.4

**Comment by dimdenGD** [comment]
Was fixed in beta

**Comment by TorutheRedFox** [comment]
lmao

**Comment by thepwrtank18** [comment]
it's scary alright, you're browsing twitter and the page reloads and you see this stupid ass "X" like I'm surprised i'm not having a heart attack
(/s)
