### ISSUE TITLE
Some people's tweets won't load

### ISSUE THREAD

**Issue by TorutheRedFox** [dimdenGD/OldTwitter#327]
```TypeError: Cannot read properties of undefined (reading ’text’) at appendTweet (chrome-extension://hpomahomknnoaomlabdidempkajlkige/scripts/helpers.js:2186:67) at async renderTimeline (chrome-extension://hpomahomknnoaomlabdidempkajlkige/layouts/profile/script.js:1465:17) at 1685143106776424450 (OldTwitter v1.7.4)```

**Comment by dimdenGD** [comment]
I cant reproduce, your bug report also lacks page where this happens

**Comment by TorutheRedFox** [comment]
[this tweet](https://twitter.com/TiffanyFong_/status/1685143106776424450)

**Comment by dimdenGD** [comment]
![image](https://github.com/dimdenGD/OldTwitter/assets/26517362/2bcf3530-6778-4964-a0e0-891ca70474f4)
Works fine for me

**Comment by TorutheRedFox** [comment]
well that's weird

maybe it's linked to me being a community notes contributor?

**Comment by dimdenGD** [comment]
![image](https://github.com/dimdenGD/OldTwitter/assets/26517362/f4d9df6a-ab95-47cb-9c81-ac647a42de4e)
Oh yeah error points to Community notes code

**Comment by dimdenGD** [comment]
I made it not show unapproved community notes now

**Comment by TorutheRedFox** [comment]
that fixed it
