### ISSUE TITLE
Mobile support?

### ISSUE THREAD

**Issue by kyoyacchi** [dimdenGD/OldTwitter#328]
Hi. I am using this extension in Kiwi Browser (116.0.5845.54) but it just shows desktop ui, even tho im on mobile.
Is there any option needs to be enabled? Am I doing something wrong?
![Screenshot_20230730-125544](https://github.com/dimdenGD/OldTwitter/assets/63583961/7589e702-f2b3-4109-9b90-8f1fc35cc61f)

**Comment by dimdenGD** [comment]
you're probably not using beta version and got it from chrome web store, this wasn't released there yet

**Comment by kyoyacchi** [comment]
I see now, thanks. I'll use beta one then
