### ISSUE TITLE
"Reverse chronological with friends likes" timeline cant load more tweets on timeline

### ISSUE THREAD

**Issue by danielah05** [dimdenGD/OldTwitter#333]
**Describe the bug**
when scrolling down on my timeline, a "load more" button appears, clicking on it does nothing while on any other timeline setting it automatically loads more tweets

**Screenshots**
https://github.com/dimdenGD/OldTwitter/assets/35849198/795a2262-2680-4560-8e59-f138e28c86da

**Browser**
Waterfox G5.1.9 (Firefox)

**OldTwitter version**
1.7.4

**Comment by dimdenGD** [comment]
Waterfox is known to have lot of weird issues with extension and I currently don't offer support for it

**Comment by danielah05** [comment]
i just tested this in regular firefox and it still does not work, this is not just an issue with waterfox

**Comment by danielah05** [comment]
it DOES seem to work in a chromium based browser tho

**Comment by dimdenGD** [comment]
I just tested and yeah this does happen to me too after scrolling for some time, on both Firefox and Chromium. I looked into log and it seems that Twitter just stops returning tweets at some point for some reason, usually it was 800 tweets as stated in their API documentations but now it seems to be only ~200? I guess I need to add option to use new version of API endpoint that has rate limits but endless

**Comment by dimdenGD** [comment]
Switched to V2.
