### ISSUE TITLE
twitter.com/#!/ older format profile URLs don't load profile

### ISSUE THREAD

**Issue by squabbled** [dimdenGD/OldTwitter#334]
**Describe the bug**
Minor bug - Older Twitter profile URLs that are formatted twitter.com/#!/test don't load profile and load the home timeline instead. Without OldTwitter going to twitter.com/#!/test loads twitter.com/test.
Example: https://twitter.com/#!/dimdenEFF should load https://twitter.com/dimdenEFF

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/40838711/5f122cfe-832b-4a86-b400-c2e81d4279e0)
![image](https://github.com/dimdenGD/OldTwitter/assets/40838711/d6712b6f-07b3-4d99-97bd-bf589b3b88b0)

**Browser**
Mozilla Firefox 115.0.3 (Windows 10)
Google Chrome 115.0.5790.110 (W10)

**Links**
https://twitter.com/#!/dimdenEFF should redirect to https://twitter.com/dimdenEFF

**OldTwitter version**
v1.7.3.4

**Comment by dimdenGD** [comment]
I've never seen this used anywhere, where did you find such link?

**Comment by squabbled** [comment]
![image](https://github.com/dimdenGD/OldTwitter/assets/40838711/680aaaaa-f78c-4b70-951a-ccaeee9ce69e)
![image](https://github.com/dimdenGD/OldTwitter/assets/40838711/97ba28c5-6c8a-4b21-a915-fd5c8ab70dd3)

I think around 2009-2012 this was the link format used when copying a profile link from Twitter because I've seen some old videos on YouTube that have links like this

**Comment by dimdenGD** [comment]
added
