### ISSUE TITLE
Error occurs when adding bookmark

### ISSUE THREAD

**Issue by thepwrtank18** [dimdenGD/OldTwitter#335]
**Describe the bug**
When adding a bookmark, you get the screenshot below. It still adds the bookmark, though.

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/57580668/20e898fb-9407-42cd-b1c8-16862e32c1e7)

**Browser**
Firefox Developer Edition 116.0b8 (64-bit)

**Links**
Any tweet.

**OldTwitter version**
v1.7.4.1

**Comment by dimdenGD** [comment]
Fixed
