### ISSUE TITLE
Some tweets couldn't be loaded due to errors.

### ISSUE THREAD

**Issue by FemboyJd** [dimdenGD/OldTwitter#336]
**Describe the bug**
When I go to my profile it shows this error "appendTweet/<@moz-extension://ece4b283-f09d-4542-90f9-ee0a47171a90/scripts/helpers.js:1649:20 appendTweet@moz-extension://ece4b283-f09d-4542-90f9-ee0a47171a90/scripts/helpers.js:1648:52 at 1685215917486329856 (OldTwitter v1.7.4)" 

**Screenshot**
![image](https://github.com/dimdenGD/OldTwitter/assets/116119001/485f52aa-4eb3-4521-b2bc-62c78969dbb8)

**Browser**
LibreWolf Version 115.0.2-2 

**Links**
https://twitter.com/BasedAndTrueFR

**OldTwitter version**
 1.7.4

**Comment by dimdenGD** [comment]
Update to 1.7.4.2 (its already available) and check if it fixes this

**Comment by FemboyJd** [comment]
It's fixed now 

Thank You!
