### ISSUE TITLE
viewing tweets on your own profile is broken

### ISSUE THREAD

**Issue by dagggy** [dimdenGD/OldTwitter#344]
**Describe the bug**
Upon trying to view my profile, I cannot view my own tweets with `TypeError: pinEntry.entry.content.itemContent is undefined` displayed instead. Only one of my accounts seem to be affected. Photos and videos/media appears to be unaffected.

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/43415554/50214e3b-726f-49ea-b3f0-58997045c0e4)
![image](https://github.com/dimdenGD/OldTwitter/assets/43415554/67a0980a-c41a-4170-8173-56d4c5c82945)

**Browser**
Firefox 115.0.3

**Links**
[Affected account.](https://twitter.com/hereanddag)

**OldTwitter version**
 v1.7.4.2

**Comment by dagggy** [comment]
oddly enough it happens on only one of my accounts

**Comment by dimdenGD** [comment]
Follow bug report template, why did you clear it
Your bug report lacks version and links

**Comment by dagggy** [comment]
i hit enter on accident and it sent, panicked a little and just made a rudimentary log, give me a minute
