### ISSUE TITLE
Nothing appearing under New Tweet Notification URL

### ISSUE THREAD

**Issue by nypocalypse** [dimdenGD/OldTwitter#346]
**Describe the bug**
When going to notifications, then clicking "new tweet notifications", nothing loads except a footer looking piece.

**Screenshots**
[Image one: Notifications screen (took out all irrelevant information)](https://nypocalypse.com/misc/notweets2.png)
[Image two: New tweet notifications screen with nothing loaded](https://nypocalypse.com/misc/notweets.png)

**Browser**
Google Chrome 115.0.5790.110
(Have tested with both ublock origin enabled and disabled to make sure that wasn't the problem already)

**Links**
[New notifications URL](https://twitter.com/i/timeline?page=device_follow&nid=AAAAAE5mTfwAAAAB7cYUwKtfDUWXms5dAAA)

**OldTwitter version**
Running [OldTwitter](https://github.com/dimdenGD/OldTwitter) v1.7.4.2 (last version: 1.7.4.3).

**Accounts affected**
Any account I can log in to.

**Comment by dimdenGD** [comment]
Was fixed in 1.7.4.3, please wait until released
