### ISSUE TITLE
Tweet notifications from other users not working

### ISSUE THREAD

**Issue by LunaXCBN** [dimdenGD/OldTwitter#347]
**Describe the bug**
When opening the tab for tweets from other users, the tab returns nothing.

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/87461596/0237f226-2917-45a3-9915-980a03636122)

**Browser**
Brave Browser v1.56.14

**Links**
Dunno what to put here, it's literally just this
![image](https://github.com/dimdenGD/OldTwitter/assets/87461596/56831782-fc15-4d53-94ce-f52eee9bf4e2)

**OldTwitter version**
v1.7.4.2

**Comment by dimdenGD** [comment]
Was fixed in 1.7.4.3
