### ISSUE TITLE
Images disappear & fail to load when clicked + image viewer not working

### ISSUE THREAD

**Issue by parkupine** [dimdenGD/OldTwitter#350]
**Describe the bug**
After the new update, whenever I try to click on an image it removes the thumbnail and does not load the image in the image viewer - this happens with every image that I try to click on

**Screenshots**
![vivaldi_Q67Bal3Zqj](https://github.com/dimdenGD/OldTwitter/assets/28219898/f869dd5a-c998-45d7-89ac-560b9cad25a3)
![vivaldi_5QPoWdFza1](https://github.com/dimdenGD/OldTwitter/assets/28219898/d7d90816-05f6-4ead-b504-6c324beb5dde)

**Browser**
**Vivaldi Browser** 6.1.3035.204 (Stable channel) (64-bit) 

**Links**
https://twitter.com/noriuma_/status/1685987897810575360 _(just an example)_

**OldTwitter version**
v1.7.4.2

(thank you btw i love your extension!!)

**Comment by dimdenGD** [comment]
Open console with F12 and go to Console tab and then click on image and show screenshot of console

**Comment by parkupine** [comment]
>![image](https://github.com/dimdenGD/OldTwitter/assets/28219898/9b85073f-38f1-4356-bae1-f94106548b98)

**Comment by dimdenGD** [comment]
Do you have any extensions or userscripts for Twitter? Looks like something tries to make image use original quality on top of OldTwitter doing it

**Comment by parkupine** [comment]
I just removed [Twitter Media Downloader](https://chrome.google.com/webstore/detail/twitter-media-downloader/cblpjenafgeohmnjknfhpdbdljfkndig) from my extensions and it seemed to have fixed the issue! I tried disabling the extension first before submitting a bug but it turns out that wasn't enough. Thank you for the help!! :)
