### ISSUE TITLE
Link Color Synching Error

### ISSUE THREAD

**Issue by NoelleCoolGirl** [dimdenGD/OldTwitter#353]
When attempting to apply a new user profile color, the process fails and results in these errors;

![color error](https://github.com/dimdenGD/OldTwitter/assets/139192699/12b0c736-74d5-4f1d-8fc8-98da9c496439)

I gave it a few hours between attempts, but it kept reoccurring regardless. I hope this helps! :)

[ I am using Firefox 115.0.3 - OldTwitter Version 1.7.4.3 ]

**Comment by dimdenGD** [comment]
Does this still happen to you?

**Comment by NoelleCoolGirl** [comment]
I just checked, i still get this error! Tried logging out and back in, but still no dice. 

If there's any troubleshooting steps that can help narrow down the problem, let me know and I'll try them! As for now, I'm going to meticulously go through my OldTwitter settings and see if any of them being on/off affects anything. I'll update this once I'm done.

**Comment by clover-yan** [comment]
I met the same error. Here's the error message in console:
![image](https://github.com/dimdenGD/OldTwitter/assets/56215525/400d159f-0c57-4eba-adca-3a83c1de0965)
> `(匿名)` === `(Anonymous)`

**Comment by dimdenGD** [comment]
@clover-yan what OldTwitter version do you use

**Comment by clover-yan** [comment]
> @clover-yan* what OldTwitter version do you use

@dimdenGD Ver. 1.7.3 from Edge Add-on store.

**Comment by dimdenGD** [comment]
That's very old and broken, install from Chrome Web Store

**Comment by NoelleCoolGirl** [comment]
The problem has seemed to resolve itself for me, though

**Comment by NoelleCoolGirl** [comment]
I did not mean to close this thread, I miss-clicked when posting. I'm going to re-open it, just in case clover is still having this issue.

**Comment by NoelleCoolGirl** [comment]
I did not mean to close this thread, I miss-clicked when posting. I'm going to re-open it, just in case clover is still having this issue.

**Comment by clover-yan** [comment]
I tried to install from Chrome Web Store and it's solved. You can close this now. @NoelleCoolGirl
