### ISSUE TITLE
Twitter Circle's Owner shows wrong

### ISSUE THREAD

**Issue by Wintiger0222** [dimdenGD/OldTwitter#357]
**Describe the bug**
Notifications misrepresent the owner of someone else's Twitter circle as myself.

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/24960466/9eeeb95c-8021-45ff-9ef8-83cebdb7e554)

**Browser**
Chrome 115.0.5790.110

**Links**
At notification Page

**OldTwitter version**
1.7.4.2 (Beta from github)

**Comment by njhuar** [comment]
appendTweet@moz-extension://96220de5-85f2-47e4-a426-4a9920f51043/scripts/helpers.js:2302:54 at 1687472908497768448 (OldTwitter v1.7.5)
