### ISSUE TITLE
Can't like a reply to a tweet when it's an image

### ISSUE THREAD

**Issue by penguinsarena** [dimdenGD/OldTwitter#36]
Whenever I try to like a reply to a tweet, and the reply has an image attatched, I can't click the like button. The only way for me to like the reply is to expand it, and then like it afterward. 
This is annoying.

I should be able to like any replies to a tweet without having to expand them.

I use chrome, and usually have twitter zoomed in at 125%. I'm hoping to see this fixed soon bc it's really getting on my nerves.

**Comment by dimdenGD** [comment]
What prevents you from liking it? Is button disabled or blocked by some element? Can you send screenshot or video of issue? I have no problems with liking any tweets.
