### ISSUE TITLE
Media Count in Profiles

### ISSUE THREAD

**Issue by ruben1PvP** [dimdenGD/OldTwitter#362]
If you check a profile in twitter with this extension, you have a count of the tweets, following accounts, accounts following, and likes that account has. However, it doesn't have a count for Media. If you go to "Photos and Videos", you indeed can see media uploaded by that account but you can't see how many there are, contrary to the new twitter when you have "X Photos & Videos" at the top of the screen below the name of the account. Can that be recreated in this extension as well?

**Comment by dimdenGD** [comment]
There's already an option in settings to show Media
