### ISSUE TITLE
Rate Limit Exceeded

### ISSUE THREAD

**Issue by Jneil4102** [dimdenGD/OldTwitter#363]
When I go to view my profile or other user profiles it tells me my rate limit is exceeded. I've taken a few hours between trying again but it is still happening.

![Screenshot (88)](https://github.com/dimdenGD/OldTwitter/assets/141190640/c28f70d1-4472-4f6f-967f-99ae561e0136)

I am using the Chrome Extention of OldTwitter (v1.7.4.3)

**Comment by dimdenGD** [comment]
Impossible to fix
