### ISSUE TITLE
Some notifications couldn't be loaded due to errors.

### ISSUE THREAD

**Issue by homosexuayla** [dimdenGD/OldTwitter#368]
the extension gave me this error and said to send it here
`ReferenceError: notificationDiv is not defined at renderNotification (chrome-extension://ojicfkfbknneblggkkkdjjkenahkmgni/scripts/helpers.js:3377:31) at updateNotifications (chrome-extension://ojicfkfbknneblggkkkdjjkenahkmgni/layouts/notifications/script.js:114:26) at async chrome-extension://ojicfkfbknneblggkkkdjjkenahkmgni/layouts/notifications/script.js:232:5 (OldTwitter v1.7.4.4)`

i'm on the latest commit

**Comment by dimdenGD** [comment]
Fixed
