### ISSUE TITLE
Birth date field has white CSS overlay making it unreadable in the profile

### ISSUE THREAD

**Issue by Srlimao** [dimdenGD/OldTwitter#369]
The birth date field in the profile has a white CSS overlay on top, making it unreadable.
Dark and Light mode seems to be inverted

![image](https://github.com/dimdenGD/OldTwitter/assets/10340512/02dc76c2-7ea3-4c26-be34-5c11dbc96221) ![image](https://github.com/dimdenGD/OldTwitter/assets/10340512/3cb4ba15-1704-4931-a173-22030ad42a21)

Chrome 115.0.5790.110

At profile

OldTwitter v1.7.4.3

**Comment by dimdenGD** [comment]
Just hover on it to uncover it lol

**Comment by Srlimao** [comment]
oh it was intended that way? 😂
