### ISSUE TITLE
the thing said to me to copy something and send here

### ISSUE THREAD

**Issue by Lucasft10** [dimdenGD/OldTwitter#37]
TypeError: Cannot read properties of undefined (reading ’split’) at appendTweet (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/scripts/helpers.js:1119:435) at renderTimeline (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/layouts/profile/script.js:930:63) at updateTimeline (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/layouts/profile/script.js:322:5) at 1594826948026707968 (OldTwitter v1.6.6.0)

**Comment by dimdenGD** [comment]
Thank you for submitting, this was fixed but it can take a few days until the update is released for users.
