### ISSUE TITLE
View Translation Button out of bounds 

### ISSUE THREAD

**Issue by Rokotallion** [dimdenGD/OldTwitter#370]
**Describe the bug**
The "View Translation" button is out of the tweet boundaries. This only occurs on the first tweet and only before the "Show new tweets" shows up.

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/79259221/da22e25c-0cfe-4923-8852-158e19e6bb19)

**Browser**
Firefox 116.0
Kiwi Android

**Links**
Only on homepage timeline

**OldTwitter version**
v1.7.4.3

**Comment by dimdenGD** [comment]
Fixed
