### ISSUE TITLE
Fix Request for Japanese Translation

### ISSUE THREAD

**Issue by kamokakesu** [dimdenGD/OldTwitter#377]
Hello, I'm Japanese that feeling so much grad to discovering and using such a great Chrome extensions.

I make a fixed version of Japanese translation of OldTwitter. Feel free to apply this.

[messages-translate-japanese-0803.zip](https://github.com/dimdenGD/OldTwitter/files/12250793/messages-translate-japanese-0803.zip)

May the peace, happiness and Force be with you :)

**Comment by kamokakesu** [comment]
Sorry for my mistake! X(
Fixed it follows order of English file, and added more translation as I can.
If you still find some bugs, please reply.

[messages_ja_0804_fixed1.zip](https://github.com/dimdenGD/OldTwitter/files/12254325/messages_ja_0804_fixed1.zip)

**Comment by dimdenGD** [comment]
Thank you, added. What is your Twitter profile so I can credit you

**Comment by kamokakesu** [comment]
Thank you for commit.

My twitter ID is same as screen name of GitHub,
but I prefer not to be credited my name in extension and want to just contribute for your works.
So it would be nice to credited only in GitHub page, not in extension, if it's possible.

Very thankful for your kindness :)
