### ISSUE TITLE
Disable Navbar Customization for Custom Profile CSS

### ISSUE THREAD

**Issue by Rokotallion** [dimdenGD/OldTwitter#378]
navbar with local custom css:
![image](https://github.com/dimdenGD/OldTwitter/assets/79259221/e52c032a-15f3-4b13-9804-be61860bdb42)

navbar during custom profile css:
![image](https://github.com/dimdenGD/OldTwitter/assets/79259221/a82a59cc-1870-4831-99ae-0b24cfc307a6)

I kinda wish navbars with custom local css wouldnt be affected in profiles with custom css attached. I know it overrides the local CSS, but I wished there was an option to not let the navbar get affected by it, without having to resort to disabling profile customizations.

**Comment by dimdenGD** [comment]
It's just too much work to make this, local css isn't loaded at all when theres custom css because it'll just mix and probably break page, and I can't know what of css is related to navbar and what isn't without parsing it (which is again too much work)

**Comment by Rokotallion** [comment]
dang, that makes sense tho
