### ISSUE TITLE
Search no longer works

### ISSUE THREAD

**Issue by thepwrtank18** [dimdenGD/OldTwitter#379]
**Describe the bug**
Searching anything displays "Dependency: Unspecified" instead.

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/57580668/94e168ef-2d67-4626-bd90-608fd7252a25)

**Browser**
Firefox Developer Edition 117.0b2 (64-bit)

**OldTwitter version**
v1.7.4.4 (v1.7.4.5 needs to be published on Mozilla)

**Comment by dimdenGD** [comment]
api issue
