### ISSUE TITLE
Cannot read properties

### ISSUE THREAD

**Issue by underdog69** [dimdenGD/OldTwitter#38]
TypeError: Cannot read properties of undefined (reading ’split’) at appendTweet (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/scripts/helpers.js:1119:435) at async renderTimeline (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/layouts/profile/script.js:930:57) at 1583866749715644416 (OldTwitter v1.6.6.0)

**Comment by dimdenGD** [comment]
Duplicate of https://github.com/dimdenGD/OldTwitter/issues/37
