### ISSUE TITLE
Support for Blue Blocker

### ISSUE THREAD

**Issue by darkpixlz** [dimdenGD/OldTwitter#381]
I use Blue Blocker to get rid of Bluechecks and people who pay for twitter, I think that this plugin should add support for Blue Blocker.

I also think that it should send bluechecks who you dont follow to the very bottom, or the "show more" section optionally because 9 times out of 10 their replies are just "🤣🤣🤣🎯🎯" or a shitty take to farm interaction to get paid

**Comment by dimdenGD** [comment]
Duplicate of https://github.com/dimdenGD/OldTwitter/issues/88
