### ISSUE TITLE
Tweets not tweeting

### ISSUE THREAD

**Issue by Fizzvipop** [dimdenGD/OldTwitter#382]
So I click "Tweet", type whatever into the box, click "Tweet" to post, all seems fine but then the tweet doesnt show up, even after refreshing the page it still wont show up. Uppon further investigation, I found it seems to only happen on the actual Twitter app, like if I try it on Chrome or Firefox it works fine but when I try it on the app then it doesnt work.

**Browser**
MS Edge/App

**OldTwitter version**
1.7.4.5

**Comment by dimdenGD** [comment]
Official Twitter app? How is that related to extension

**Comment by Fizzvipop** [comment]
Theres a bug that exists when I use the extention with it, as I explained above, it wont let me tweet
