### ISSUE TITLE
Quote tweets are cut off by the quoted tweet

### ISSUE THREAD

**Issue by thepwrtank18** [dimdenGD/OldTwitter#385]
**Describe the bug**
Some Quote Tweets show part of the quote, the tweet it's quoting, then part of the quoted tweet becomes the quote tweet.

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/57580668/b4938d0e-a081-426a-be06-329d26fc79f6)

**Browser**
Include your browsers name and it's version.

**Links**
https://twitter.com/lefunny87104/status/1687190515526017024

**OldTwitter version**
v1.7.4.6

**Comment by dimdenGD** [comment]
Already fixed in beta
