### ISSUE TITLE
Keep video playing when you're watching it and decides to scroll down thorugh twitter timeline?

### ISSUE THREAD

**Issue by ericpa06** [dimdenGD/OldTwitter#386]
Not sure if this is a bug or a feature request, or if I'm doing something wrong, but anyway, it would be nice that when you click on a video and scroll down, the video doesn't stop playing (sometimes you just want to hear the video).

**Comment by iiv3** [comment]
There was a bug that caused this behavior.

I do want the videos to auto-pause when scrolling away, so this enhancement should be optional.

**Comment by dimdenGD** [comment]
Added option
