### ISSUE TITLE
Issue sending images via DM

### ISSUE THREAD

**Issue by PaoM1999** [dimdenGD/OldTwitter#387]
When attempting to attach images on my computer to send via DM, the image loads in, and it allows me to click send. Once I have clicked the send button, nothing happens, and it does not allow me to hit the send button again.

https://github.com/dimdenGD/OldTwitter/assets/141466510/214d8f4a-7803-4a19-a649-5745c8fc5bb4

**Comment by dimdenGD** [comment]
This was fixed on latest already, also follow bug template instead of clearing it next time
