### ISSUE TITLE
reverse chronological with friends likes doesn't seem to work on latest commit

### ISSUE THREAD

**Issue by homosexuayla** [dimdenGD/OldTwitter#391]
all the others ones work fine but this one just tries to load for a few seconds and then shows nothing

previous commit works just fine

**Comment by dimdenGD** [comment]
any errors in console? F12

**Comment by homosexuayla** [comment]
there are

![image](https://github.com/dimdenGD/OldTwitter/assets/76013118/533c1d51-42e2-487a-885e-79f08f7259f2)
