### ISSUE TITLE
mobile version improvements

### ISSUE THREAD

**Issue by homosexuayla** [dimdenGD/OldTwitter#392]
1. ok so, neither kiwi browser and specially not firefox have a good color picker. kiwi's doesn't let you choose a specific hex/rgb/whatever and firefox's doesn't really exist, it's just like 10 predefined colors. so i think it would be nice if there was a custom color picker or at least an input box to put a hex code in there.
2. maybe add a no modal mode? they're really good on a computer but they're not that good on mobile, so i think adding an option without them would be cool, specially with that experimental page-preserving navigation option. and it makes it more like the twitter mobile app (ik i can just click on the "45m ago" and it takes me to a full page but that's tiny :( )
that's it!!

**Comment by dimdenGD** [comment]
What's wrong with modals, they are taking 100% of width so there's basically no different from full page, you can press back button to close them too

**Comment by homosexuayla** [comment]
ik it's kinda dumb but i like to see the little bar

**Comment by dimdenGD** [comment]
Updated color picker to be good on mobile too
