### ISSUE TITLE
The limited_tweet field is not being properly translated.

### ISSUE THREAD

**Issue by lrisora** [dimdenGD/OldTwitter#394]
**Describe the bug**
I've noticed that the `limited_tweet` field is not being translated on the home page tweets and remains in English. However, it appears that there's a translation available in the tweet modal window, but with a hardcoded English period. Perhaps the period should be moved to the `LOC.limited_tweet` field to allow for proper translation.

**Browser**
Firefox 110.0.1 & chrome 115

**Links**
Link to profile/tweet or other page where bug happens.

**OldTwitter version**
v1.7.5

I don't think it's good to post other people's homepage without consent, please reply if necessary, I will send it from email

Another issue is that when trying to select the text content of a tweet using the mouse/trackpad, if the mouse is pressed or released outside the text area, it registers as a click. This behavior is not very user-friendly, especially for selecting text starting or ending from the blank space of the tweet window. Shouldn't the click action be disabled when attempting to select text?

**Comment by dimdenGD** [comment]
Text for limitation is provided by Twitter API and even though OldTwitter sends language of user seems that Twitter doesn't return translated versions of this text for some reason (while doing so for most other things)
Fixed text selection

**Comment by lrisora** [comment]
It seems like there might be an issue with the API on the homepage, but the tweet modal window correctly translates the content in Japanese and Chinese, as shown in the image. The issue seems to be related to the usage of the period character "." in the translations.

![畫面擷取於 2023-08-06 22 22 24](https://github.com/dimdenGD/OldTwitter/assets/43085437/12425c57-3228-4de5-b8d8-dc3139dfeb9f)

![畫面擷取於 2023-08-06 22 23 40](https://github.com/dimdenGD/OldTwitter/assets/43085437/2bcd39bf-9f11-4b8c-9d3f-d88e18f41614)

In Japanese and Chinese, the period character used is "。" instead of "." . It appears that the extra period "." is coming from the helpers.js (line 1785) and tweetviewer.js (line 985) files, rather than the messages.json.

To address this, the unnecessary period character should be removed in the helpers.js and tweetviewer.js files.
