### ISSUE TITLE
All interactions highlight tweets on mobile

### ISSUE THREAD

**Issue by kokoropaint** [dimdenGD/OldTwitter#396]
The recent optimizations for the mobile update have helped a lot and convinced me to start using it. However, tapping on tweets and otherwise interacting with them makes them flash in a way that is pretty distracting:

https://github.com/dimdenGD/OldTwitter/assets/37761120/167a0d54-cf3f-4a32-80a8-294fae0b6568

I'm using Kiwi Browser 116.0.5845.61 with the extension updated to 1.7.5 on a Samsung Z Flip3 (not sure if brand/model are affecting anything)

**Comment by dimdenGD** [comment]
Fixed
