### ISSUE TITLE
uneven full image display

### ISSUE THREAD

**Issue by rekvui** [dimdenGD/OldTwitter#4]
well, this seems strange, for sure
![image](https://user-images.githubusercontent.com/93687310/181379930-092b62bc-e823-44bf-9461-ce1e71dadd2b.png)
![image](https://user-images.githubusercontent.com/93687310/181379969-77f55d08-1621-4b4d-8411-dc6ba8f3b58a.png)

**Comment by dimdenGD** [comment]
not sure what you're talking about here, seems fine

**Comment by dimdenGD** [comment]
made it float to top if thats what you meant
