### ISSUE TITLE
[FEATURE] Add mute icon next to the account name

### ISSUE THREAD

**Issue by The-Cluster** [dimdenGD/OldTwitter#402]
![firefox_dXXRQt7rwe](https://github.com/dimdenGD/OldTwitter/assets/54781235/b926c77d-2162-4329-97ac-965aefc0d7bd)
![firefox_o08YpGYWhW](https://github.com/dimdenGD/OldTwitter/assets/54781235/54eb4055-778a-4dc5-b938-7122bf4ca0fb)

**Comment by iiv3** [comment]
At first I thought you want to have a button to mute/unmute an account with a single click.
But looking at the pictures the request seems about something else.

You want to see the muted icon on the profile name, even outside of their main profile, don't you?
Not only does this seem reasonable, it might be a bug.

**Comment by dimdenGD** [comment]
Added
