### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by 6306** [dimdenGD/OldTwitter#41]
TypeError: Cannot read properties of undefined (reading ’split’) at appendTweet (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/scripts/helpers.js:1119:435) at async renderTimeline (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/layouts/home/script.js:337:17) at 1614387271310151680 (OldTwitter v1.6.6.0)

**Comment by dimdenGD** [comment]
Duplicate of https://github.com/dimdenGD/OldTwitter/issues/37
