### ISSUE TITLE
Settings, Following and Followers have Layout issues on mobile

### ISSUE THREAD

**Issue by Rokotallion** [dimdenGD/OldTwitter#415]
**Describe the bug**
Going to the OldTwitter Settings, Following and Followers page on mobile extends the page to the right and down. more so in the Following and Followers page.

**Screenshots**

https://github.com/dimdenGD/OldTwitter/assets/79259221/0c8d27a6-b836-49bb-9ba7-48db7b03b9e4

**Browser**
Firefox 116.0.2 (Inspect Element Mobile Layout)
also occurs in Kiwi Browser

**Links**
twitter.com/old/settings
twitter.com/[profile_name]/following
twitter.com/[profile_name]/followers

**OldTwitter version**
1.7.5.2

**Comment by dimdenGD** [comment]
can't reproduce

**Comment by Rokotallion** [comment]
huh, weird, this also got magically fixed for me
