### ISSUE TITLE
Clarification for Arabic Translation

### ISSUE THREAD

**Issue by swagic** [dimdenGD/OldTwitter#419]
Hello dimden ^^

I noticed the note next to "ext_description"

Why is there confusion between using "تويتر" or "Twitter" for the Arabic translation?

I wanna help

Thanks!!

**Comment by dimdenGD** [comment]
I don't know I don't know Arabic

**Comment by swagic** [comment]
> I don't know I don't know Arabic

Yeah sorry. It says in README.md "Yours Truly" translated it, so I assumed it was you
