### ISSUE TITLE
Tweet body smaller / into sidebar

### ISSUE THREAD

**Issue by kissandfly** [dimdenGD/OldTwitter#42]
Would be great to be able to send tweet body into sidebar
thanks a lot for your work

**Comment by dimdenGD** [comment]
Sorry, I don't quite get what exactly do you mean by that

**Comment by kissandfly** [comment]
Thank you for your answer )
The idea is to reduce the twits column size and if possible to show only this column. Maybe it is possible with CSS only.
Then, eventually yo use this column as a sidebar, like this extension for example https://addons.mozilla.org/en-US/firefox/addon/twit-side/

**Comment by dimdenGD** [comment]
I don't think i'll add this, sorry
