### ISSUE TITLE
[Feature Request] Setting to enable automatic conversion to vxtwitter links when using copy link

### ISSUE THREAD

**Issue by LonelyNeko** [dimdenGD/OldTwitter#424]
Absolutely in love with the extension. A thing that would be a very neat quality of life feature is if pressing the copy link button could automatically copy a vxtwitter link.
If possible, a toggle-able quick copy button on tweets and profiles with the same conversion feature would be neat.
Appreciate your work!

**Comment by dimdenGD** [comment]
Already exists 
![image](https://github.com/dimdenGD/OldTwitter/assets/26517362/557a8c59-9858-49a1-a7d0-1adca46c52d6)
