### ISSUE TITLE
OldTwitter is struggling to grab images on some tweets

### ISSUE THREAD

**Issue by KingGamingYT** [dimdenGD/OldTwitter#429]
**Describe the bug**
OldTwitter is seemingly struggling to grab images for tweets, as well as some occasional slowness when loading pages. I believe this might be related to some sort of api limiting that both fxtwitter and vxtwitter, as well as other "FixTwitter" link modifiers, are experiencing currently. The new twitter interface and (regular) mobile have no such image loading issues.

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/45918062/124cbfac-2c72-4296-bfa1-3ddb64d9e9f5)
![image](https://github.com/dimdenGD/OldTwitter/assets/45918062/a1a27b69-e4ed-4060-a2b8-4d6c681adbea)

**Browser**
Chrome 115

**Links**
Any page.

**OldTwitter version**
v1.7.5.3

**Comment by 404Dev-404** [comment]
same thing is happening to me i have firefox 116.0.2 and oldtwitter v1.7.5.6

**Comment by Cherrychip7** [comment]
This just started happening to me today, at the same time as you all

**Comment by Cherrychip7** [comment]
Actually other people without old twitter are saying they are having a problem with media being broken, so maybe twitter is just breaking atm, which isn't surprising

**Comment by dimdenGD** [comment]
![Screenshot_20230813-195350](https://github.com/dimdenGD/OldTwitter/assets/26517362/021d7f45-311d-49d6-adaa-78da6264258a)
This isn't oldtwitter issue, new twitter images don't load too

**Comment by QueenKit** [comment]
This is a Twitter issue, not an OldTwitter issue. It's happening to a lot of people.
