### ISSUE TITLE
"X liked" dialog not showing up on timeline, but the tweet is 

### ISSUE THREAD

**Issue by THErlego** [dimdenGD/OldTwitter#43]
**Describe the bug**
a user i am not following appears on the timeline. when switching to regular twitter view it shows that it was a post liked by someone i did follow. 

**To Reproduce**
settings: reverse chronological with friend likes. find a tweet on TL from a user you do not follow and it will not say that the post was liked by someone you follow

**Expected behavior**
the tweet should say who liked the post, which caused it to show up on the timeline

**Screenshots**
https://i.imgur.com/ubwtmfb.png
https://i.imgur.com/WkHZuG8.png

**Browser**
chrome 108

**Comment by dimdenGD** [comment]
Fixed, it can take some time before it's released as update though
