### ISSUE TITLE
An option to add the verification icon 

### ISSUE THREAD

**Issue by Neyunse** [dimdenGD/OldTwitter#44]
I don't know if it would be a good idea and if it is possible, but could you add a setting to add the verified icon for others to see it?

**Comment by dimdenGD** [comment]
Not sure what exactly you mean, like setting to get blue checkmark that only other extension users would be able to see? Doesn't sound like a very good idea, I'm not a fan of paid checkmarks and this would be even worse lol

**Comment by Neyunse** [comment]
> Not sure what exactly you mean, like setting to get blue checkmark that only other extension users would be able to see? Doesn't sound like a very good idea, I'm not a fan of paid checkmarks and this would be even worse lol

Yeah... 👀 it looked interesting in my mind
