### ISSUE TITLE
When the Enter key is pressed during the confirmation of a conversion in Japanese input, the search is performed.

### ISSUE THREAD

**Issue by tesmite** [dimdenGD/OldTwitter#443]
**Describe the bug**
In Japanese input, when converting the input word into a suggestion such as Kanji, press the Enter key to confirm the word with the suggestion.
In the search bar, pressing the Enter key executes a search in any situation, so that once you press the Enter key to confirm the conversion of the word, the search is executed even though you are still in the middle of typing.

**Screenshots**
https://github.com/dimdenGD/OldTwitter/assets/111569199/f38e8d8c-7558-4be0-8e4b-cc831f43ce68

**Browser**
Firefox ESR 102.14.0 on Windows 10 21H2

**Links**
Anywhere a search bar exists.

**OldTwitter version**
OldTwitter v1.7.6

**Comment by tesmite** [comment]
Thank you for your prompt response, however, this problem still occurs with the combination of Firefox (ESR 102.14.0) and OldTwitter v1.7.7.1.
It does not occur with Google Chrome.
https://github.com/dimdenGD/OldTwitter/assets/111569199/c18c3133-96ff-4bfe-beda-aa93e6694136

**Comment by dimdenGD** [comment]
You're right, for some reason it's happening again even though it didn't happen after I fixed it 2 days ago, I'll check

**Comment by dimdenGD** [comment]
Now should be fixed
