### ISSUE TITLE
Repost > Retweet in notifications

### ISSUE THREAD

**Issue by Vulpix037** [dimdenGD/OldTwitter#444]
It seems that Twitter recently changed "X liked your retweet", "X retweeted your retweet", etc. in notifications to "X liked your repost", "X reposted your repost", etc.

Would it be possible for OldTwitter to change "repost" back to "retweet" in these notfications? Thanks.

![image](https://github.com/dimdenGD/OldTwitter/assets/56650249/4b539946-e1bc-4d02-a9a9-ea2b70e9f1a2)

**Comment by dimdenGD** [comment]
Already done in latest beta

**Comment by Vulpix037** [comment]
OK, thanks for the immediate reply!
