### ISSUE TITLE
Can't see the full "trends"

### ISSUE THREAD

**Issue by olivertzeng** [dimdenGD/OldTwitter#45]
**Describe the bug**
I can't scroll down to see the whole "trends"

**To Reproduce**
Scroll old twitter

**Expected behavior**
See the full "trends"

**Screenshots**
https://imgur.com/a/4sRUZBQ

**Browser**
Brave 1.47.171

**Comment by dimdenGD** [comment]
Fixed, it can take some time before it'll be released though

**Comment by olivertzeng** [comment]
oh thanks!
