### ISSUE TITLE
couple QOL improvements i thought of on a whim

### ISSUE THREAD

**Issue by staticanimal** [dimdenGD/OldTwitter#451]
1. add ability to edit user profile without redirecting to new twitter [possibly by making the modal\popup look the way it would have on old twitter or, if not possible, showing new style profile edit modal on top of old twitter]
2. reduce margin between individual buttons to prevent twitter logo from getting overlapped when enabling too many pinned links on navbar
3. fix timeline updates [both manual And automatic] forcibly closing reply popups and completely erasing anything typed within them
4. dynamically adjust width of profile popup window to always show entirety of user's display name

**Comment by dimdenGD** [comment]
1. there will be no support for sensitive apis
2. even with reduced margin if you pin everything it'll still overlap the logo (and it'll look bad)
3. already done on beta
4. ehh it looks fine already

**Comment by staticanimal** [comment]
[on 4.]
in that case i'd suggest at least giving users the option as to whether they want display name shortening or not because there are cases where it does Not look fine, e.g. for me it's shortening my display name by just two characters. the three dots that appear in place of the cut-off characters use up about the same amount of space as the characters themselves would. also that's how old twitter used to do it.
