### ISSUE TITLE
OldTwitter crash when going into notifications timeline

### ISSUE THREAD

**Issue by Pupco1** [dimdenGD/OldTwitter#455]
**Describe the bug**
When clicking on the "new tweet notifications" tab on the notifications screen, OldTwitter reverts to the new website and gives this error 
TypeError: Cannot read properties of null (reading ’append’) at appendTweet (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/scripts/helpers.js:3393:31) at async renderDeviceNotificationTimeline (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/layouts/itl/script.js:79:13) at 1693962330847989941 (OldTwitter v1.7.7)

**Screenshots**

https://github.com/dimdenGD/OldTwitter/assets/76978520/ee3ae978-ffa3-4feb-a43e-b23577c603d5

**Browser**
Chrome Version 116.0.5845.96 (Official Build) (64-bit)

**Links**
https://twitter.com/notifications

**OldTwitter version**
1.7.7

**Comment by dimdenGD** [comment]
Do you have Discord to help debug this?

**Comment by Pupco1** [comment]
> Do you have Discord to help debug this?

yes "pupco1"

**Comment by dimdenGD** [comment]
Fixed, update
