### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by mengyang00** [dimdenGD/OldTwitter#458]
I've added the translation language, why some tweets still don't use translation

![屏幕截图 2023-08-23 015648](https://github.com/dimdenGD/OldTwitter/assets/112148106/124a1daf-5ef9-4652-9e4b-ca3b2a79f14e)

**Comment by dimdenGD** [comment]
Sometimes Twitter simply doesn't provide ability to translate for some reason. There's nothing to be done about this

**Comment by mengyang00** [comment]
> 有时 Twitter 出于某种原因根本不提供翻译功能。对此无能为力



> Sometimes Twitter simply doesn't provide ability to translate for some reason. There's nothing to be done about this

Well, thanks

**Comment by mengyang00** [comment]
> Sometimes Twitter simply doesn't provide ability to translate for some reason. There's nothing to be done about this

Well, thanks
