### ISSUE TITLE
"Something went wrong" popup appears when tweeting, favoriting (liking), etc. in some versions of Firefox

### ISSUE THREAD

**Issue by tesmite** [dimdenGD/OldTwitter#467]
**Describe the bug**
When I try to tweet or add a favorite (like) to a tweet, a popup saying "Something went wrong" comes up and the display returns to as if the action was not taken.
However, in reality, the action is still taken (reloading the window reflects the action).
This does not happen on the tweet detail page displayed in a modal window.

**Screenshots**
https://github.com/dimdenGD/OldTwitter/assets/111569199/b018d8d2-305b-47e4-b476-9a51f27814c7

**Browser**
Firefox ESR 102.14.0 on Windows 10 21H2
This problem does not occur in Firefox 116 or Edge 116 and is believed to be caused only by some older versions of Firefox.

**Links**
Almost all pages except the tweet detail page displayed in a modal window

**OldTwitter version**
OldTwitter v1.7.7.2

**Comment by Fapo39** [comment]
can confirm this also happens to me for ESR and Nightly versions, normal works fine but then can't use the Tweetdeck one

**Comment by tesmite** [comment]
> can confirm this also happens to me for ESR and Nightly versions, normal works fine but then can't use the Tweetdeck one And it's not just liking posts, but rt, and post as well will always bring up the "something went wrong" popup
> 
> OldTwitter 1.7.8.1 Firefox 102.15.0esr (64-bit)

I mentioned this as if it were caused by an older version, but does it also occur with Nightly?
If so, this problem may be due to the default settings in about:config in these releases that are different from the stable version.
Thank you.

**Comment by tesmite** [comment]
I updated Firefox ESR to 115 and it works fine.
Therefore, I would consider this a low-priority issue that may be occurring in some non-main version of Firefox.

**Comment by ReiFan49** [comment]
Ah, so I need to update the OS? Let me try first. On 102.12.0 ESR rn.
Do you think this kind of error can be improved into a popup instead alert?

**Comment by tesmite** [comment]
Given that the action is reflected on the X (Twitter) server side, it seems that there is a part of the process for displaying the data that reflects the action that cannot be executed correctly in some Firefox versions, and an error is being returned.
Therefore, it should not be difficult to change the error display caused by this part.
