### ISSUE TITLE
rate limit exceeded

### ISSUE THREAD

**Issue by calopies** [dimdenGD/OldTwitter#475]
**Describe the bug**
So, I've been using old twitter since they add rate limit is a thing, and didn't have limit problem until now. Suddenly got rate limit exceeded. Idk if this bug or twitter suddenly broken again.

**Screenshots**
https://imgur.com/a/orpfDpy

**Browser**
Mozilla Firefox (116.03)

**Links**
https://twitter.com/home

**OldTwitter version**
1.7.7.3

**Comment by dimdenGD** [comment]
Nothing to fix

**Comment by calopies** [comment]
rip, thanks for the reply though!
