### ISSUE TITLE
Paragraph breaks for longer alt text

### ISSUE THREAD

**Issue by GJJellyfish** [dimdenGD/OldTwitter#482]
I saw a post that was transcribing screenshots of an article (and adding a little bit of side commentary) using alt-text, but I noticed that the alt-text gets cut off after a certain length. It feels like alt-text in image expansion needs to be reworked a bit to allow longer alt-text to be shown (or perhaps replicate the alt text drop down on current web Twitter)

**Comment by dimdenGD** [comment]
Link to tweet?

**Comment by dimdenGD** [comment]
Text is fully shown 
![image](https://github.com/dimdenGD/OldTwitter/assets/26517362/944aaa74-4585-42d5-8169-0eac8e959754)

**Comment by GJJellyfish** [comment]
huh, i was talking about the caption under the image when you expand it. i had no clue it showed up as a tooltip, though.

**Comment by dimdenGD** [comment]
What caption? There are no captions for alt text other than tooltip

**Comment by GJJellyfish** [comment]
I am talking about the UI that appears when you click on an image. Unless this is something Opera GX does

![image](https://github.com/dimdenGD/OldTwitter/assets/17233256/4526f431-6f31-4a47-915c-a49ab535c105)

**Comment by dimdenGD** [comment]
This is a feature of image viewer library I'm using, I can't do anything about it, just hover on images instead
