### ISSUE TITLE
Video or GIF playback shows bugged colors when playing

### ISSUE THREAD

**Issue by m3k1e** [dimdenGD/OldTwitter#49]
I was browsing Twitter for a moment and then this showed up on main menu but not the tweet itself. Any ideas why this happened? I'm using AMD Ryzen 3 2200G.

![20230303_205539.jpg](https://user-images.githubusercontent.com/41316133/222727416-a724662d-04d3-4ad5-b958-874b296c3834.jpg)

![20230303_210707.jpg](https://user-images.githubusercontent.com/41316133/222727816-4131d646-2c01-48aa-9d2c-d94c255e9c2d.jpg)

**Comment by dimdenGD** [comment]
this is definitely not issue with oldtwitter since it just uses basic html elements to show video, so it's either some weird issue with your browser, hardware or maybe extensions conflicting
