### ISSUE TITLE
Extension randomly retweets tweets I scroll past or click on

### ISSUE THREAD

**Issue by Phineas1500** [dimdenGD/OldTwitter#50]
When I scroll On Old Twitter and click on tweets, they periodically get retweeted to my account. This happens without me hitting the retweet button.

I am not notified that my account retweeted anything, and I only notice when I see users liking something I scrolled past that I didn't realize was being retweeted to my account.

This can especially be an issue if I scroll past / click on a problematic tweet that proceeds to get automatically retweeted. My followers will then be notified or notice that I retweeted that problematic tweet.

This issue is happening for me on the Arc browser, which is Chromium.

**Comment by dimdenGD** [comment]
oldtwitter doesn't retweet anything on its own, the only way i could think of this happening is you accidentally pressing T button which is hotkey for retweet
