### ISSUE TITLE
Homepage tweets not loading

### ISSUE THREAD

**Issue by FasterMars** [dimdenGD/OldTwitter#51]
**Describe the bug**
Tweets on the homepage don't load and a message stuck on saying "Loading tweets"

**To Reproduce**
Open https://twitter.com/home in FireFox

**Screenshots**
![image](https://user-images.githubusercontent.com/91949513/226827667-a0aeca38-f1f9-4e8c-9dc8-2b48ef6b121d.png)

**Expected behavior**
Tweets should be loaded instead of a message saying loading tweets

**Browser**
Firefox latest

**Comment by dimdenGD** [comment]
Can you press F12 and go to Console tab and screenshot what errors are there

**Comment by FasterMars** [comment]
Cookie “lang” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite twitter.com:155:512
The resource at “https://abs.twimg.com/responsive-web/client-web-legacy/polyfills.37df27aa.js” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. twitter.com
The resource at “https://abs.twimg.com/responsive-web/client-web-legacy/vendor.508b33fa.js” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. twitter.com
The resource at “https://abs.twimg.com/responsive-web/client-web-legacy/i18n/en.66c6f8ba.js” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. twitter.com
The resource at “https://abs.twimg.com/responsive-web/client-web-legacy/main.826ce92a.js” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. twitter.com
The resource at “https://abs.twimg.com/responsive-web/client-web-legacy/shared~loader.Typeahead~bundle.LoggedOutHome~bundle.Search.c076af5a.js” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly.

There's nothing except these warnings in the console

**Comment by FasterMars** [comment]
Thanks! It worked
