### ISSUE TITLE
something went wrong 

### ISSUE THREAD

**Issue by AI0183** [dimdenGD/OldTwitter#52]
**Describe the bug**
Tweets on the homepage don't load and a message is stuck saying "Loading tweets"

**To Reproduce**
Open https://twitter.com/home in Chrome
**Expected beh
![chrome_HWudp2ADkf](https://user-images.githubusercontent.com/53639956/227029220-e8aa912b-5c22-4341-a17d-383b8919738f.png)
avior**

**Screenshots**
If applicable, could you add screenshots to help explain your problem?

**Browser**
Chrome latest

**Comment by dimdenGD** [comment]
I don't see it being stuck on "Loading tweets" on your screenshot

**Comment by dimdenGD** [comment]
Fixed error on your screenshot, might take some time until it's published
