### ISSUE TITLE
Site using this extension via Firefox is bugging AS WORSE

### ISSUE THREAD

**Issue by themattreinhart** [dimdenGD/OldTwitter#521]
**Describe the bug**
Entering Twitter switches to the new and your layout occassionally and even the home page using OldTwitter after bad switch causes the timeline to load empty UNTIL a few minutes later unless I force refresh the site. Even the title bar doesn't switch to "Twitter" but "X" so its really a bad bug caused by server side changes.

Idk if this is because of a layout changes on the newer layout or something. It used to load and switch to that extension fast. (I'm using Windows, Mac works as a charm)

UPDATE: Also slowish... so its the layout changes on the new one.

**Screenshots**
(Bear with the right side of the pic; thats my extension of my monitor)

![image](https://github.com/dimdenGD/OldTwitter/assets/141158116/6cc418ee-6a9f-4a95-96d9-2983dd1f7a1c) 
**_Twitter forcing the new layout rather than the OldTwitter layout before refreshing by itself_**
![image](https://github.com/dimdenGD/OldTwitter/assets/141158116/f2150c0a-7d28-41e1-a4b9-96cc01a600de)
**_Twitter after refreshing to the OldTwitter layout_**

**Browser**
Firefox 117.01 (Windows)

**Links**
On the main site and whenever possible.

**OldTwitter version**
17.9.1

**Comment by dimdenGD** [comment]
This was fixed in 1.7.9.2, update
