### ISSUE TITLE
the dumb x link embeds dont work

### ISSUE THREAD

**Issue by homosexuayla** [dimdenGD/OldTwitter#522]
(im calling the x stuff dumb not you just to be clear)

so yeah twitter is giving you the links as x links on the official updated app and site and they aren't working here :(

example:
![image](https://github.com/dimdenGD/OldTwitter/assets/76013118/0655ce72-b155-4773-af85-18025b11ee1d)

**Comment by dimdenGD** [comment]
link to tweet

**Comment by homosexuayla** [comment]
> link to tweet

[here](https://twitter.com/jestingtime/status/1701802730137006299)

**Comment by dimdenGD** [comment]
They don't embed in new Twitter too
