### ISSUE TITLE
Having OldTwitter on an active tab makes youtube run badly sometimes

### ISSUE THREAD

**Issue by derreka** [dimdenGD/OldTwitter#524]
**Describe the bug**
Some youtube videos run like absolute shit (constantly loading even when the video is completely loaded or even when going 5 seconds back) when having OldTwitter on an active tab in a different window of the same browser. I am not sure what exactly causes it, but I know for sure that switching to a non-OldTW tab fixes the issue. 
I think it also happens with different players, but I'm not sure

**Browser**
Opera GX, current and previous versions

**Links**
Can't pin it down exactly, but probably everywhere

**OldTwitter version**
Any (at least the ones after the ratio limits scandal)

**Comment by sontopo** [comment]
Write opera://flags and search for **Experimental QUIC protocol** or just **QUIC**, if it appears, disable it and restart the browser, now try again.

**Comment by dimdenGD** [comment]
I don't see how QUIC would be anyhow related to performance

**Comment by sontopo** [comment]
> I don't see how QUIC would be anyhow related to performance

https://www.reddit.com/r/chrome/comments/14bzu58/comment/joigx5j/?utm_source=share&utm_medium=web2x&context=3

**Comment by dimdenGD** [comment]
How would having OldTwitter tab open relate to that though, if switching to other tab makes it work again, I assume it's something related to performance/rendering, not connectivity

**Comment by derreka** [comment]
Just tried disabling QUIC and watching YT while using OldTw and looks like it works for now. Can't say 100% bc the issue is kinda random but it may indeed be one of those "really complex things having really complex interactions that can go to shit with the silliest of things" scenario

**Comment by iiv3** [comment]
Could it be related to #495 ?

Just for the test, enable QUIC back and remove the animated element on the OldTwitter about box. I did that with the zapper of UBlock Origin.

You can do the same using built-in devtools in chrome (and firefox):
Press F12 to open the devtools.
Select "Elements" ("Inspector")
Use the select tool to select the about box with the animation. (The picket is on the left end of the bar, where "Elements" tab is selected.)
It would bring you to the collapsed node.
Use the right button to bring drop-down menu and select "Delete".

If something goes wrong, refresh and try again.

**Comment by derreka** [comment]
I enabled it back and tried to recreate the issue but as I said it's quite random (or at the very least I have no idea what could've caused it) and for the moment everything seems fine but I'll keep that in mind if it happens again (and tbh it may have been fixed after the API fucky wucky and the subsequent fix so who knows)

**Comment by derreka** [comment]
Ok at this point this might count as necroing but I haven't had that problem for a long time so I guess it's "solved"
