### ISSUE TITLE
cant view profiles for some reason

### ISSUE THREAD

**Issue by Arcadius2006** [dimdenGD/OldTwitter#525]
**Describe the bug**
When you try to enter someone's profile, a JSON error pops out and it tells you to go to the main page, it and the tweet page work fine besides for not displaying your profile

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/93880348/7cd0f725-da2a-4c83-b557-2413c219b624) 
![image](https://github.com/dimdenGD/OldTwitter/assets/93880348/8e39bd54-d559-46d9-999e-47d710cd8ca9) 
![image](https://github.com/dimdenGD/OldTwitter/assets/93880348/22ae6cc3-38c6-480d-a720-dd3b2b607ed9)

**Browser**
Google Chrome 116.0.5845.187 64-bit

**Links**
Any profile page.

**OldTwitter version**
1.7.9.2

**Comment by Arcadius2006** [comment]
![image](https://github.com/dimdenGD/OldTwitter/assets/93880348/51b93aec-ff11-4f67-95cc-5d30201875fc)
sometimes this also appears

**Comment by Arcadius2006** [comment]
note: regular twitter is fine, this is just for OldTwitter

**Comment by VaelophisNyx** [comment]
Got this just now too; worked fine an hour ago

**Comment by mollyesbian** [comment]
enncountering the same issue. seems to be affecting multiple users.

**Comment by g-gundam** [comment]
He seems to be aware of the problem.
https://twitter.com/dimdenEFF/status/1702008104479547395

**Comment by danielah05** [comment]
having the same issue, ive also just randomly had my timeline just not load at all recently and i would have to refresh multiple times for it to load

**Comment by xinomp** [comment]
yup also have this issue

**Comment by VaelophisNyx** [comment]
issue resolved on my end!

**Comment by Arcadius2006** [comment]
AW SHIT ITS BACK

**Comment by thepwrtank18** [comment]
\*click\* \*click\* \*click\*
![image](https://github.com/dimdenGD/OldTwitter/assets/57580668/c46bafd1-ee7b-4f15-b788-2f5a29afacd4)
