### ISSUE TITLE
Completely broken on Firefox

### ISSUE THREAD

**Issue by thepwrtank18** [dimdenGD/OldTwitter#526]
**Describe the bug**
Nothing's working on Firefox. At all.

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/57580668/7c84a503-af1c-41d9-90cf-6ec3a2ae49a2)
![image](https://github.com/dimdenGD/OldTwitter/assets/57580668/f6c1e2cc-c9a6-46d9-9714-5992db4e54af)
![image](https://github.com/dimdenGD/OldTwitter/assets/57580668/977cc191-27a1-4afc-b6b0-295be607b017)

**Browser**
Firefox Developer Edition 118.0b8 (64-bit)

**OldTwitter version**
v1.7.9.2

**Comment by pankofufu** [comment]
https://twitter.com/dimdenEFF/status/1702013792240980218

**Comment by Ghost-Miner** [comment]
It isnt completely broken, i can still see and reply to tweets in the hashtag section, but rest of it doesnt work sadly.
