### ISSUE TITLE
Everything broken on chrome (feed, profile, notifications)

### ISSUE THREAD

**Issue by Lacerta-agilis** [dimdenGD/OldTwitter#527]
**Describe the bug**
Feed: is empty, message "You're not following anyone so there's no tweets found! Change your timeline type to 'Algorithmical' in [OldTwitter settings](https://twitter.com/old/settings)." is being displayed (that is not true, I have enough followed users and don't want algorithmical feed 

When I press then the button "load new tweets", they appear, but the error message remains hanging, and after some scrolling everything disappears again. 
The icon/link to my profile is disappeared from the headline, I can't find it.
When I go to notifications, it's just empty. Clicking on 'load more' doesnt help (nothing happens)
Link to messages is broken.
Button 'tweet' is broken.
When trying to open a user profile with a link, a JSON error is returned

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/144956945/aea31af2-55b9-4d51-a0b6-67734aa455e8)
![image](https://github.com/dimdenGD/OldTwitter/assets/144956945/48723efc-5368-4ae6-a6a1-c9d21f5e7ccd)
![image](https://github.com/dimdenGD/OldTwitter/assets/144956945/2cb05323-8fc9-4d66-8929-65f7065efa57)

**Browser**
Version 117.0.5938.63 (Official Build) (64-bit)
(but the same shitfall on Firefox 117.0.1 (64-bit)

**Links**
Link to profile/tweet or other page where bug happens: JUST EVERYWHERE ON TWITTER DOT COM

**OldTwitter version**
Running [OldTwitter](https://github.com/dimdenGD/OldTwitter) v1.7.9.2

**Comment by dimdenGD** [comment]
https://twitter.com/dimdenEFF/status/1702056095190020371

**Comment by Lacerta-agilis** [comment]
thanks for a fast reply, waiting soo much for the update
