### ISSUE TITLE
OldTwitter not loading properly

### ISSUE THREAD

**Issue by Andromander** [dimdenGD/OldTwitter#529]
**Describe the bug**
Various features are not loading properly, such as custom UI colours, the timeline of users you follow, as well as the profile not showing up. After a while, showing your timeline will blank out and suggest Algorithmical instead.

In the screenshot, what should be purple is showing as blue instead. I am logged into my profile as it shows fine in new Twitter.

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/29526717/91502c84-da2e-4bee-93aa-07eb5604e647)

In the screenshot, what should be purple is showing as blue instead. I am logged into my profile as it shows fine in new Twitter.

**Browser**
Chrome (Version 117.0.5938.62)

**Links**
https://twitter.com/home, note that you must be on one of the page views that only shows Following

**OldTwitter version**
1.7.9.2

**Comment by dimdenGD** [comment]
This was fixed already and update is awaiting approval from Chrome Web Store

**Comment by Andromander** [comment]
Just spotted #527, yeah
