### ISSUE TITLE
Error No status found with that ID.

### ISSUE THREAD

**Issue by QueenKit** [dimdenGD/OldTwitter#53]
**Describe the bug**
Says some tweets can't open because of errors

**To Reproduce**
Shows it on this persons homepage https://twitter.com/HaleySpades
Just a heads up, Her page is a bit pornographic

>  **_Missing: No status found with that ID. at 1637944230453837824 (OldTwitter v1.6.7)**

**Expected behavior**
Just a normal browse like all other pages.

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/96992261/227034786-b399f88a-eecc-4f04-9ecb-31740467eab1.png)

**Browser**
Chrome

**Comment by dimdenGD** [comment]
Fixed, it can take some time before update will be published
