### ISSUE TITLE
Profile won't load

### ISSUE THREAD

**Issue by AmarinReyny** [dimdenGD/OldTwitter#530]
**Describe the bug**
My profile won't load while using OldTwitter. My icon, username, bio, and other stuff just says "loading," and my feed says I'm not following anyone.

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/60671985/820629aa-37b5-4fb6-9074-704116c450a9)

**Browser**
Chrome 116.0.5845.168 (Official Build) (32-bit)

**OldTwitter version**
v1.7.9.2

(It says "last version: 1.8.0," but I don't see any options for updating - sorry if it's already fixed!)

**Comment by dimdenGD** [comment]
You'll autoupdate in 6-12 hours

**Comment by AmarinReyny** [comment]
> You'll autoupdate in 6-12 hours

Ah, okay, Thank you!
