### ISSUE TITLE
Extension is pretty much completely broken for no app

### ISSUE THREAD

**Issue by muuyo** [dimdenGD/OldTwitter#531]
**Describe the bug**

When using the site, today it's entirely broken - "Loading" instead of my profile, broken images, the feed randomly refreshing in really annoying ways, some profiles refusing to load... et cetera.
**Screenshots**
If applicable, add screenshots or video to help explain your problem.
![image](https://github.com/dimdenGD/OldTwitter/assets/34991771/51c0b67d-6184-42cf-a5d6-9e453bbaf239)

**Browser**
Include your browsers name and it's version.
Firefox 117.0.1
**Links**
Link to profile/tweet or other page where bug happens.
None specific, however when I visit some profiles such as [this one](https://twitter.com/Mossstone_1mzn9) it produces this error:
![image](https://github.com/dimdenGD/OldTwitter/assets/34991771/d3334a84-270d-4ef7-b920-6241b2c9c9fa)

**OldTwitter version**
Can be seen on bottom-right
1.7.9.2
Here's an additional Pastebin link to the output of my browser console when refreshed. Might be helpful? https://pastebin.com/pfV8yfiA

**Comment by dimdenGD** [comment]
Update extension

**Comment by muuyo** [comment]
My firefox was refusing to update it until removed, weird.
Thanks!
