### ISSUE TITLE
Profiles do not display

### ISSUE THREAD

**Issue by spifory** [dimdenGD/OldTwitter#534]
**Describe the bug**
When going to ___any___ profile on Twitter, it returns the following error
`SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data`

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/80943664/dbaf24f8-4574-4050-a9e0-00451ed1f9b1)
![image](https://github.com/dimdenGD/OldTwitter/assets/80943664/623a7f60-77a7-4050-8462-a8c7bf6c5dae)

**Browser**
Mozilla Firefox Developer Edition for Arch Linux 118.0b6 (64-bit)

**Links**
Any Twitter account applies, but in this case I went to [@spifory_](https://twitter.com/spifory_)

**OldTwitter version**
Running [OldTwitter](https://github.com/dimdenGD/OldTwitter) v1.7.9.2 (last version: 1.8.0)

**Comment by dimdenGD** [comment]
Update
