### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading ’core’)

### ISSUE THREAD

**Issue by pan93412** [dimdenGD/OldTwitter#539]
**Describe the bug**

```
script.js:551
TypeError: Cannot read properties of undefined (reading 'core')
    at parseTweet (apis.js:181:20)
    at apis.js:1682:45
```

**Screenshots**

![TypeError: Cannot read properties of undefined (reading ’core’) with DevTools enabled](https://github.com/dimdenGD/OldTwitter/assets/28441561/ac1d8ff6-531a-4c2c-972b-710abf4a48f6)

**Browser**

Arc 1.8.0 (41552), Chromium Engine Version 116.0.5845.187

**Links**

Your profile page.

**OldTwitter version**

v1.8.0

**Comment by pan93412** [comment]
![CleanShot 2023-09-16 at 13 02 09@2x](https://github.com/dimdenGD/OldTwitter/assets/28441561/82da881f-e29b-4926-997e-17799522abdb)

`result` can be undefined. Previous stack:

![CleanShot 2023-09-16 at 13 04 55@2x](https://github.com/dimdenGD/OldTwitter/assets/28441561/6f6ab943-8661-4afa-9ace-0b7d3e7611a8)

![CleanShot 2023-09-16 at 13 05 29@2x](https://github.com/dimdenGD/OldTwitter/assets/28441561/647f9f45-e135-4ba4-a976-f16a847e5ca1)

**Comment by dimdenGD** [comment]
This was fixed in 1.8.0.2

**Comment by pan93412** [comment]
> This was fixed in 1.8.0.2

Hmm, I did not receive this update from Chrome Web Store :(

**Comment by dimdenGD** [comment]
Because it's still in review

**Comment by pan93412** [comment]
Thanks!
