### ISSUE TITLE
Option to be able to send tweets to DMs

### ISSUE THREAD

**Issue by planet-bluto** [dimdenGD/OldTwitter#542]
I would love to have an option in a tweet drop-down to send a tweet to DMs, just like in modern Twitter. It's a feature I used a fair amount and currently I just open the tweet in newTwitter, and then click the option there.

I have no idea how hard it'd be to make the modal for that would be, but I'd assume it'd just list all you messages like it would when you view them normally, but it'd have a send button next to it instead and clicking so would just jump to the DM with the tweet already inputted in the input element.

**Comment by dimdenGD** [comment]
There's an easier way, you can just copy tweet link and send in dms and it'll show as tweet

**Comment by dimdenGD** [comment]
Added the button

**Comment by planet-bluto** [comment]
> There's an easier way, you can just copy tweet link and send in dms and it'll show as tweet

I had the copy link button to vxtwitter, so it wouldn't work, but I could've just removed the 'vx' from it, lol
Thank you 🙏
