### ISSUE TITLE
User page titles that start with "X" (accounts not related to X) are shown incorrectly

### ISSUE THREAD

**Issue by AlexzanDev** [dimdenGD/OldTwitter#557]
**Describe the bug**
If you open a page of an account whose name starts with "X", the page title will show "Twitter" instead of the letter X. I get that this is due to the actual X, but, for example, with Xbox accounts it shows "Twitterbox" or "TwitterboxGamePass".

**Screenshots**
<img width="174" alt="image" src="https://github.com/dimdenGD/OldTwitter/assets/35893655/75d7034d-84b7-47dd-80ec-9dce654cbafd">
<img width="175" alt="image" src="https://github.com/dimdenGD/OldTwitter/assets/35893655/a703a4e7-c926-4853-b5f6-31ce009a5b38">

**Browser**
Google Chrome 117.0.5938.92 on Windows 11.

**Links**
https://twitter.com/XboxGamePass
https://twitter.com/Xbox
And possibly other accounts that have X as their first letter in the name.

**OldTwitter version**
v1.8.1

**Notes**
I don't know if this will be fixed because of the horrible naming of Twitter, but I think it's a silly bug that I wanted to report anyway.

**Comment by dimdenGD** [comment]
I can't reproduce this bug, maybe you're using some other extensions that do this?

**Comment by AlexzanDev** [comment]
> I can't reproduce this bug, maybe you're using some other extensions that do this?

Yes, it was Control Panel for Twitter's fault (that I keep enabled despite using OldTwitter)! Thank you.
