### ISSUE TITLE
Using OldTwitter prevents twitter links in gmail from working correctly, also interferes with Bluesky

### ISSUE THREAD

**Issue by AmarinReyny** [dimdenGD/OldTwitter#559]
**Describe the bug**
When trying to open twitter links from gmail, it opens a redirect page intended to bring me to the linked tweet, but it never gets past that redirect page. Also, having recently joined Bluesky, I've noticed that having Oldtwitter modifies the layout on Bluesky, and does not work properly (which is understandable since it wasn't meant for Bluesky anyway), preventing me from being able to scroll when using the search function.

**Browser**
Google Chrome
Version 116.0.5845.210 (Official Build) (32-bit)

**OldTwitter version**
v1.8.1

**Comment by dimdenGD** [comment]
OldTwitter doesn't have access to bluesky and doesn't modify it in any way, I can't reproduce your issue for bluesky

**Comment by AmarinReyny** [comment]
> OldTwitter doesn't have access to bluesky and doesn't modify it in any way, I can't reproduce your issue for bluesky

To be fair, the Bluesky issue was something I had encountered a couple of days ago, when I had only just joined, and was still adding feeds. I couldn't scroll through the feed search function until I turned OldTwitter off. I figured it was a bit odd, but didn't think to do a bug report then. I only initially intended to make this bug report about the gmail links, and when I was typing it, I figured I should mention the Bluesky issue as well. In any case, after logging onto Bluesky today after seeing your reply, and the issue seems to have gone away.

Maybe something changed on Bluesky's end? I know it's made by a lot of the same people who used to work at Twitter, so I wouldn't be surprised if they were still using stuff from Twitter for a while, and if that ended up tricking OldTwitter into thinking Bluesky was the same thing as Twitter in some way.

The gmail link issue still persists, though.

**Comment by dimdenGD** [comment]
Can you give me URL that endless redirects get stuck at?

**Comment by AmarinReyny** [comment]
> Can you give me URL that endless redirects get stuck at?

Here's one:

https://twitter.com/i/redirect?url=https%3A%2F%2Ftwitter.com%2FMoringmarkMark%2Fstatus%2F1707032392593277268%3Fcxt%3DHBwWqIXcyda6zLAvAAAA%26cn%3DZmxleGlibGVfcmVjcw%253D%253D%26refsrc%3Demail&t=1+1695877509982&cn=ZmxleGlibGVfcmVjcw%3D%3D&sig=f65732c4ce7961cc5a5da6f74a73b7dea085b811&iid=841990dc81574112804666aa60a1d168&uid=1099030732985507840&nid=244+272699393
