### ISSUE TITLE
Cannot read user_results.js

### ISSUE THREAD

**Issue by QueenKit** [dimdenGD/OldTwitter#56]
**Describe the bug**
as the title states.

**To Reproduce**
Got no clue as it happens when I load up the home page

**Expected behavior**
homepage load like normal

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/96992261/228079200-547c5a11-f0d7-4e96-b9b2-decf00d98e44.png)

**Browser**
Chrome

**Comment by dimdenGD** [comment]
This was fixed in https://github.com/dimdenGD/OldTwitter/issues/52 but wasnt published yet
