### ISSUE TITLE
Embeds to certain platforms autoplay, ignoring browser settings

### ISSUE THREAD

**Issue by fivefivefiver** [dimdenGD/OldTwitter#566]
**Describe the bug**
Certain tweets with embeds to podcast hosting services autoplay sound whenever they're loaded into the timeline. This is annoying, because sometimes it's outright impossible to figure out which tweet it is. 

Unfortunately, I can't provide more detail than that; it happens rarely enough for me not to spot a pattern and just often enough to be annoying. Can it be possible to somehow prevent iframe embeds in Old Twitter to stop this issue from occurring?

**Browser**
Firefox 117.0.1

**OldTwitter version**
v. 1.8.1.2

**Comment by dimdenGD** [comment]
There's currently no way to disable iframes, what are the platforms that do this?

**Comment by fivefivefiver** [comment]
It seems to happen with Ed Zitron's (@edzitron) podcast embeds, for instance in the tweet below:

https://twitter.com/edzitron/status/1708889155001106875

**Comment by fivefivefiver** [comment]
> There's currently no way to disable iframes, what are the platforms that do this?

It's happening to me in Firefox on both MacOS and Windows.
