### ISSUE TITLE
csrf cookie and header

### ISSUE THREAD

**Issue by Navycide** [dimdenGD/OldTwitter#57]
**Describe the bug**
I cannot tweet at all, and often on loading the timeline, an error shows up saying "This request requires a matching csrf cookie and header. at 1642471357748314112 (OldTwitter v1.6.7)"

**To Reproduce**
Attempt to tweet or access the timeline

**Expected behavior**
Be able to load and send tweets

**Screenshots**
![image](https://user-images.githubusercontent.com/129663628/229350576-af38d222-cdbe-4080-a9e8-53dbc39312bd.png)

**Browser**
Opera GX LVL4 (core: 96.0.4693.117) Chromium version:110.0.5481.192

**Comment by dimdenGD** [comment]
Press F12 and go to Console and try to tweet and show what error shows up there
