### ISSUE TITLE
Fellow oldTwitter indicator & Last login statuses

### ISSUE THREAD

**Issue by planet-bluto** [dimdenGD/OldTwitter#572]
This definitely is more of a vanity thing, but I would feel such a sense of community to know if someone else is also using this extension by some indicator on their user profile page. The indicator would show up if someone logs in to twitter with the extension. Hovering over it could also tell you when the last logged in (with the extension on of course). 

![image](https://github.com/dimdenGD/OldTwitter/assets/44180499/f1dd0a00-6c9f-42ea-9469-122a48473789)
_(Quick mockup, but I'd make it stand out a bit more than this, lol)_

The log-in info could be databased the same way he account colors are, but I don't know how it's done or if it's even viable. And the 'login information' would just be like a giant map with the keys being the account ids and the value is a timestamp and to check if someone would have the indicator you'd check if their account id is even in the database, and then since the value would be a timestamp you can calculate how long it's been since their last log-in and use momentjs to get the relative string... _But that's just my hypothesis_

**Comment by dimdenGD** [comment]
This won't be added
