### ISSUE TITLE
[ Profile Custom Themes ] Can't use images that aren't from Twitter.

### ISSUE THREAD

**Issue by ktg5** [dimdenGD/OldTwitter#573]
**Describe the bug**
Unsure if this is fixable, but when trying to set a custom background image for a Twitter profile with custom themes enabled, the background doesn't change and the following error shows up in console:
![image](https://github.com/dimdenGD/OldTwitter/assets/42522603/a5b496c9-b193-4180-aaf4-021d61fcadca)
A solution to this issue was using Twitter's image CDN, `https://pbs.twimg.com/`, but it's not on the link whitelist.

**Browser**
Brave Version 1.58.137
Chromium: 117.0.5938.153 (64-bit)

**Links**
https://twitter.com/oocnichijou

**OldTwitter version**
v1.8.1.2

**Comment by dimdenGD** [comment]
Can't reproduce, imgur images load fine for me

**Comment by ktg5** [comment]
Hmm, weird...
It wasn't just Imgur links for me though; other links like Discord & whatever else are in the supported links didn't work. It might be something on my side. I'll look into it more when I can.

**Comment by ktg5** [comment]
Nevermind -- I somehow fixed it by re-enabling my extensions? I don't really know how this happened lol.
