### ISSUE TITLE
Add a report button.

### ISSUE THREAD

**Issue by ScratchOSTeam** [dimdenGD/OldTwitter#576]
Basically what the title says. The reason I'm asking is bc there isn't a report button in the menus as you can see
![image](https://github.com/dimdenGD/OldTwitter/assets/99697031/7b22db4e-fd3d-46c7-a41a-955ae2ea0bb0)

**Comment by dimdenGD** [comment]
This will not be added, go to new Twitter to report someone

**Comment by ni1chigo2115** [comment]
I would like at least a button to temporarily go to NewTwitter from the account page. (Close it to go back to oldtwitter)
If possible, it would be nice to be able to do reports on the fly. Not being able to report a scam account is a pain.

**Comment by dimdenGD** [comment]
There is such button already on bottom-right of page

**Comment by defaultxr** [comment]
> This will not be added, go to new Twitter to report someone

Out of curiosity, why not? Is it difficult?

Would a pull request implementing such be accepted?

**Comment by dimdenGD** [comment]
Because it's dangerous to implement such critical APIs
