### ISSUE TITLE
My own tweets are not loading

### ISSUE THREAD

**Issue by Dan0xE** [dimdenGD/OldTwitter#578]
**Describe the bug**
My Profile is blank, I can not see the things I tweeted/replied to on my own profile.
This only happens occasionally!

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/23116945/f98ad82b-95e6-4838-a785-2a66e8c7ab27)
![image](https://github.com/dimdenGD/OldTwitter/assets/23116945/03aadc42-6020-42e3-82b8-fad4e74b44e3)

**Browser**
Chrome Version 117.0.5938.150

**Links**
https://twitter.com/dan0xe

**OldTwitter version**
1.8.1.4

**Comment by Dan0xE** [comment]
One thing I noticed is that this bug goes away when I visit one of my own tweets via a direct link, after that my profile and all the tweets load as they should, maybe it's a Twitter issue and not an issue with the extension? (would not be surprised)

**Comment by dimdenGD** [comment]
Twitter was having issues, your profile loads fine now
