### ISSUE TITLE
Retweet handler with icon only and blank text

### ISSUE THREAD

**Issue by DaGamerFiles** [dimdenGD/OldTwitter#58]
**Describe the bug**
Retweet handler indicated by the retweet icon does not showing proper text with the user that retweeted.

**To Reproduce**
Open regular web Twitter with the extension enabled.

**Expected behavior**
Retweet handler shows text including which user retweeted it.

**Screenshots**
![Retweet handler with blank text bug](https://media.discordapp.net/attachments/324487601488920576/1092098962724491355/image.png)

**Browser**
Vivaldi 5.7.2921.65 (Stable channel) (64 bit)

**Comment by exentio** [comment]
Having the same issue with Chrome 112.0.5615.49

**Comment by dimdenGD** [comment]
@DaGamerFiles can you disable adblocker and see if it fixes the issue for you? I've never had this problem and I don't see how programmatically it can ever happen

**Comment by DaGamerFiles** [comment]
> Having the same issue with Chrome, turns out it's Ublock

As @exentio said, I think the issue was from uBlock Origin, built-in Vivaldi's Tracker and Ad Blocker works fine with the extension.

**Comment by exentio** [comment]
I didn't want to completely disable uBlock, so disabling just the cosmetic filter worked fine for me
