### ISSUE TITLE
Ability to untag people in replies

### ISSUE THREAD

**Issue by TheAgamer554** [dimdenGD/OldTwitter#586]
When replying to a tweet there is no option to untag the people who aren't the direct recipient or any indication of who you're tagging in that reply

**Comment by dimdenGD** [comment]
You can unmention people with "@" button 
![image](https://github.com/dimdenGD/OldTwitter/assets/26517362/48f4f49f-d945-41ad-80cb-52265a04f20e)

**Comment by TheAgamer554** [comment]
oh, sorry about that, it didn't look that intuitive, but thanks for clarifying
