### ISSUE TITLE
Dependency: Internal error. (131) when visiting own profile

### ISSUE THREAD

**Issue by thepwrtank18** [dimdenGD/OldTwitter#594]
**Describe the bug**
When trying to visit your own file, you just see "Dependency: Internal error. (131)".

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/57580668/e035dbb6-c05b-424c-8ac5-36d25024cc57)
![image](https://github.com/dimdenGD/OldTwitter/assets/57580668/37e03995-aa39-40a0-a41e-e5423aaa0eae)

**Browser**
Firefox Developer Edition 120.0b6 (64-bit)

**Links**
Link to profile/tweet or other page where bug happens.

**OldTwitter version**
v1.8.1.4

**Comment by dimdenGD** [comment]
Server error

**Comment by Unikitty185** [comment]
I've had that since the day before yesterday its still happening

**Comment by ericpa06** [comment]
Still happening in some occasions. I only use twitter to check some profiles, and when I visit a profile too much, it starts giving this error, not on all profiles but rather just the one I visited the most. My theory is that twitter implements some measure to avoid scraping, but it only deploy such measure when it thinks you visit a profile “too much”. It might be a little tricky to replicate, but maybe selecting some profile and put a tab to reload during a given amount of time would trigger it.
