### ISSUE TITLE
Make grandfathered GIF profile pictures animated on profile page

### ISSUE THREAD

**Issue by thepwrtank18** [dimdenGD/OldTwitter#597]
An example of a grandfathered GIF pfp would be at https://twitter.com/PRguitarman

![image](https://github.com/dimdenGD/OldTwitter/assets/57580668/df227cfc-50cf-4fd4-b0fe-112aeb553f88)

![image](https://github.com/dimdenGD/OldTwitter/assets/57580668/261a72f1-a56d-4609-b9a1-b8b0e340b6d2) (pretend the pfp is moving)

**Comment by dimdenGD** [comment]
It just shows what twitter gives, and it doesnt return gif for bigger image
