### ISSUE TITLE
How long has it been since mobile.twitter.com redirects to twitter.com?

### ISSUE THREAD

**Issue by HastagGuigui** [dimdenGD/OldTwitter#60]
Hang on, I pressed enter too early...

**Comment by dimdenGD** [comment]
What?

**Comment by HastagGuigui** [comment]
So, I tried opening mobile.twitter.com, and it just autoredirects to twitter.com (Firefox 112.0, if needed)

**Comment by dimdenGD** [comment]
Doesn't happen to me, I'm on Chrome

**Comment by HastagGuigui** [comment]
Hang on, let me record

**Comment by HastagGuigui** [comment]
https://user-images.githubusercontent.com/47950669/233739217-35a45d5f-0fd4-4364-ac0d-6ee0efe95ebc.mp4

**Comment by QueenKit** [comment]
> Doesn't happen to me, I'm on Chrome

The redirect is also happening to me, and I'm on Chrome too.

**Comment by HastagGuigui** [comment]
I guess they want the mobile side of twitter to *stay* in the app, but I guess it breaks that button in OldTwitter...

**Comment by dimdenGD** [comment]
Started happening to me, will see if possible to fix

**Comment by dimdenGD** [comment]
I've added new way of viewing new Twitter, be patient for update release on stores

**Comment by HastagGuigui** [comment]
Alright, thanks!
