### ISSUE TITLE
Youtube embeds don't work

### ISSUE THREAD

**Issue by ruben1PvP** [dimdenGD/OldTwitter#604]
**Describe the bug**
The title says it all. I have a "The content is blocked. Contact the site owner to fix the issue" message instead of the embed. I need to clarify that this happened after I switched to Brave. I've never had this problem on Firefox. It also appeared to solved itself after I turned off "Disable personalized trends", but it came back.

**Screenshots**
![Embed with the extension on](https://github.com/dimdenGD/OldTwitter/assets/73245443/8d8eb36e-81c9-4d40-b72b-e3c223811e31)
![Embed with the extension off](https://github.com/dimdenGD/OldTwitter/assets/73245443/0765db7d-bcdd-446d-b4f5-eebd562d1576)

**Browser**
Brave v1.60.118

**Links**
https://twitter.com/endermanch

**OldTwitter version**
v1.8.1.4

**Comment by dimdenGD** [comment]
This looks like some sort of blocking on Brave. Nothing to be done

**Comment by ruben1PvP** [comment]
> This looks like some sort of blocking on Brave. Nothing to be done

It is not Brave's fault because if I disable the Extension the embed works.
