### ISSUE TITLE
Cant change the font. it's always times new roman.

### ISSUE THREAD

**Issue by nyathea** [dimdenGD/OldTwitter#606]
**Describe the bug**
The font is always set to times new roman and i cant change it. im using arch linux.

**Browser**
Firefox 119.0.1

**OldTwitter version**
v1.8.1.4

**Comment by dimdenGD** [comment]
Choosing any font in list always results to times new roman?

**Comment by flanmoder** [comment]
> Choosing any font in list always results to times new roman?

Yes, it can't change the font at all

**Comment by TorutheRedFox** [comment]
you sure that you have the fonts you're changing it to installed? if they're not installed, the browser or system will use a fallback font

**Comment by SneakySnake04** [comment]
> works fine for me, probably arch linux issue

on Win11 23H2, problem appeared for me recently as well

**Comment by flanmoder** [comment]
i got it fixed. changed the default font in firefox settings
