### ISSUE TITLE
"Some tweets couldn't be loaded due to errors."

### ISSUE THREAD

**Issue by carinavljko** [dimdenGD/OldTwitter#61]
TypeError: Cannot read properties of undefined (reading ’id_str’) at appendTweet (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/scripts/helpers.js:1015:39) at renderTimeline (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/layouts/profile/script.js:982:63) at updateTimeline (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/layouts/profile/script.js:328:5) at undefined (OldTwitter v1.6.8)

I just clicked back to my profile.

I expected tweets to show?

This was on my private account, so I'm not willing to show my profile.

Opera GX LVL 4 (core: 97.0.4719.84)

**Comment by dimdenGD** [comment]
This error happens when tweet doesnt have user data, I can't fix it without being able to reproduce it though
