### ISSUE TITLE
Edit circles

### ISSUE THREAD

**Issue by qqwik** [dimdenGD/OldTwitter#617]
You can't create new circle tweets anymore, I understand, but replying to old threads still works so the circle functionality is still fine.
Could it be possible to add a feature to add/remove people from circles still? I coulnd't find the option anywhere.

**Comment by dimdenGD** [comment]
Will be back in new version, for now you can press F12, go to Console tab and paste `document.getElementById(’new-tweet-audience-input’).hidden = false;` and it'll be back
