### ISSUE TITLE
Do not completely reset timeline after a few hours!

### ISSUE THREAD

**Issue by iiv3** [dimdenGD/OldTwitter#628]
**Describe the bug**

Commit 6b06ec4e393d33403365654e1c8549e64a6d5e8e introduces a new behavior, if you try to 'load new tweets' after 5 hours, it would clear up the whole timeline and would only load the first page.

It goes directly against how I use twitter. I'm checking it just a few times a day and I would like to resume reading from the last tweet read, as evident from my feature request #506 .
If I want to reset my timeline, I can always refresh or press the "Home" button.

Please, if you want to limit the amount of tweets loaded at once, then do that. Aka, load the tweets from the next +4 hours after the last/current tweet.

If you can't do that, then at very least set the time to 24 or 12 hours...
One's supposed to have at least 8 hours of sleep without having to tweet.

**OldTwitter version**
Current git (1.8.1.7).

**Comment by dimdenGD** [comment]
the purpose of this feature is that if you didnt click this button for more than 5 hours it almost definitely doesn't have up-to-date info and has big blanks, not sure how this makes you lose tweet you've read since you have to scroll to top to click it anyway
