### ISSUE TITLE
Favourites not loading

### ISSUE THREAD

**Issue by ewanmckinlay6** [dimdenGD/OldTwitter#63]
**Describe the bug**
The favourites section does not load.

**To Reproduce**
Go to your profile, then click on "Favourites".

**Expected behavior**
Your favourited Tweets are supposed to show up.

**Screenshots**
![image](https://user-images.githubusercontent.com/86389939/234410986-8c0502a2-c36a-4e63-a7bd-5aa852d17340.png)

**Browser**
Google Chrome, version 112.0.5615.138 (Official Build) (64-bit)

**Comment by dimdenGD** [comment]
Link to profile? Or screenshot of console

**Comment by ewanmckinlay6** [comment]
> Link to profile? Or screenshot of console

https://twitter.com/2huPosting

**Comment by dimdenGD** [comment]
Fixed, please wait until update release (might take a week)
