### ISSUE TITLE
Please, restore the functionality to both select tweet text and open tweets clicking on the tweet text.

### ISSUE THREAD

**Issue by iiv3** [dimdenGD/OldTwitter#630]
**Describe the bug**
Commit 998a3cb249d4855bff8015288bfc33f722fb2495 fixes issue #629 , but it does more. It also adds more code to deliberately remove the new functionality introduced explicitly by commit 83c90b54cb0308815b44fd4ca29f5f21353f70f8 aka "Clicking on the text of the tweet (or other "deadzones") will now  properly open that tweet."

Basically the new functionality allowed text to be selected freely or to open tweets when clicking the same text. A feature that has been explicitly requested.

There is absolutely no reason to remove that functionality.
Unless you want to make your users angry and to alienate code contributors.

Please revert the code that handles "tweet-body-text-span".

**OldTwitter version**
Current git (1.8.1.8).

**Comment by dimdenGD** [comment]
this was a bug i didn't notice, not opening tweet on text click is correct behavior
without it selecting text without opening tweet is impossible and extensions that require you to click on text (like yomichan) won't work without always having to open tweets

**Comment by iiv3** [comment]
"without it selecting text without opening tweet is impossible"
The whole point is that this code implements exactly that. It does allow selection of text without opening a tweet. Have you even tried it before crippling it?

**Comment by dimdenGD** [comment]
it doesn't work, when i click on text twice i want to be able to get automatically all text selected not to open tweet

**Comment by iiv3** [comment]
Doesn't the extension have a mode where it selects/translates a word just by hovering the mouse over it?

Anyway, at very least make that optional. Most of the users don't have your very specific needs. And it is seriously crippling, especially on mobile.

**Comment by dimdenGD** [comment]
its not crippling at all, i use it on both computer and mobile and everything is fine because theres always lot of space to press on. the extension on pc works on hover but on phone you have to press on text

**Comment by iiv3** [comment]
Just make it an option.

**Comment by dimdenGD** [comment]
i only add things i use myself, if you need it you're free to contribute though

**Comment by iiv3** [comment]
You just crippled @ephemeralViolette contribution and you ask for more contributions?
