### ISSUE TITLE
Might have trouble with posting Circle Tweets.

### ISSUE THREAD

**Issue by MysticManiaZone** [dimdenGD/OldTwitter#644]
Whenever I try to post a Circle Tweet, it says: "Authorization: User is not permitted to create this Twitter Circle tweet. (459)"

![coicle](https://github.com/dimdenGD/OldTwitter/assets/154051487/d8b2f5ae-0a8f-4e95-8d43-db6cca7e3216)
 
 I'm not sure if there is anything I can do to fix this, to continue using Circles. Thank you.

**Comment by dimdenGD** [comment]
There's nothing to be done, you can reply to older circle tweets to continue posting in circle though. This thing is left here only for you to still be able to manage circle members

**Comment by MysticManiaZone** [comment]
I really appreciate it. Thank you!
