### ISSUE TITLE
Site is COMPLETELY BROKEN.

### ISSUE THREAD

**Issue by ewanmckinlay6** [dimdenGD/OldTwitter#65]
**Describe the bug**
The CSS is completely broken. It's mixed with new Twitter.

**Screenshots**
![image](https://user-images.githubusercontent.com/86389939/234424124-7a925df5-ffca-499a-994b-ad17f40f7771.png)
![image](https://user-images.githubusercontent.com/86389939/234424352-76a3b84f-24b5-4cc3-b319-218d9b4a210b.png)

**Browser**
Google Chrome, version 112.0.5615.138 (Official Build) (64-bit)

**Comment by dimdenGD** [comment]
What about now

**Comment by ewanmckinlay6** [comment]
![image](https://user-images.githubusercontent.com/86389939/234426592-56214a1e-1bbb-431e-9389-ba018031d55f.png)
Looks a lot better.
