### ISSUE TITLE
Added missing Tagalog translations

### ISSUE THREAD

**Issue by paintthetownredd** [dimdenGD/OldTwitter#657]
Added the missing translations for tagalog :}} My handle is @cheesee_its

[tl.zip](https://github.com/dimdenGD/OldTwitter/files/13791153/tl.zip)

**Comment by conc1erge** [comment]
i made work in progress fork at [conc1erge/OldTwitter](https://github.com/conc1erge/OldTwitter) with some changes i think fit well
on top of that, i'm working with issue's OP adding more translations!

**Comment by conc1erge** [comment]
#668 <- PR'd and is done, waiting for approval
