### ISSUE TITLE
Option to change country/location for trends

### ISSUE THREAD

**Issue by kokoropaint** [dimdenGD/OldTwitter#658]
This is an option available in the normal Twitter layout (on the [explore page](https://twitter.com/explore?newtwitter=true).) Changing it on the modern explore page affects your trends in the OldTwitter layout, but you should probably be able to change this setting without needing to switch.

(Excited for Whispy, btw! you're doing great work dimden)

**Comment by dimdenGD** [comment]
Such option won't be added because I don't add things that change your account settings, since calling these APIs is pretty risky
