### ISSUE TITLE
Extension CSS has been nuked.

### ISSUE THREAD

**Issue by ewanmckinlay6** [dimdenGD/OldTwitter#66]
**Describe the bug**
The extension's CSS has been mixed with New Twitter.

**To Reproduce**
Go to any page on OldTwitter.

**Expected behavior**
Nothing from New Twitter should show up.

**Screenshots**
![image](https://user-images.githubusercontent.com/86389939/234426175-4124d2b0-1f0c-4387-9113-1f269e279bdd.png)

**Browser**
Google Chrome, version 112.0.5615.138 (Official Build) (64-bit)

**Comment by dimdenGD** [comment]
duplicate of #65
