### ISSUE TITLE
Image layouts

### ISSUE THREAD

**Issue by Vulpix037** [dimdenGD/OldTwitter#661]
For some reason, tweets with three attached images show the images side by side in a 1x3 layout instead of one large thumbnail at the left and two smaller thumbnails at the right in both the Android app and the main site. Is this intentional?

![image](https://github.com/dimdenGD/OldTwitter/assets/56650249/551a98bf-57ec-4c0c-b315-95d6aa126728)

**Comment by dimdenGD** [comment]
it's intentional
