### ISSUE TITLE
Media tab does not appear

### ISSUE THREAD

**Issue by Jalezen2** [dimdenGD/OldTwitter#669]
**Describe the bug**
Media tab appears blank

**Screenshots**
https://file.garden/ZJ2iO-Hgu2LVKUb5/Example.png 
<img width="726" alt="Example" src="https://github.com/dimdenGD/OldTwitter/assets/81977496/95a5d1a8-ca6a-48f9-a7f5-cc277f968693">

**Browser**
Brave. Tested on Chrome too, still does not appear

**Links**
Happens on every profile. https://twitter.com/d1mden/media as an example though

**OldTwitter version**
v1.8.1.3. Apparently the last version is 1.8.1.9 but i don't see it in the releases tab?

**Comment by dimdenGD** [comment]
updated file in release, would be probably better to just use version from chrome web store though
