### ISSUE TITLE
Support for Incognito

### ISSUE THREAD

**Issue by AdamSaketume26** [dimdenGD/OldTwitter#675]
I used the extension for the first time and I had problem with using when also being logged in on Twitter with incognito on chrome. I see in #200 you said it's because the cache is shared. Can we you use two separate cache one for incognito and one for regular?

https://developer.chrome.com/docs/extensions/reference/api/tabs#type-Tab
There is tab property "incognito" to see Whether the tab is in an incognito window.

Using this can't you cache two different data for incognito and not incognito twitter accounts? and if it is incognito if all incognito tabs/windows are closed also purge the incognito cache.

**Comment by dimdenGD** [comment]
impossible
