### ISSUE TITLE
add a more convenient Download Button

### ISSUE THREAD

**Issue by xyzxye** [dimdenGD/OldTwitter#678]
first, thank you for creating this wonderful extension !

could you make a direct Download Button within the tweet?
like, from this
![origin](https://github.com/dimdenGD/OldTwitter/assets/71118632/ffce47c2-4a00-45fb-9b12-55c5fe75e641)

to this
![after](https://github.com/dimdenGD/OldTwitter/assets/71118632/fa4fcfb5-23e4-4c53-9b5e-a0315ea9575f)

this feature will make downloading more convenient

**Comment by dimdenGD** [comment]
why not just right click on video and save

**Comment by xyzxye** [comment]
the download button makes it more convenient to Download Multiple Images, name them in a more organized manner and download it in original size

although there are some scripts that can do this, but they are not compatible with this extension......
