### ISSUE TITLE
Not showing new bookmarks

### ISSUE THREAD

**Issue by carinavljko** [dimdenGD/OldTwitter#68]
**Describe the bug**
Unable to view new bookmarks

**To Reproduce**
Add a ton of bookmarks.

**Expected behavior**
I expected more recent bookmarks to appear

**Screenshots**
![image](https://user-images.githubusercontent.com/79905640/235344056-20d5d709-7d3c-4b00-be9e-ae4fc94d6d2f.png)
![image](https://user-images.githubusercontent.com/79905640/235344069-6f15e154-0184-4e9b-a787-3ccde6850aa2.png)

**Browser**
Opera GX LVL 4 (core: 97.0.4719.89)

**Comment by dimdenGD** [comment]
This was fixed already, update your extension
