### ISSUE TITLE
Add Direct Link to Settings Page

### ISSUE THREAD

**Issue by attheshow** [dimdenGD/OldTwitter#680]
I apologize if this has already been covered. Is there any way we could add a link to the Settings page via the right sidebar? I'm new to the extension so I still find that I need to change some settings almost daily. It would be nice to have a quick link to it. Thanks!

**Comment by dimdenGD** [comment]
i think user avatar menu is already quick enough

**Comment by attheshow** [comment]
Oh wow! I had no idea there was a menu that would appear when you click on your profile picture. That wasn't intuitive! 😊🏅
