### ISSUE TITLE
Unable To Use Twitter Circle/Not Working

### ISSUE THREAD

**Issue by MonoCycloptic** [dimdenGD/OldTwitter#682]
**Describe the bug**
I know there's still an option to choose the Twitter circle, but It doesn't work for me. When I tried to publish the tweet, a pop up comes up and says the following: "Authorization: User is not permitted to create this Twitter Circle tweet. (459)". I don't know if this is a Patreon only thing, or there's something in that website's code that's preventing me to use it. If there's nothing that it can be done to fix it, then might as well remove it. But I'll miss it so much. :'(
 
**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/158801642/2b8fcd76-9e2a-4749-b4a1-974905d52ef0)
![image](https://github.com/dimdenGD/OldTwitter/assets/158801642/2afe1894-ff7a-47ce-b900-edc88f114a68)

**Browser**
Mozilla Firefox Version 122.0 (64-bit) (It's up to date)

**Links**
https://twitter.com/home

**OldTwitter version**
v1.8.2.0 (last version: 1.8.2.0)

**Comment by dimdenGD** [comment]
It's impossible to create new Circle tweets, the only way is to reply to older tweets made in Circle. This option is there only for managing your Circle members

**Comment by MonoCycloptic** [comment]
> It's impossible to create new Circle tweets, the only way is to reply to older tweets made in Circle. This option is there only for managing your Circle members

Ah, I see. I was a bit confuse why is it still there, but thanks for clarifying it!
