### ISSUE TITLE
"Error setting link color" while attempting to edit and sync custom profile color.

### ISSUE THREAD

**Issue by ishiexe** [dimdenGD/OldTwitter#690]
Attempting to edit link color in my profile and syncing as follows will give the following two error messages:

![chrome_TyZuEN5PTw](https://github.com/dimdenGD/OldTwitter/assets/160997263/3495e8fb-cd50-47aa-94e7-85a9e7708ed3)
![chrome_mzOThc2emk](https://github.com/dimdenGD/OldTwitter/assets/160997263/7793330b-b7d8-47c9-a8e0-3b453bce0b72)
![chrome_VVpHhijQcJ](https://github.com/dimdenGD/OldTwitter/assets/160997263/ac0acd47-5843-4e31-a1a3-9e60012a52d4)

Tested on both Firefox 123.0  and Chrome 122.0.6261.70.
Running OldTwitter version 1.8.2.0.

**Comment by dimdenGD** [comment]
Fixed
