### ISSUE TITLE
Cant sync profile color because of CORS Policy

### ISSUE THREAD

**Issue by LelIllumina** [dimdenGD/OldTwitter#695]
**Describe the bug**
Trying to use link color synchronization throws an error and dosent change colors presistently, i have seen issue  #96 but i am on the latest version and still face this problem (im using libertytunnel to access twitter if that is relevant)

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/121309458/83f8c076-a9fa-4dc9-ab69-48e650ea96f2)
![image](https://github.com/dimdenGD/OldTwitter/assets/121309458/dfa9966d-b416-460f-88f3-67a8661c182d)
![image](https://github.com/dimdenGD/OldTwitter/assets/121309458/f1a50a08-b948-4a5d-8b65-f4a38e4bb61a)

**Browser**
Thorium  AVX2 Version 120.0.6099.235 (Official Build) (64-bit)

**Links**
https://twitter.com/Lel_Illumina (profile page)

**OldTwitter version**
Copypasted:
Running [OldTwitter](https://github.com/dimdenGD/OldTwitter) v1.8.2.1 (last version: 1.8.2.1).

**Comment by dimdenGD** [comment]
Can't reproduce, works fine for me. CORS header is definitely being sent: 
![image](https://github.com/dimdenGD/OldTwitter/assets/26517362/94d645c3-5446-445b-b5de-99cc60d86b50)

**Comment by LelIllumina** [comment]
i get a similar error using vanilla firefox, ill just try again later when i can access twitter normally (without vpn or libertytunnel)

**Comment by LelIllumina** [comment]
switched from liberty tunnel to goodbyedpi and it seems that fixed this
