### ISSUE TITLE
there should be a explore tab

### ISSUE THREAD

**Issue by rekvui** [dimdenGD/OldTwitter#7]
there should be a explore tab, like the one we have currently, together with the home, notifications and dm tab in the navbar. similarly to pic 2
![image](https://user-images.githubusercontent.com/93687310/181390275-d8f634a4-46a1-4f5e-9de0-1e8d843a5994.png)
![image](https://user-images.githubusercontent.com/93687310/181390414-901ba23d-6ead-4c6a-9733-b3a478d92c7a.png)

**Comment by dimdenGD** [comment]
won't be added
