### ISSUE TITLE
Enable direct navigation to suggested search terms using mouse cursor

### ISSUE THREAD

**Issue by ashjaylk** [dimdenGD/OldTwitter#71]
**Description**
When using Twitter search, users are presented with a **list of suggested search terms based on their query**. However, currently, users cannot directly navigate to these suggested search terms using their mouse cursor. Instead, **they must use the arrow keys to move to the desired term and then press enter**. This process can be time-consuming and unintuitive, especially for users who are used to clicking on suggested search terms in other search engines. 

Therefore, **_I am requesting a feature to enable direct navigation to suggested search terms using the mouse cursor_**. This would enable users to simply move their cursor over the desired suggested term and click on it to navigate to the search results for that term.

![image](https://user-images.githubusercontent.com/77319819/236608152-02eaa2d3-1275-436f-bdb3-f80b7e96b18f.png)

**Implementation Details** 

- [x]  Add a new UI element to the search bar that displays the suggested search terms as clickable links.
- [x]  When a user hovers their mouse cursor over one of the suggested search terms, the link should be highlighted to indicate that it is clickable.
- [ ]  When the user clicks on one of the suggested search terms, the search results for that term should be displayed.

**Impact**
This feature would improve the user experience of Twitter search by making it more intuitive and user-friendly. It would also save users time by eliminating the need to use arrow keys to navigate to suggested search terms.

**Comment by dimdenGD** [comment]
It's already a thing? I can click on results fine

**Comment by ashjaylk** [comment]
it ain't working for me. Ad blocker and Edge security are off, I even did a hard refresh, but no luck.

**Comment by dimdenGD** [comment]
Just checked on Edge, works fine
