### ISSUE TITLE
List Of Features Requested

### ISSUE THREAD

**Issue by theanthonydavenport** [dimdenGD/OldTwitter#714]
Please do not request multiple big features at once, break them down into multiple issues.

Clicking on view count does nothing
It should bring up the analytics for the tweet, and I'm hoping the feature will be implemented.
(https://github.com/dimdenGD/OldTwitter/assets/99144439/e90d7396-8a5f-466b-a266-047c7a334017)

Essentially, I'd like to be able to see the analytics of a tweet/reply that I've posted.
<img width="595" alt="Screenshot 2024-03-26 at 11 25 35" src="https://github.com/dimdenGD/OldTwitter/assets/99144439/807662f5-73fe-48f1-831e-6e99abb924cd">

No option to report a tweet
(This is something we'd all hope to be implemented, as it's an essential feature)

Add the option to save the tweet as an image (With Source Label)
(Saving an Tweet on OldTwitter as a photo)
(Something I That I Thought Was Cool)
(https://github.com/dimdenGD/OldTwitter/assets/99144439/bd7d4602-7001-4697-baf8-d36dcdf89de3)

Settings Option to turn on and off a Community Notes Tab
<img width="226" alt="Screenshot 2024-03-26 at 11 30 41" src="https://github.com/dimdenGD/OldTwitter/assets/99144439/1c02b1d6-ff06-476d-b837-0b472f8cb6b4">

**Comment by dimdenGD** [comment]
Please do not request multiple big features at once, break them down into multiple issues.

**Comment by theanthonydavenport** [comment]
Understood, I’ll put the features in individual issues.
