### ISSUE TITLE
Advanced search doesn't show up

### ISSUE THREAD

**Issue by lbr5539** [dimdenGD/OldTwitter#724]
**Describe the bug**
The advanced search page [(https://twitter.com/search-advanced)](https://twitter.com/search-advanced) can't be acessed, showing a "User was not found." message instead. Possibly make it apply the newtwitter=true flag automatically when opening it.

**OldTwitter version**
1.8.2.4

**Comment by zbalkan** [comment]
The page https://x.com/search-advanced fails to be accessed. Basically an empty page appears. Should I create another issue?
