### ISSUE TITLE
page not loading in OTL in 1.8.3

### ISSUE THREAD

**Issue by Dominatoah** [dimdenGD/OldTwitter#725]
Hi, this is my first GitHub experience and I hope I can provide useful stuff. I have no clue about programming so ask what you want to know!

I wanted to use OTL like every other day but now it only shows a white page.
New install of OTL didn't do the trick. X works normal without the extension.
OTD 3.5.4 is working fine.

Brave Browser: Version 1.64.113 Chromium: 123.0.6312.86 (Offizieller Build) (64-Bit)
OTL: 1.8.3

Console while loading:

![Screenshot 2024-04-01 105559](https://github.com/dimdenGD/OldTwitter/assets/165649556/522d23d7-9c30-4b82-a286-796268cbac6e)

**Comment by ayaaop** [comment]
same

**Comment by ayaaop** [comment]
Duplicate of #723

**Comment by Dominatoah** [comment]
I am a noob, you could've mentioned that there is a new version for chromium as well but thanks

it's working now with 1.8.3.5
