### ISSUE TITLE
Blank page on Brave browser

### ISSUE THREAD

**Issue by 12d3** [dimdenGD/OldTwitter#728]
browser page loads blank, or rather doesn't load at all
i noticed someone else mention the same issue happening on another browser but i figured i'd mention its also occurring on Brave
disabling the extension fixes the issue

[image](https://github.com/dimdenGD/OldTwitter/assets/69762568/8b3569e4-af84-44c7-9f0b-b406b74ac6e0)

Brave
Version 1.64.113 Chromium: 123.0.6312.86 (Official Build) (64-bit)

**Comment by dimdenGD** [comment]
update extension

**Comment by 12d3** [comment]
updating fixed the issue at the time, the problem has returned already today, nothing on twitter will load unless i deactivate the extension

**Comment by 12d3** [comment]
> update extension

updating fixed the issue at the time, the problem has returned already today, nothing on twitter will load unless i deactivate the extension
