### ISSUE TITLE
Add legacy verified checkmarks

### ISSUE THREAD

**Issue by highesttt** [dimdenGD/OldTwitter#73]
Add an option to see the legacy verified people using this database https://github.com/thansen0/verified_twitters.
(or you can make it so the extension works with old twitter: https://github.com/chromestone/OriginalBirds)

**Comment by dimdenGD** [comment]
Would be nice but that database is really huge, i'm not sure how it'll impact perfomance since you'll need to search that file on every single tweet / user component

**Comment by highesttt** [comment]
What do you think about trying to make the addon work with your custom client 🤔
Would that be a plausible option?

**Comment by dimdenGD** [comment]
I don't think it's possible, it works on new twitter while oldtwitter is entirely different client with different layout

**Comment by highesttt** [comment]
Ah shit.. I had hopes because it works with goodtwitter2
