### ISSUE TITLE
Ability to report users from the context menu (three dots)

### ISSUE THREAD

**Issue by iansquenet** [dimdenGD/OldTwitter#732]

**Comment by iansquenet** [comment]
How come? As it was an actual feature and I find myself making a lot of reports, so it's annoying to always select the New Twitter button.

![image](https://github.com/dimdenGD/OldTwitter/assets/36297463/c9f8d77b-3ea5-4a29-8f69-9999fdebfeac)
![tw-status-r3](https://github.com/dimdenGD/OldTwitter/assets/36297463/0d825aae-4061-4afa-9bc6-adc6e033d3cd)
![tw-status-r7](https://github.com/dimdenGD/OldTwitter/assets/36297463/1c6b4413-0b67-40a0-b5fd-3824bb5f4c8d)

**Comment by dimdenGD** [comment]
It's impossible to test this properly and it's a critical API

**Comment by iansquenet** [comment]
Fair enough. Do keep in mind though.
