### ISSUE TITLE
Thinks I'm Not Following Anyone

### ISSUE THREAD

**Issue by benserwa** [dimdenGD/OldTwitter#736]
**Describe the bug**
While I'm reading Twitter with the extension on, the page will shift back to the top and I'll get a message saying "You're not following anyone so there's no tweets found! Change your timeline type to 'Algorithmical' in OldTwitter settings." However, this is not true. Also, different posts seem to be loaded after this happens. Perhaps older ones? Not sure.

**Browser**
Microsoft Edge Version 123.0.2420.65 (Official build) (64-bit)

**OldTwitter version**
v1.8.2.0

**Comment by dimdenGD** [comment]
uninstall extension and install from chrome web store instead of edge store to receive last update
