### ISSUE TITLE
Question about custom fonts

### ISSUE THREAD

**Issue by highesttt** [dimdenGD/OldTwitter#74]
How does custom fonts work? I've tried adding a custom font with the correct name but it doesn't work for every font.
I've tried:
Samsung Sans [FAIL]
Script Regular [FAIL]
Elephant [SUCCESS]
System Bod [FAIL]
Terminal [FAIL]
Lucida Fax [SUCCESS]

I originally thought it didn't work with fonts with a space in them, but after trying Terminal, which failed, and Lucida Fax, which worked, it leaves me puzzled..

*Yes, all fonts are installed on my PC and are named that way inside Fonts*

**Comment by dimdenGD** [comment]
It uses CSS's `font-family` option. I can't really tell why exactly some fonts don't work for you, browser can simply not support that local font for some reason, or there can be some different font family name for it
