### ISSUE TITLE
Pages Not Loaded due to errors

### ISSUE THREAD

**Issue by JSwizzle86** [dimdenGD/OldTwitter#740]
**Describe the bug**
"TypeError: Cannot read properties of undefined (reading ’replace’) at escapeHTML (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/scripts/helpers.js:385:10) at index_map.<computed> (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/scripts/helpers.js:467:33) at renderTweetBodyHTML (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/scripts/helpers.js:508:23) at appendTweet (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/scripts/helpers.js:1855:132) at renderTimeline (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/layouts/profile/script.js:1758:23) at 1778497810003874078 (OldTwitter v1.8.3.7)"

**Screenshots**
https://cdn.discordapp.com/attachments/316252129574780928/1231116486647480360/image_2024-04-20_00-37-11.png?ex=6624a613&is=66235493&hm=5aa3bc41cdb6dde2559f81853b58a1f1e1c243fe19290dd3369f8c991c11a0d5&

**Browser**
Chrome

**Links**
[Link to profile/tweet or other page where bug happens.](https://twitter.com/Mango_JuiceBara)

**OldTwitter version**
OldTwitter v1.8.3.7

**Comment by dimdenGD** [comment]
Should be fixed (wait for update)
