### ISSUE TITLE
"Some tweets couldn't be loaded due to errors."

### ISSUE THREAD

**Issue by Tekk236** [dimdenGD/OldTwitter#745]
**Describe the bug**
Unsure, bug appears whenever I reload OldTwitter and gives no particular culprit.

TypeError: sizeFunctions[t.extended_entities.media.length] is not a function or its return value is not iterable at renderMedia (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/scripts/helpers.js:1375:73) at appendTweet (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/scripts/helpers.js:1873:27) at async renderTimeline (chrome-extension://jgejdcdoeeabklepnkdbglgccjpdgpmf/layouts/home/script.js:332:17) at 1782560714668060858 (OldTwitter v1.8.3.7)

**Screenshots**
[image](https://github.com/dimdenGD/OldTwitter/assets/167828205/1acf96e7-8779-4a3b-ae23-9e3622604d35)

**Browser**
Google Chrome Version 124.0.6367.61 (Official Build) (64-bit)

**Links**
On my https://twitter.com/home page.

**OldTwitter version**
OldTwitter v1.8.3.7

**Comment by eaocto** [comment]
It also happened to me today, albeit a little bit different. In my case a retweet shows up as 2011 style retweet with "RT: ...." full with its media too just like a normal modern tweet. Then when opening the account it throws the same error. With the following error:

`escapeHTML@moz-extension://931ff9fe-2635-41b2-80f2-b64a7beea112/scripts/helpers.js:384:5 renderTweetBodyHTML/</index_map[url.indices[0]]<@moz-extension://931ff9fe-2635-41b2-80f2-b64a7beea112/scripts/helpers.js:467:33 renderTweetBodyHTML@moz-extension://931ff9fe-2635-41b2-80f2-b64a7beea112/scripts/helpers.js:508:23 appendTweet@moz-extension://931ff9fe-2635-41b2-80f2-b64a7beea112/scripts/helpers.js:1855:132 renderTimeline@moz-extension://931ff9fe-2635-41b2-80f2-b64a7beea112/layouts/profile/script.js:1758:23 at 1777917717535948966 (OldTwitter v1.8.3.7) `

At the left sidebar where there're media thumbnail, it shows all media from this weird retweet. The tweet tab also shows this weird retweet. But at the media tab it properly show only this accounts tweet.
