### ISSUE TITLE
Unable to manually install on Firefox Dev Edition

### ISSUE THREAD

**Issue by Shinjar** [dimdenGD/OldTwitter#753]
**Describe the bug**
I'm unable to install "OldTwitterFirefox.zip", either from your latest release or the automated pack extension builds (attempted several of the latest of these) on the latest Firefox Dev edition, with xpinstall.signatures.required set to "false".

The error that comes up when attempting to install says the following:
"This add-on could not be installed because it appears to be corrupt."

This is unlike your **OldTweetDeck**Firefox.zip which installs and works flawlessly.

This behaviour also occurs on a clean install of Firefox Dev on a VM.

**Screenshots**
If applicable, add screenshots or video to help explain your problem.
![image](https://github.com/dimdenGD/OldTwitter/assets/71134132/bd784a47-1106-4737-a4dc-f0664b5823e4)

**Browser**
Firefox Dev 126.0b6 (64-bit)

**OldTwitter version**
Several latest versions. (1.8.3.5 & 1.8.3.9)

**Comment by Kusoneko** [comment]
I can confirm this issue. It can be installed successfully by going to `about:debugging#/runtime/this-firefox` and adding it as a temporary add-on, however temporary add-on means close Firefox Developer Edition and restart it and it's gone.

I can't however figure out why it refuses to install it, all I find about that error is that you need to have an id in some browser-specific-settings option in the manifest.json (which this extension seems to have) and have the xpiinstall.signatures.required config flag set to false (which it is) while using either an unbranded, beta or developer edition of firefox.

**Comment by Shinjar** [comment]
Can confirm the "id" line is indeed all that was required, nice work @Kusoneko :)

I don't know the ins and outs of github but I hope dimden somehow sees your solution and the fix can be implemented when time is ample and the day serene.

![nynfall](https://github.com/dimdenGD/OldTwitter/assets/71134132/0cd5e756-cc81-408e-9488-9d956e042456)

**Comment by dimdenGD** [comment]
Now Github versions generate extension ID
