### ISSUE TITLE
Did the plug-in author take the initiative to remove the plug-in from Firefox or did Firefox take the initiative to remove the plug-in?

### ISSUE THREAD

**Issue by WOLFRAZOR** [dimdenGD/OldTwitter#755]
When I wanted to install this plug-in, I found the following prompt on the Firefox store website:

**_If you’ve followed a link from another site for an extension or theme, that item is no longer available. This could be because:

    The developer removed it. Developers commonly do this because they no longer support the extension or theme, or have replaced it.
    Mozilla removed it. This can happen when issues are found during the review of the extension or theme, or the extension or theme has been abusing the terms and conditions for addons.mozilla.org. The developer has the opportunity to resolve the issues and make the add-on available again._**

So is it the first case or the second case? I don't want to be forced to change browsers because of using this plug-in (since Google is about to implement the manifest v3 standard, the browser plug-ins I use will be completely broken by this standard. So I can only use Firefox)

Hope to get a reply, thank you.

**Comment by WOLFRAZOR** [comment]
I make sure my Firefox is the international version (not the Beijing Mozilla customized version). I've ruled out network issues.
![截屏2024-04-28 下午5 24 32](https://github.com/dimdenGD/OldTwitter/assets/93996192/82fbecd7-75c8-4afb-81bb-2d7ee9192067)

**Comment by dimdenGD** [comment]
Mozilla removed it

**Comment by Saberleo456** [comment]
Many other Chromium based browsers have already made changes to continue the old manifest version, such as Vivaldi. I can confirm that OldTwitter works on Vivaldi as well.

**Comment by clover-yan** [comment]
However, how to keep using the extension in Firefox?

Plus, why is the issue closed?

**Comment by WOLFRAZOR** [comment]
> However, how to keep using the extension in Firefox?
> 
> Plus, why is the issue closed?

Because the author has already answered it (please open the "Discussion" interface). I asked this question because this interface was not open (I saw it later, so I marked this question as "closed").

If you installed the add-on on Firefox before it was removed, please do not do anything. If you want to continue using the plug-in after it is removed, you need to switch Firefox from the official version channel to any one of the three channels: ESR, Nightly, and DEV. Or switch to browsers that are based on Chromium but still support manifest V2.

**Comment by WOLFRAZOR** [comment]
> However, how to keep using the extension in Firefox?
> 
> Plus, why is the issue closed?

Regarding the countdown to the activation of V3, if the browser you are using has clearly "no longer supports V2", and your browser plug-in will be wiped out due to the new standard. You need to migrate as soon as possible. (The UBlock Origin, Tamper Monkey, and CanvasBlocker I use will be wiped out by the new standard) (Firefox retains support for V2 while also adding support for V3)

**Comment by dimdenGD** [comment]
OldTwitter supports Manifest v3, it should work on any Chromium browsers
