### ISSUE TITLE
getting "This request requires a matching csrf cookie and header." every time i try to do something on twitter after switching to a different account

### ISSUE THREAD

**Issue by gage64** [dimdenGD/OldTwitter#76]
i keep getting this error that says "This request requires a matching csrf cookie and header." whenever i try to do literally anything (i.e. interacting with a tweet [liking/retweeting/etc.], clicking on a profile, trying to tweet). it only happened after i swapped to an alt account.
![image](https://github.com/dimdenGD/OldTwitter/assets/28501503/270282eb-e753-4603-a81f-7bab0f31d04c)

it also removed the ability to swap accounts (it didn't sign me out of them though)
![image](https://github.com/dimdenGD/OldTwitter/assets/28501503/07508883-f456-418b-a1b5-b42327d0c214)

**Comment by dimdenGD** [comment]
Fixed in https://github.com/dimdenGD/OldTwitter/commit/b72152b550cb4f4ecafaa7c78aaf36d8ec2884e0. It can take a while before update is released to stores.
