### ISSUE TITLE
Unable to manually install Chrome extension

### ISSUE THREAD

**Issue by Andromander** [dimdenGD/OldTwitter#763]
Since Twitter's merge, the extension installed via the Chrome Web Store has broken - it's still version 1.8.3.8.

However, when attempting to install unpacked, Chrome cannot install it because the manifest file is missing or unreadable. I can see the json clear as day and I can't get any more info from that.

Not really sure which question is best to ask here. Is there something blocking 1.8.3.9 from showing up in the Chrome Web Store? Otherwise, is there something I'm not doing right with the manual install?

**Comment by dimdenGD** [comment]
You're definitely picking the wrong folder when trying to install unpacked extension if you get that error. I'll upload new version to Github tho

**Comment by Andromander** [comment]
ok so I just found out only the sandbox html got extracted from the zip

**Comment by Andromander** [comment]
Figured I should have gotten back to this: the 1.8.4 zip install worked after properly extracting the files.
