### ISSUE TITLE
Cannot post media

### ISSUE THREAD

**Issue by Inuko-kun** [dimdenGD/OldTwitter#764]
**Describe the bug**
Can't post tweet with media, error popup says "X.com says: Could not authenticate you.", if it makes any difference, I'm in a country that has twitter.com redirected to x.com

**Screenshots**
https://imgur.com/a/GG13KQj

**Browser**
Edge Version 124.0.2478.105 (Official build) (64-bit)

**Links**
Any page

**OldTwitter version**
v1.8.4

**Comment by dimdenGD** [comment]
Fixed
