### ISSUE TITLE
Can't quote tweet on OldTwitter.

### ISSUE THREAD

**Issue by EZ2Alpa** [dimdenGD/OldTwitter#766]
**Describe the bug**
When I send a quote tweet on OldTwitter, I get “BadRequest: attachment_url parameter is invalid. (44)” and cannot quote tweet.
I am using the latest version.
I was able to send it successfully on the official app.

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/139020260/be347f2a-7a67-4e9f-9983-5cd5566c2e36)
![image](https://github.com/dimdenGD/OldTwitter/assets/139020260/21d78f99-5445-439f-a887-6f27921d3919)

**Browser**
Google Chrome 124.0.6367.208

**Links**
(All sites where you can quote and tweet)

**OldTwitter version**
v1.8.4.1

**Comment by Asteriadeath** [comment]
tried to see if this happens on ubuntu, this is a real bug.


OS: ubuntu 22.04

**Comment by dimdenGD** [comment]
Fixed
