### ISSUE TITLE
some tweets couldn't be loaded due to errors

### ISSUE THREAD

**Issue by JakeREichert1** [dimdenGD/OldTwitter#767]
error code: 
 escapeHTML@moz-extension://c1a262b4-43d9-4fe0-a136-d488d790538e/scripts/helpers.js:384:5 renderTweetBodyHTML/</index_map[url.indices[0]]<@moz-extension://c1a262b4-43d9-4fe0-a136-d488d790538e/scripts/helpers.js:467:33 renderTweetBodyHTML@moz-extension://c1a262b4-43d9-4fe0-a136-d488d790538e/scripts/helpers.js:508:23 appendTweet@moz-extension://c1a262b4-43d9-4fe0-a136-d488d790538e/scripts/helpers.js:1855:132 renderTimeline@moz-extension://c1a262b4-43d9-4fe0-a136-d488d790538e/layouts/profile/script.js:1758:23 at 1789058312551448798 (OldTwitter v1.8.3.7)

**Comment by dimdenGD** [comment]
old version
