### ISSUE TITLE
"People and body" Category in emote picker not openable

### ISSUE THREAD

**Issue by danielah05** [dimdenGD/OldTwitter#77]
**Describe the bug**
The emote picker has 9 categories, all of them are openable besides the "People and body" category

**To Reproduce**
1. Compose a new Tweet
2. Open the Emote Picker
3. Try to open the "People and body" category (The waving hand)

**Expected behavior**
It should open the "People and body" category

**Screenshots**

https://github.com/dimdenGD/OldTwitter/assets/35849198/c938787b-3cdd-46f4-aedb-9a553e5857e8

**Browser**
Waterfox G5.1.8

**Comment by dimdenGD** [comment]
Works fine for me 
![6381bea92bc](https://github.com/dimdenGD/OldTwitter/assets/26517362/5c6397a5-3794-4834-a36a-24457dc95484)

**Comment by danielah05** [comment]
It seems like this bug might be a Firefox based browser only issue (Waterfox is a fork of Firefox for context). I just installed this extension on ungoogled chromium and I can't reproduce this issue on it.

**Comment by dimdenGD** [comment]
Fixed in 1.7.2
