### ISSUE TITLE
Kept being redirected back and forth

### ISSUE THREAD

**Issue by robloxianstudio123** [dimdenGD/OldTwitter#776]
**Describe the bug**
Keeps trying to redirect to x.com, and then back to twitter.com
Creating an infinite loop.

Steps to reproduce:
1. Install the extension
2. Open twitter.com (or x.com if you prefer it that way)
3. See the infinite loop of redirects happen

**Screenshots**

![Untitled](https://github.com/dimdenGD/OldTwitter/assets/148556463/ff51de19-bd8c-42e4-84c4-d2c6ab072d03)
Sorry that in the screenshot that i don't have windows activated

**Browser**
I use Google Chrome, Version 124.0.6367.207 (Official Build) (64-bit)

Might also affect other browsers i guess

**Links**
Link to profile/tweet or other page where bug happens.
twitter.com
x.com

**OldTwitter version**

Had to use the main extension itself, because it's broken, version 1.8.4

**Comment by dimdenGD** [comment]
You need to turn off extension on migration page, let it migrate you and then enable it again

**Comment by robloxianstudio123** [comment]
Okay that worked, This is likely an useless report that i created..
Closing it anyway
