### ISSUE TITLE
OldTwitter not showing its UI

### ISSUE THREAD

**Issue by alvarokrn** [dimdenGD/OldTwitter#777]
**Describe the bug**
It was working correctly, but today it started to fail. I realized that the browser was looping trying to load a twitter url that contains "migrate" as a parameter (I can't remember well) in a blank page. So I reloaded the extension (disable and enable again) and It starts showing the real X user interface instead of OldTwitter.

I've installed the last version and the problem persists. I restarted firefox and the problem persists. I updated Firefox to the last version and the problem persists.

**Screenshots**
![Captura de pantalla 2024-05-17 151757](https://github.com/dimdenGD/OldTwitter/assets/108217204/3c0bd8fd-5ab3-4b6f-8c9d-0c0365137466)
![Captura de pantalla 2024-05-17 151824](https://github.com/dimdenGD/OldTwitter/assets/108217204/645f09f0-2f8b-4bf9-a65b-514d8fc38f08)
![Captura de pantalla 2024-05-17 151830](https://github.com/dimdenGD/OldTwitter/assets/108217204/5ea31c03-1b4b-4f44-aab6-8753c1d2ded7)

**Browser**
125.0.3 (64-bit) and 126.0 (64-bit) (Windows 11)

**Links**
https://twitter.com / https://x.com 

**OldTwitter version**
1.8.3.7

**Comment by dimdenGD** [comment]
1.8.3.7 is old version, you need to get new version manually

**Comment by alvarokrn** [comment]
Thanks. I installed the last version but looks like Firefox failed and it keep the old one. I've unistalled and installed again and it works!
