### ISSUE TITLE
Plugin doesn't work anymore.

### ISSUE THREAD

**Issue by DeCat4** [dimdenGD/OldTwitter#779]
Twitter now forces us onto the x.com domain and my firefox only allows it to access data for the twitter.com domain

Firefox just says the plugin can't make changes on this site, when i open twitter.com it just forces me to x.com, one thing i encountered earlier is that it would endlessly load until i disabled and re enabled the plugin, now it just can't access the site, i can't manually give it permission

Firefox Version 126.0 (64 Bits)

**Comment by serveral1** [comment]
Same here, had to disable the extension of firefox because otherwise it'd would get stuck on an endless loop trying to redirect to x.com

**Comment by zombipuppy** [comment]
Same issue here.

**Comment by bluewarbler** [comment]
Thirding this.

**Comment by Axm0deus** [comment]
fourthing this.

**Comment by Babosa28** [comment]
Fifthing this.

**Comment by JadeMonsuta** [comment]
Started around last night for me, twitter seems to be stuck in a constant cycle of redirecting now.

**Comment by terminatorX2** [comment]
Yeah, same here. Switching to the desktop app version for now.

**Comment by dimdenGD** [comment]
You need to update extension manually on Firefox, since it was removed from Mozilla Addons store. Make sure to visit x.com at least once without extension for migration to complete.

**Comment by DeCat4** [comment]
how do we update manually? are we supposed to drag and drop the files from the github repo into whatever directory firefox holds plugins in?

**Comment by dimdenGD** [comment]
Uninstall current one, install it again (theres tutorial on main page)
