### ISSUE TITLE
TypeError in tweet replies

### ISSUE THREAD

**Issue by MarisaKirisame-ze** [dimdenGD/OldTwitter#78]
**Describe the bug**
The end of a tweet's reply section will have a TypeError instead of extra replies loading.

**To Reproduce**
Go to any tweet and go to the replies.

**Expected behavior**
The replies scroll infinitely, but they don't for some reason.

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/86389939/bbd12727-2049-44f3-9f55-c57947e11f6f)

**Browser**
Google Chrome, Version 114.0.5735.110 (Official Build) (64-bit)

**Comment by dimdenGD** [comment]
Can't reproduce

**Comment by MarisaKirisame-ze** [comment]
Try tweets with 10 or more replies.
https://twitter.com/Marisa_Plushie/status/1432733451300519937
