### ISSUE TITLE
Custom CSS didn't migrate to "x.com"

### ISSUE THREAD

**Issue by wiichicken** [dimdenGD/OldTwitter#780]
**Describe the bug**
When my Twitter was migrated from twitter.com to "x.com" (formerly twitter.com), my custom CSS was not carried over.

**Browser**
Vivaldi 6.7.3329.31 (Stable channel) (64-bit) 

**OldTwitter version**
v1.8.4.1

**Comment by dimdenGD** [comment]
Unfortunately impossible to fix :(
