### ISSUE TITLE
New twitter.com > x.com redirect breaks the Firefox extension for me

### ISSUE THREAD

**Issue by glottisfaun0000** [dimdenGD/OldTwitter#781]
Starting today twitter.com is redirecting to x.com for me (see: https://arstechnica.com/tech-policy/2024/05/twitter-urls-redirect-to-x-com-as-musk-gets-closer-to-killing-the-twitter-name/ ). Wondering if the extension can support the site on x.com urls or somehow circumvent this.

**Comment by dimdenGD** [comment]
They're already supported on new version, you need to update extension manually since it was removed from Mozilla addon store

**Comment by glottisfaun0000** [comment]
Totally missed the removal, thanks for working on this!
