### ISSUE TITLE
Redirection issue

### ISSUE THREAD

**Issue by rockguitarbandhero0192** [dimdenGD/OldTwitter#786]
when trying to access twitter, it keeps switching back and forth from x.com to twitter,com/x/migrate...... with a white screen

**Browser**
Firefox Nightly 128.0a1

**OldTwitter version**
1.8.4.1

**Comment by rockguitarbandhero0192** [comment]
nevermind https://twitter.com/d1mden/status/1791407084279320676

**Comment by UnholyEntropy** [comment]
I did what it said, but when I turn the addon back on and try to go back to the site, it merely retains the usual layout and doesn't apply the addon's layout.
