### ISSUE TITLE
Firefox OldTwitter add-on is read as broken.

### ISSUE THREAD

**Issue by Alquidreo** [dimdenGD/OldTwitter#787]
**Describe the bug**
When trying to upload the ZIP file to firefox developer mode (freshly installed), it says the add-on is broken and doesn't load it

**Screenshots**
![nope0](https://github.com/dimdenGD/OldTwitter/assets/107868843/46b1af8a-8965-46ad-82cd-a4f7fe556a34)
![nope](https://github.com/dimdenGD/OldTwitter/assets/107868843/d545e857-27e1-482b-b8f2-fa1cd97e24f5)

**Comment by dimdenGD** [comment]
Go to about:config
Set xpinstall.signatures.required to false

**Comment by Alquidreo** [comment]
It has been set to false.

![nope1](https://github.com/dimdenGD/OldTwitter/assets/107868843/e5561fcb-cc9a-4078-8ff4-b9ba4e73d2d8)

**Comment by cherrypockies** [comment]
> Go to about:config Set xpinstall.signatures.required to false

thats not the issue, i tried updating mine today and it seems like the latest version is not working
(xpi signature required is disabled)

**Comment by Alquidreo** [comment]
However, it seems to work fine when updated in normal Firefox as a temporary add-on.
I'm not sure how or why.

![nope2](https://github.com/dimdenGD/OldTwitter/assets/107868843/e2c219cd-fdbe-40ce-b5a1-fc934bcf9a8d)

**Comment by dimdenGD** [comment]
Updated file, try again

**Comment by cherrypockies** [comment]
> Updated file, try again

that seems to have fixed it!

**Comment by Alquidreo** [comment]
Seems to work just fine, thanks a lot dimden!
