### ISSUE TITLE
OldTwitter not working after X.com domain change.

### ISSUE THREAD

**Issue by chickenwithakeyboard** [dimdenGD/OldTwitter#789]
**Describe the bug**
OldTwitter is not activating when X is loaded. X loads as 'normal'.

**Browser**
Firefox Version 126.0 (64-bit)

**Links**
https://twitter.com/

**OldTwitter version**
1.8.3.7

**Comment by dimdenGD** [comment]
ure using old version of extension

**Comment by chickenwithakeyboard** [comment]
updated! thank you!
