### ISSUE TITLE
Tweets tab doesn't show all photos and videos.

### ISSUE THREAD

**Issue by MarisaKirisame-ze** [dimdenGD/OldTwitter#79]
**Describe the bug**
When you go into the Tweets tab of a profile, not all photos and videos are shown in the "Photos and videos" section. Only pinned tweets show for some reason.

**To Reproduce**
Go into your profile and click the "Tweets" tab.

**Expected behavior**
All of the photos and videos should be there.

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/86389939/3a83fcdd-3f49-4bc4-b5d9-23154624bb8a)

**Browser**
Google Chrome Version 114.0.5735.110 (Official Build) (64-bit)

**Comment by dimdenGD** [comment]
This is not a bug and only shows media of your tweets it loaded, and since you probably retweet a lot it only saw pinned tweet as your only tweet, if you load more tweets of your they'll appear
