### ISSUE TITLE
Opening links from tweets in the same tab

### ISSUE THREAD

**Issue by jcszymansk** [dimdenGD/OldTwitter#793]
**Describe the bug**
Clicking an external link in a tweet (but not the page thumbnail) opens in the same tab, not in a new one.

**Screenshots**
n/a

**Browser**
Firefox 125.0.3, Brave Beta

**Links**
n/a

**OldTwitter version**
1.8.4.3, newest from Actions

**Comment by JadedMagician** [comment]
I've been experiencing the same issue in Vivaldi. It's very annoying as it causes me to lose my place on the timeline when I go back.
