### ISSUE TITLE
"Photos & videos" doesn't show any tweets anymore

### ISSUE THREAD

**Issue by Manimap** [dimdenGD/OldTwitter#795]
**Describe the bug**
When I go to "Photos & videos" for any user, I cannot see any tweet anymore, it's just empty. Others like "tweets" and "tweets & replies" work fine.

**Screenshots**
<img width="839" alt="image" src="https://github.com/dimdenGD/OldTwitter/assets/13313380/5401f60f-70a6-4f12-b234-390ff9359317">

Browser
Brave Version 1.66.110 Chromium: 125.0.6422.60 (Official Build) (64-bit)

Links
Go to any user and click on "Photos & videos"

OldTwitter version
v1.8.4.3

**Comment by dimdenGD** [comment]
What error do you get in console (F12)?

**Comment by dimdenGD** [comment]
these are warnings not errors

**Comment by dimdenGD** [comment]
idk then, it works for me
