### ISSUE TITLE
Twitter Migrate URL

### ISSUE THREAD

**Issue by AYT04** [dimdenGD/OldTwitter#796]
I found this thing that happens whenever I load 'x.com', it tried to load the site but comes up with the migration, assuming it's glitched on my device with the extension (addon) installed.

Again, I'm not sure if this is a bug or what.

Device:
Android 10

[Learn More](https://odysee.com/@clips:1d/thanks-elon-for-breaking-twixxer.ayt:4?r=Cj54sHLrTqB1ZSFBVujuJVEwYPNG7E56)

**Comment by Asteriadeath** [comment]
disable oldtwitter then let it migrate to the new url, then try to see if oldtwitter will work.

**Comment by ruben1PvP** [comment]
> disable oldtwitter then let it migrate to the new url, then try to see if oldtwitter will work.

No, that's not a proper solution, as there is a not zero chance Twitter "migrates" again if you open a twitter.com link, which forces you to disable the addon and enable it again after.

**Comment by dimdenGD** [comment]
Not sure what you're talking about, but you just have to "migrate" once, which just means going to x.com once without extension. After that you can turn extension back on and it works fine always

**Comment by ruben1PvP** [comment]
> Not sure what you're talking about, but you just have to "migrate" once, which just means going to x.com once without extension. After that you can turn extension back on and it works fine always

Alright, I think I know what happens. You only have to migrate **once** because the "_check_" of you being migrated is only in your client (it's saved as part of your x.com cookies). So if you are someone like me that cleans cookies from sites from your browser, you will have to migrate again.
