### ISSUE TITLE
cannot make tweets with photos on it

### ISSUE THREAD

**Issue by trinitykitty** [dimdenGD/OldTwitter#797]
I cannot upload any piece of media onto my twitter profile with this.
I don't know if it's because of the stupid """new""" URL that Elongated Muskrat is fucking forcing me to use or if it's because i'm using a private account
but I cannot make any tweets with media in it

I can send normal tweets, I can't send tweets with media in it...

**SCREENSHOTS:**
![trying to send a photo](https://github.com/dimdenGD/OldTwitter/assets/101519557/5720186b-00f7-42ea-8e4a-59394272acab)
![DAMMIT](https://github.com/dimdenGD/OldTwitter/assets/101519557/cf1e85b5-9990-4141-b4d3-81e0661369da)

**Comment by frozenpandaman** [comment]
Getting this as well. ver 1.8.4

**Comment by frozenpandaman** [comment]
Fixed on Chrome, thanks!
