### ISSUE TITLE
twitter.com to x.com with oldtwitter active

### ISSUE THREAD

**Issue by Asteriadeath** [dimdenGD/OldTwitter#799]
**Describe the bug**
just got my hdd back and i tried to go on twitter today, everytime i try to open twitter, i get moved to x.com.

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/163482010/cb8e4f1f-1fb2-4b3e-832b-0ff931a9a57d)
![image](https://github.com/dimdenGD/OldTwitter/assets/163482010/0842c261-bdd5-4db5-b37e-c7a90b57e654)
![image](https://github.com/dimdenGD/OldTwitter/assets/163482010/5ee180ac-b786-40fd-8653-e75ccb6d3a2a)
in a loop

**Browser**
edge version 125.0.2535.51

**Links**
any twitter/x link

**OldTwitter version**
nope, only the oldtwitter loading screen

**Comment by dimdenGD** [comment]
turn extension off, visit x.com without extension once to get migrated, turn extension back on
