### ISSUE TITLE
'Could not authenticate you' on Firefox

### ISSUE THREAD

**Issue by skmistress** [dimdenGD/OldTwitter#801]
Why does this pop up when I try to send/post an image with the extension enabled?
![image](https://github.com/dimdenGD/OldTwitter/assets/156722465/d15042d0-2545-4f70-9ef1-c43089cfea48)

**Comment by dimdenGD** [comment]
It's a bug that was fixed in newer version

**Comment by skmistress** [comment]
Oh, I didn't know.
