### ISSUE TITLE
"Could not authenticate you." pop-up when trying to post a Tweet

### ISSUE THREAD

**Issue by kiiboen** [dimdenGD/OldTwitter#802]
I use OldTwitter v1.8.4 on Firefox 126.0. No matter what I do. Every time I try to post a Tweet; I get this pop-up:
![Screenshot from 2024-05-24 20-57-58](https://github.com/dimdenGD/OldTwitter/assets/117480539/87cab9fb-c02c-44f7-af67-2520370a5599)

I have no idea what could be causing this. All I remember is that started happening a few days after OldTwitter returned to Add-ons for Firefox.

**Comment by dimdenGD** [comment]
https://twitter.com/d1mden/status/1793925792499654777
