### ISSUE TITLE
"This request requires a matching csrf cookie and header." error when trying to tweet

### ISSUE THREAD

**Issue by Sphirye** [dimdenGD/OldTwitter#803]
**Describe the bug**
When trying to tweet anything on any context (single tweet or comment), the browser throws an "This request requires a matching csrf cookie and header." alert.

Console log:
`This request requires a matching csrf cookie and header. [tweetviewer.js:723:29]`

**Screenshots**
![imagen](https://github.com/dimdenGD/OldTwitter/assets/68203934/288a570c-188e-461d-ac07-4592ff260284)

**Browser**
Firefox Browser 126.0 64-bits (Flatpak)
OS: Fedora 40

**OldTwitter version**
v1.8.4

**Comment by GR-Eliki-Smith** [comment]
got the same issue and it occurs when trying to upload files, i HOPE it'll get resolved soon.

**Comment by dimdenGD** [comment]
1.8.4 is an old version
