### ISSUE TITLE
"Could not authenticate you." when attempting to tweet an image or video

### ISSUE THREAD

**Issue by torodesu** [dimdenGD/OldTwitter#804]
**Describe the bug**
Attempting to tweet an image or video prompts a pop-up with the message "x.com says: Could not authenticate you."

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/83902603/54c0fbde-32dd-4bb3-a13e-f44e2a4eefdf)

**Browser**
Microsoft Edge 125.0.2535.67 (Official build) (64-bit) 

**OldTwitter version**
1.8.4

**Comment by dimdenGD** [comment]
You're using old version of extension

**Comment by torodesu** [comment]
You're right, my apologies. Looks like it working fine now. Thank you so much. 😊

**Comment by themattreinhart** [comment]
I think its needs to be reopen... IT ALSO OCCURS ON THE NEW VERSION TOO. Text tweets tho works.

**Comment by torodesu** [comment]
I'm on 1.8.4.3 and it's working fine
![image](https://github.com/dimdenGD/OldTwitter/assets/83902603/a24bb146-02de-4ff6-ad97-f8475b611cf6)
![image](https://github.com/dimdenGD/OldTwitter/assets/83902603/2361b11f-2052-49ec-892f-2e1bea85c6ec)
