### ISSUE TITLE
Latest Update still not functioning on firefox

### ISSUE THREAD

**Issue by MP36ctrl** [dimdenGD/OldTwitter#806]
Error reading crypto key No key found [injection.js:618:17](moz-extension://61c80b97-0e59-4d04-ad55-650ac7e43115/scripts/injection.js)
Error: chrome.scripting.executeScript(...) is undefined undefined
Error during challenge: [twchallenge.js:128:17](moz-extension://61c80b97-0e59-4d04-ad55-650ac7e43115/scripts/twchallenge.js)
TypeError: homepageData.match(...) is null
    initChallenge moz-extension://61c80b97-0e59-4d04-ad55-650ac7e43115/scripts/twchallenge.js:108
    async* moz-extension://61c80b97-0e59-4d04-ad55-650ac7e43115/scripts/twchallenge.js:134
[twchallenge.js:129:17](moz-extension://61c80b97-0e59-4d04-ad55-650ac7e43115/scripts/twchallenge.js)
Content-Security-Policy: Ignoring “'unsafe-inline'” within script-src: nonce-source or hash-source specified [migrate](https://twitter.com/x/migrate?tok=eyJlIjoiL2hvbWUiLCJ0IjoxNzE2ODM5MDgzfRRcrah7Y0T7TMwHyLtEDE4%3D)
textInput event has been remapped to beforeinput for compatibility reasons. See https://bugzilla.mozilla.org/show_bug.cgi?id=1739489 for details. [bug1739489-draftjs-beforeinput.js:13:9](moz-extension://321a4e55-ef43-46e1-8c7a-5d643df5b13b/injections/js/bug1739489-draftjs-beforeinput.js)
Content-Security-Policy: The page's settings blocked the loading of a resource at inline ("script-src"). [blocker.js:162:27](moz-extension://021a2bc9-917e-4c4e-ba27-9491a3ea3603/data/inject/blocker.js)
Content-Security-Policy: The page's settings blocked the loading of a resource at inline ("script-src"). 2 [content.js:60:436](moz-extension://158d2e76-799f-4393-8588-8f9979a36f66/content.js)
Content-Security-Policy: The page's settings blocked the loading of a resource at inline ("script-src"). [content.js:411:48](moz-extension://7f2302bf-109c-4fda-9a29-ea600fec738c/dist/content.js)
Error during challenge: [twchallenge.js:128:17](moz-extension://61c80b97-0e59-4d04-ad55-650ac7e43115/scripts/twchallenge.js)
TypeError: homepageData.match(...) is null
    initChallenge moz-extension://61c80b97-0e59-4d04-ad55-650ac7e43115/scripts/twchallenge.js:108
    async* moz-extension://61c80b97-0e59-4d04-ad55-650ac7e43115/scripts/twchallenge.js:134

This is on Firefox 115esr

**Comment by dimdenGD** [comment]
what exactly do you mean by not functioning

**Comment by Garyzan** [comment]
I have a similar issue, the page keeps redirecting between
 - https://x.com/home
 - https://twitter.com/x/mx=1
 - https://twitter.com/x/migrate?tok=[long token]
in an endless cycle

I'm on the version 1.8.4 of OldTwitterLayout and version 126.0.1 of Firefox

**Comment by dimdenGD** [comment]
You need to load x.com at least once without extension for it to work. Also 1.8.4 is old version, extension is no longer updated on Mozilla Addons
