### ISSUE TITLE
Unable to make posts with images

### ISSUE THREAD

**Issue by MadMarco64** [dimdenGD/OldTwitter#807]
Everytime i try to make a post with an image attached, it doesn't complete and a pop up appears saying "Could not authenticate you."
No idea why this happens unfortunately.

![image](https://github.com/dimdenGD/OldTwitter/assets/115125120/8a77d1e9-e4c7-4bca-b2b0-4d172c8efd8e)

Firefox 126.0

OldTwitter v1.8.4.4

**Comment by dimdenGD** [comment]
are you sure you're actually using 1.8.4.4?

**Comment by MadMarco64** [comment]
Ah apologies i've misread it, it's 1.8.4
I thought it was updated to the last version from Firefox's Add-ons store.
Does that mean i'll have to use Firefox Developer Edition for it to work permanently? or will it be updated in the add-ons store for the normal browser?

**Comment by dimdenGD** [comment]
I don't know if they will approve update or not. Yes you need developer edition to add extensions manually permamently

**Comment by MadMarco64** [comment]
Apologies for the trouble, and thank you for your time aswell.
Have a good day!
