### ISSUE TITLE
Twitter completely unusable with OldTwitter since url change to X.com

### ISSUE THREAD

**Issue by ShieldOfWesnoth** [dimdenGD/OldTwitter#809]
When I try to view my twitter feed, or absolutely any twitter page (users, searching, even OldTwitter's settings), in what I assume is OldTwitter possibly trying to stay on "twitter", it gets caught in an infinite redirection loop as the website itself tries to drag it back to having "x.com" urls.
If I try to go to "twitter.com" it'll load a moment, then it automatically goes to "x.com/home", then it automatically goes to "twitter.com/x/migrate"", then it automatically goes to "twitter.com/?mx=1".  From there, the loop will return to its point at "x.com/home" and repeat the series of redirects indefinitely from there.

Turning off OldTwitter in my extension settings fixes this instantly, but the downside is that I get none of OldTwitter's benefits and have to look at the ugly mess that is modern twitter/x... which I cannot stand whatsoever...!

Trying to avoid this by just biting the bullet and typing in "x.com" in the first place has no effect, and just creates the same redirect loop so long as OldTwitter is activated.  Can this be fixed?  Using twitter on desktop has become impossible because the pages can never fully load.  Help!

**Browser** where this was experienced: **Opera** One, version 110.0.5130.39

**Links**: twitter.com, x.com, x.com/home

**OldTwitter version**: 1.8.4.3

**Comment by dimdenGD** [comment]
If you load x.com once without extension, you should get migrated and turn extension back on and it'll work fine. It's impossible for it to cause such redirect loops afterwards unless you're actively clearing your cookies every time you try to use OldTwitter.
