### ISSUE TITLE
Make it so quote retweets open a new window that lets you add images, polls and whatever else you can add to a regular tweet

### ISSUE THREAD

**Issue by Arcadius2006** [dimdenGD/OldTwitter#81]
honestly its kinda annoying to have the quote menu open like a reply despite the fact that it's technically a seperate tweet

**Comment by dimdenGD** [comment]
You already can add images/videos/gifs to quote tweets with `[upload media]` button. You can't add polls on quote tweets, that's limitation on normal twitter too
