### ISSUE TITLE
can't quote a tweet, send a tweet or reply to someone with images

### ISSUE THREAD

**Issue by yorunoken** [dimdenGD/OldTwitter#810]
**Describe the bug**
each occasion gives a different error.
when you're trying to quote someone, it gives you `BadRequest: attachment_url parameter is invalid. (44)`
when trying to send a tweet with any images, it pops up an alert and says "could not authenticate you"

**Screenshots**
quote example:
![image](https://github.com/dimdenGD/OldTwitter/assets/69751661/3c4335c2-c55e-4cbc-af3f-074947931d16)
console:
![image](https://github.com/dimdenGD/OldTwitter/assets/69751661/9d849424-27e6-4bbb-8e9f-dc603b5cdc19)

image tweet example:
![image](https://github.com/dimdenGD/OldTwitter/assets/69751661/d1b8d040-2804-4ff3-9885-39857628ce76)
console:
![image](https://github.com/dimdenGD/OldTwitter/assets/69751661/e6f19400-3d6a-4701-8b66-327941f445c7)

**Browser**
Mozilla Firefox, developer edition 127.0b7 on Archlinux

**Links**
no link needed as it happens every single time, on every single tweet, but [this is the tweet that errors when trying to quote](https://x.com/rasaa2020/status/1794031056565522571)

**OldTwitter version**
Running [OldTwitter](https://github.com/dimdenGD/OldTwitter) v1.8.4

**Comment by dimdenGD** [comment]
You're using an old version
https://twitter.com/d1mden/status/1793925792499654777

**Comment by yorunoken** [comment]
oh alright thanks, didn't see your tweet.
