### ISSUE TITLE
Image uploading / viewing is broken in DMs

### ISSUE THREAD

**Issue by memmam** [dimdenGD/OldTwitter#814]
**Describe the bug**
Cannot send or view images in DMs in OldTwitter, only in regular Twitter

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/9062595/cf026cc1-ad34-4237-b943-0a33c0b97dfa)
(this shows an image failing to send
![image](https://github.com/dimdenGD/OldTwitter/assets/9062595/5835bac9-1abe-48f7-b5e1-d3164c324d09)
(image can be sent just fine in regular Twitter)
![image](https://github.com/dimdenGD/OldTwitter/assets/9062595/928abbcf-8a24-4b91-9321-cf80002fbe24)
(image shows as broken in OldTwitter, note working emoji)

Browser
Firefox Developer Edition 127.0b6
Issue also occurs on Firefox 126.0.1

Links
https://x.com/home#dm
happens with any DM with any person, in my experience

OldTwitter version
~~1.8.4.5~~ 1.8.4

**Comment by dimdenGD** [comment]
![image](https://github.com/dimdenGD/OldTwitter/assets/26517362/e699fc2d-64ce-40d7-918a-ed6c7dd34c7b)
Can't reproduce on both Firefox and Chrome on 1.8.4.5

**Comment by memmam** [comment]
Correction, I think I'm on 1.8.4? it says 'last version 1.8.4.5' but it says my version is 1.8.4, I think I misinterpreted that initially. OldTwitter on Firefox Addons also reports as being version 1.8.4. Whoops.

**Comment by glottisfaun0000** [comment]
I get this error on all photo uploads

**Comment by dimdenGD** [comment]
1.8.4 is old version. More info: https://twitter.com/d1mden/status/1793925792499654777
