### ISSUE TITLE
Latest version of OldTwitter will still not post pictures but can post text tweets

### ISSUE THREAD

**Issue by themattreinhart** [dimdenGD/OldTwitter#815]
I think it needs to be reopen... IT ALSO OCCURS ON THE NEW VERSION TOO. Text tweets tho works. (Add-on ver: 1.8.4)

_Originally posted by @themattreinhart in https://github.com/dimdenGD/OldTwitter/issues/804#issuecomment-2138496375_

^^^^^^^^^^^

I thought the now-closed issue says that its due to an outdated version. Still applies on the latest version.

Firefox Dev 127.0b7 (latest as of posting; updated to new version)

**Comment by dimdenGD** [comment]
1.8.4 is old version

**Comment by themattreinhart** [comment]
> 1.8.4 is old version

Seems like the Firefox Add-On store version is still at 1.8.4 while the latest on GitHub is 1.8.4.4 which can only be downloaded and reinstalled again, which is the reason why it caused the issue.

**Comment by dimdenGD** [comment]
https://twitter.com/d1mden/status/1793925792499654777
