### ISSUE TITLE
Twitter->X migration happening again even with the page being x.com

### ISSUE THREAD

**Issue by VaelophisNyx** [dimdenGD/OldTwitter#816]
**Describe the bug**
Was just sitting with twitter open (as x.com) and it redirected to the migration key link. Keeps doing it now.

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/1534478/1b323f1b-a608-4e22-81f3-3c4b5bcf6726)
![image](https://github.com/dimdenGD/OldTwitter/assets/1534478/8e82b6fd-d323-418d-afe6-b774154fa771)

**Browser**
![image](https://github.com/dimdenGD/OldTwitter/assets/1534478/e01789c4-296f-40a9-9cd6-35e0697f4342)

**Links**
[https://x.com](https://x.com)

**OldTwitter version**
can't check.

**Comment by dimdenGD** [comment]
Turn extension off, let it migrate, turn it back on
