### ISSUE TITLE
Auto-height for input boxes

### ISSUE THREAD

**Issue by quardbreak** [dimdenGD/OldTwitter#82]
I wanted to implement by self but gave up.
Anyway, seems must be neat to have for these:
![image](https://github.com/dimdenGD/OldTwitter/assets/44920739/855acfa1-8dff-4e9b-a479-d73584b83cdf)
![image](https://github.com/dimdenGD/OldTwitter/assets/44920739/3571f11f-4ed5-43c6-883a-69f85be723fb)

**Comment by Rajeevjewar** [comment]
I will try to fix it later.

**Comment by dimdenGD** [comment]
I've added a way to resize reply inputs but it won't be added for main tweet composer (as it's trash that will break on any size change)
