### ISSUE TITLE
cannot post images, will also periodically log me out 

### ISSUE THREAD

**Issue by staterafukumoto** [dimdenGD/OldTwitter#823]
**Describe the bug**
i cannot attach images to tweets, and after a few attempts (or just randomly whenever it feels like it) it randomly logs me out and gets stuck at a blank page, and i have to disable the extension to do a capcha test to log into my account again.

(when it logs me out and gets stuck, the URL is a `https://twitter.com/x/migrate?tok=` with a token at the end of it)

**Screenshots**
![SCR-20240605-21c](https://github.com/dimdenGD/OldTwitter/assets/48106340/d41d0bd0-38e8-4f07-87ef-f0e5ead87200)

**Browser**
firefox 126.0.1

**Links**
anywhere on the website

**OldTwitter version**
1.8.4 (latest version on firefox store)

**Comment by dimdenGD** [comment]
1.8.4 is old version. OldTwitter is no longer updated on Firefox Addons Store

**Comment by staterafukumoto** [comment]
> 1.8.4 is old version. OldTwitter is no longer updated on Firefox Addons Store

is there any plan for updating it on the firefox addons store ever again, or is it officially no longer being updated and i should move on?
