### ISSUE TITLE
Extension should be removed from Firefox Addons store if possible (got my account suspended)

### ISSUE THREAD

**Issue by kokoropaint** [dimdenGD/OldTwitter#824]
Pretty selfexplanatory title. My account is [here](https://x.com/amalgamidol). I have had no other suspicious activity or tweets that were "worthy" of suspension, other than the constant lockouts caused by version 1.8.4. of this extension. If there's any way you can take it down I really don't think it's safe to keep it up.

**Comment by LabRatMime** [comment]
The same thing happened to me, lockouts and everything. I managed to get my account back from an appeal but that's still pretty odd.

**Comment by itsTyrion** [comment]
@LabRatMime what did you put in the appeal? Mine gets auto rejected within seconds ._.

**Comment by LabRatMime** [comment]
@itsTyrion i just put "I'm not sure what I did." it worked for my second suspension as well though that one took about a week to be accepted
