### ISSUE TITLE
The extension doesnt Works On google chrome

### ISSUE THREAD

**Issue by HOLAAAAAAAAAAA12** [dimdenGD/OldTwitter#827]
**Describe the bug**
when i go to the site the extension bugs with x.com and a a link called token please fix it

**Screenshots**
![b](https://github.com/dimdenGD/OldTwitter/assets/171965932/cd7da55d-0072-4b6f-8bd8-27b185b1b420)

**Browser**
Google Chrome 125

**Links**
Link t![b]

**OldTwitter version**
The actual from chrome web store

**Comment by dimdenGD** [comment]
turn off, visit x.com without extension, turn on
