### ISSUE TITLE
escaping alt text

### ISSUE THREAD

**Issue by cacheninetynine** [dimdenGD/OldTwitter#829]
**Describe the bug**
i don't really know how its correctly called but you can escape alt text with the alt text being `start" <h1>hello, world</h1>` (https://x.com/josephorange__/status/1799085430337585509)

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/88933951/77431d40-b245-40ba-bb43-c935f9b0c11b)
Firefox

![image](https://github.com/dimdenGD/OldTwitter/assets/88933951/27fa6947-e416-4eaf-9262-369cee208354)
Microsoft Edge

**Browser**
Firefox 126.0.1 and Microsoft Edge 125.0.2535.85 respectively

**Links**
https://x.com/josephorange__/status/1799079427378401647
https://x.com/josephorange__/status/1799081970829586849

**OldTwitter version**
Firefox v1.8.4 and Edge v1.8.4.5

**Comment by dimdenGD** [comment]
This already was fixed but not updated on stores
