### ISSUE TITLE
Cannot initialize security header generator: "undefined"

### ISSUE THREAD

**Issue by muuyo** [dimdenGD/OldTwitter#833]
**Describe the bug**
A clear and concise description of what the bug is. Make sure to search issues, maybe it's already reported.

Open any x.com tab. Error popup. No dice.

**Screenshots**
If applicable, add screenshots or video to help explain your problem. Include screenshot of your browser console (F12 -> Console tab).

![image](https://github.com/dimdenGD/OldTwitter/assets/34991771/2f20c5ac-0bf4-4ccc-9df4-e2cdeefb137d)

**Browser**
Include your browsers name and it's version.
Floorp
![image](https://github.com/dimdenGD/OldTwitter/assets/34991771/bdd5fb65-f465-4ffa-ba4e-920bfca7ef6b)

**Links**
Link to profile/tweet or other page where bug happens.
N/A

**OldTwitter version**
Can be seen on bottom-right
Installed fresh from the latest release, 18 hours ago, however unable to check since it never loads.

Additional:
[console-export-2024-6-8_6-40-9.txt](https://github.com/user-attachments/files/15748065/console-export-2024-6-8_6-40-9.txt)

**Comment by dimdenGD** [comment]
There has been an update a hour ago

**Comment by muuyo** [comment]
didn't know i had to download the beta, that works 👍
