### ISSUE TITLE
New 1.8.4.7 update broke media display

### ISSUE THREAD

**Issue by ayukoVTuber** [dimdenGD/OldTwitter#835]
**Describe the bug**
Some media (gifs/videos/photos) in my notifications, on my timeline and any profile I'm viewing appears blank and any video I'm trying to play turns blank right after I click play

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/22845568/c175fb1a-a79a-4ccd-aded-0f58ce8c3b6a)

(console outputs this:)
![image](https://github.com/dimdenGD/OldTwitter/assets/22845568/c58bdcb2-2f29-4613-86fc-fb70226a51a7)

**Browser**
Firefox Nightly 128.0a

**Links**
Affects all pages

**OldTwitter version**
1.8.4.7

**Comment by themattreinhart** [comment]
> **Describe the bug** Some media (gifs/videos/photos) in my notifications, on my timeline and any profile I'm viewing appears blank and any video I'm trying to play turns blank right after I click play
> 
> **Screenshots** ![image](https://private-user-images.githubusercontent.com/22845568/338015601-c175fb1a-a79a-4ccd-aded-0f58ce8c3b6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNjU2MzgsIm5iZiI6MTcxODA2NTMzOCwicGF0aCI6Ii8yMjg0NTU2OC8zMzgwMTU2MDEtYzE3NWZiMWEtYTc5YS00Y2NkLWFkZWQtMGY1OGNlOGMzYjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDAwMjIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzOWNlNTM1OTdkNGJiZjY4Y2E1NTY3MDQ0MmJkODFlNzIwZGVlZDI5ZGFkYzFjN2JkMWY5NmFkOGYzMDg4YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nPpMCBh_ltKUDOUw20S0fEB0pmkrAnjbTUZow8RlesU)
> 
> (console outputs this:) ![image](https://private-user-images.githubusercontent.com/22845568/338015676-c58bdcb2-2f29-4613-86fc-fb70226a51a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNjU2MzgsIm5iZiI6MTcxODA2NTMzOCwicGF0aCI6Ii8yMjg0NTU2OC8zMzgwMTU2NzYtYzU4YmRjYjItMmYyOS00NjEzLTg2ZmMtZmI3MDIyNmE1MWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDAwMjIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5ZWVhOGZmNzQ0NzZiNWIyOGJiNTcxMzEyZDgxMzY5MTA5YjhjZTJlOTdmOTAxMmEzMWRlNTdiNjU4YTA4NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wRtYfBB-8cLpR6rDSPCxuyBCw_8IYxOhIztIWp-GgSI)
> 
> **Browser** Firefox Nightly 128.0a
> 
> **Links** Affects all pages
> 
> **OldTwitter version** 1.8.4.7

Nightly is mostly a "day-by-day" version of Firefox that **CAN** have bugs within FF. Can you try using the Developer Edition one since the update release is different than the Nightly? (Dev works with 1.8.4.7 latest)

**Comment by ayukoVTuber** [comment]
> Nightly is mostly a "day-by-day" version of Firefox that **CAN** have bugs within FF. Can you try using the Developer Edition one since the update release is different than the Nightly? (Dev works with 1.8.4.7 latest)

tried it, worked for a while and now I have the same issue again but with videos/gifs only and when I click play this shows up in the console
![image](https://github.com/dimdenGD/OldTwitter/assets/22845568/ba6bd35b-3f24-48c7-8511-5fe516c028f3)

scrolling through media displays this in console without me clicking play
![image](https://github.com/dimdenGD/OldTwitter/assets/22845568/52b66a5c-5e29-4723-973a-0863871fa877)

**Comment by ayukoVTuber** [comment]
ok so update idk if its just my pc or not but once this happens I just have to restart the browser and it works again (it can break after like minutes but then another restart helps)
