### ISSUE TITLE
x.com to twitter.com

### ISSUE THREAD

**Issue by CHUCKECHEESETubeYT** [dimdenGD/OldTwitter#836]
the x.com url is still being used instead of the Twitter.com url, is there a way of making it so that way we can switch between x.com & Twitter.com url? thx

**Comment by ayukoVTuber** [comment]
I think the only way of forcing twitter.com is if the extension added "?mx=1" on the end of the url (idk if it still works tho) since apparently that prevents you from getting redirected to the migration url that takes you to x.com

**Comment by dimdenGD** [comment]
Not possible

**Comment by CHUCKECHEESETubeYT** [comment]
how do you know dimdenGD? you didn't even try! & ayukoVTuber if that's the case, then experimentation is in order
