### ISSUE TITLE
Re-Enable Seeing Likes/Favorites

### ISSUE THREAD

**Issue by PRGilland** [dimdenGD/OldTwitter#837]
Twitter is removing the ability to view other peoples' likes/favorites, and while OldTwitter still has access to the tab, they do not load. However, (Old)Tweetdeck can still see them just fine. Would it be possible to somehow re-enable being able to see likes/favorites?

**Comment by Nightcaat** [comment]
> I can see other people likes, but they just can't load

The method was patched, they are gone for good
