### ISSUE TITLE
brief white flash when loading new pages

### ISSUE THREAD

**Issue by echolessowl** [dimdenGD/OldTwitter#84]
**Describe the bug**
Brief moment where dark mode is deactivated

**To Reproduce**
Install extension, then click on anything that prompts a new page to be loaded.

**Expected behavior**
Dark mode is applied before the page loads.

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/96448535/3bd41bb9-dfde-42b6-9d84-61e8aa6599c2)
taken just before the timeline page loaded

**Browser**
Firefox version 114.0.2

**Comment by dimdenGD** [comment]
This is a bug with injection, I tried to make it as quick as possible but this just happens on slower computers unfortunately :/

**Comment by echolessowl** [comment]
My computer isn't particularly slow, shame

**Comment by TorutheRedFox** [comment]
> My computer isn't particularly slow, kind of a shame i guess

mine isn't either

**Comment by kittuar** [comment]
is there anything to be done about this? getting flashbanged every time I try to use the twitter icon on the top bar to reload isn't great.

**Comment by dimdenGD** [comment]
Glad to say: I fixed this!
