### ISSUE TITLE
Favorites/Likes don't load.

### ISSUE THREAD

**Issue by ovingiv** [dimdenGD/OldTwitter#842]
**Describe the bug**
When viewing any profile or your own, you can't see likes. It has a loading circle that just spins around.

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/24558152/df0b9dbe-0081-4a5d-97a0-0099884d20ab)
![image](https://github.com/dimdenGD/OldTwitter/assets/24558152/7a97feda-17af-4ec3-bdbf-2efe4386737d)
![image](https://github.com/dimdenGD/OldTwitter/assets/24558152/c7e88f26-f8a9-4afd-aa66-7d8492ec7525)

**Browser**
Google Chrome Version 125.0.6422.142 (Official Build) (64-bit)

**Links**
https://x.com/d1mden/likes

**OldTwitter version**
1.8.5

**Comment by PRGilland** [comment]
It was patched out and doesn't work anymore
