### ISSUE TITLE
It doesn´t let you see the likes again

### ISSUE THREAD

**Issue by soulsoul20** [dimdenGD/OldTwitter#845]
It doesn´t let you see other account´s likes again. Last time I could see them was about 18h ago.

**Comment by dimdenGD** [comment]
its gone

**Comment by soulsoul20** [comment]
So it isn´t fixable?

**Comment by dimdenGD** [comment]
nop

**Comment by soulsoul20** [comment]
And will it be in the near future? Elon has destroyed twitter :(
