### ISSUE TITLE
"Could not authenticate you" when trying to post tweets with media

### ISSUE THREAD

**Issue by vnwr** [dimdenGD/OldTwitter#858]
**Describe the bug**
A clear and concise description of what the bug is. Make sure to search issues, maybe it's already reported.
Unable to upload media anywhere on the site, can tweet normally but adding any image/video causes the error shown below

**Screenshots**
If applicable, add screenshots or video to help explain your problem. Include screenshot of your browser console (F12 -> Console tab).
![image](https://github.com/dimdenGD/OldTwitter/assets/65083757/f585772c-774a-4ae2-a7bf-91f7e3cae42c)
![image](https://github.com/dimdenGD/OldTwitter/assets/65083757/69e256c0-3d69-4dca-b6a3-b9bd49dc6ab0)
[copy of output](https://pastebin.com/raw/U1JFw55m)

**Browser**
Include your browsers name and it's version.
Firefox 127.0.2 (64-bit)

**Links**
Link to profile/tweet or other page where bug happens.
Anywhere on the website

**OldTwitter version**
Can be seen on bottom-right
1.8.4

**Comment by dimdenGD** [comment]
You're using an old version of extension
