### ISSUE TITLE
custom link color doesn't work

### ISSUE THREAD

**Issue by caramellya-mei** [dimdenGD/OldTwitter#868]
### Description
I just noticed the link color defaults to blue (not the twitter accent color) and cannot be changed. 

![image](https://github.com/dimdenGD/OldTwitter/assets/115384748/b141af66-4dca-44ed-9acb-6af9ed9934d1)

The cause seems to be because there is `--link-color: var(--general-color) !important;` in `:root`,  which overrides the custom `--link-color`.

![image](https://github.com/dimdenGD/OldTwitter/assets/115384748/c1974ad7-cc3f-42c9-ad74-b4297f420c27)

### Temporary solution

Changing `--general-color` from the custom css works

![image](https://github.com/dimdenGD/OldTwitter/assets/115384748/7a9ae165-ae51-4cc5-b2d5-e805e46a453b)

### Browser
Mercury 123.0.1 (Firefox fork)

### OldTwitter version
1.8.5.2

**Comment by dimdenGD** [comment]
--general-color is not part of oldtwitter, check other extensions for interference

**Comment by caramellya-mei** [comment]
turns out it is from the themes that I'm using (firefox gx and firefox one), the colors for addon author in about:addons page is using --link-color. I didn't see there are 2 :root that has --link-color and thought the one in screenshot was inline. So yeah, I just had to remove the !important flag from the file
