### ISSUE TITLE
Blue Blocker Integration

### ISSUE THREAD

**Issue by kheina** [dimdenGD/OldTwitter#88]
I got an email a few hours ago asking if [Blue Blocker](https://github.com/kheina-com/Blue-Blocker) could integrate with Old Twitter. I didn't know about your extension before and it's really good, so I'm hoping we can work together to get them working together.

from my investigation, it appears that requests made by extension content scripts, even those that run on the same page, are completely isolated from each other. blue blocker works by [intercepting requests made by the webpage](https://github.com/kheina-com/Blue-Blocker/blob/af9503a397fc3c305ca463391f63ee4378a26457/src/injected/inject.ts#L3-L48) and parsing out the tweet content, old twitter making its requests from a content script essentially blinded blue blocker to all requests being made.

if you'd like to add the ability to run blue blocker with old twitter, the best solution would likely be to use [cross-extension messaging](https://developer.chrome.com/docs/extensions/mv3/messaging/#external) whenever old twitter makes an api request for something containing user content or tweet content, [like the home timeline request](https://github.com/dimdenGD/OldTwitter/blob/master/scripts/apis.js#L199-L218), so that blue blocker can parse it the same as it does with other content

[blue blocker issue](https://github.com/kheina-com/Blue-Blocker/issues/173)

**Comment by dimdenGD** [comment]
Hi, if you'll implement this I will merge the pull request, this seems pretty low priority to me
