### ISSUE TITLE
Some tweets couldn't be loaded due to errors.

### ISSUE THREAD

**Issue by m3k1e** [dimdenGD/OldTwitter#889]
**Describe the bug**
I was opening Twitter and the constant error bug shows up.

**Screenshots**
![image](https://github.com/user-attachments/assets/159ff20f-f8a2-40cd-a1f6-95d362d5bb71)

**Comment by LegitScarceTM** [comment]
experiencing the same thing.
![image](https://github.com/user-attachments/assets/e515eb82-db50-4a8c-9b6f-a0e92eaf53b6)

**Comment by GrapesMaster98** [comment]
+1

![image](https://github.com/user-attachments/assets/c1ddc534-1bf2-4957-90f9-33914d7be08f)

**Comment by EZ2Alpa** [comment]
Same here... even all the tweets are no longer loading... perhaps the API is dead for the extension API...?
Guess we'll have to wait for an emergency update...
![image](https://github.com/user-attachments/assets/f7d378ee-42d7-43ff-bd4a-0f9b47f45e3d)

**Comment by shy1132** [comment]
i think this is just a temporary bug, "Internal error" is coming from twitter's side
i can also reproduce an instance of this on regular twitter

**Comment by EZ2Alpa** [comment]
I knew that was the case...
I can use and view the official apps,
But only OldTwitter seems to have an internal error...
Even a clear cache reload did the same thing...

**Comment by meechgalhuquot** [comment]
Same errors, just manually updated in Firefox and still having the issue. No problem when extension disabled

**Comment by shy1132** [comment]
very weird, i cant reproduce it at all
if/when i can reproduce it ill try to fix it and make a pr (assuming this doesn't just blow over within a few hours)

**Comment by LegitScarceTM** [comment]
was running Chrome 126.0.6478.182, trying an update.

**Comment by LegitScarceTM** [comment]
interestingly, after running a nightly build of firefox with the extension, it is working just fine on my end.

**Comment by EZ2Alpa** [comment]
I deleted the extension and re-dropped it, and the same thing happened.
I looked at the error log in the extension settings and found two errors like this, the first one was “Uncaught (in promise) Error: Extension context invalidated.
![image](https://github.com/user-attachments/assets/8b474540-834e-443c-8892-799d77a1c671)
![image](https://github.com/user-attachments/assets/725c1ca6-5da5-4ef9-a809-bc5462d239f1)

**Comment by EZ2Alpa** [comment]
But sometimes when I run it on a Google account with a different profile, the tweets load correctly...
You must be wondering about this bug...
![image](https://github.com/user-attachments/assets/dd39ab7d-b388-44cc-aae4-520cab265661)

**Comment by EZ2Alpa** [comment]
It appears to be fixed.
So maybe it was a temporary Twitter bug...
![image](https://github.com/user-attachments/assets/fc603779-e2c5-4d24-ab63-46dd53fb4246)

**Comment by shy1132** [comment]
i suspected that to be the case seeing how inconsistent it was, i have no idea how differences in browser + user account affected it though
