### ISSUE TITLE
Video playback aborted due to a network error

### ISSUE THREAD

**Issue by Devarite** [dimdenGD/OldTwitter#9]
I always get "Video playback aborted due to a network error" overlayed over every video but the video still plays if spacebar is pressed.

![waterfox_mAN3bBi59h](https://user-images.githubusercontent.com/80384432/186055703-8970bdb8-dd07-400f-b383-72debfcbd795.png)

Browser: Firefox

**Comment by dimdenGD** [comment]
Can you send link to tweet where this happens?

**Comment by dimdenGD** [comment]
Oh well you said every video, I tried playing couple of vids on firefox but it all works well for me so I'm not sure, maybe you get some errors in console when try playing?

**Comment by Devarite** [comment]
I get "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://video.twimg.com/ext_tw_video/1522424553158455296/pu/vid/640x360/yu-WoePsqNqq_j8q.mp4?tag=12. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)" constantly repeating in the console when playing.

**Comment by dimdenGD** [comment]
what version of firefox do you have?
