### ISSUE TITLE
Tweets no longer load

### ISSUE THREAD

**Issue by thepwrtank18** [dimdenGD/OldTwitter#90]
**Describe the bug**
When you try to load a Tweet, it's just this:
![image](https://github.com/dimdenGD/OldTwitter/assets/57580668/1565ca59-73cf-4e92-af42-c9f484b1b091)
When going to the direct link (and in the console), it just says "Sorry, that page does not exist".

**To Reproduce**
Steps to reproduce the behavior
1. Try to click on Tweet
2. nothing

**Expected behavior**
The tweet should show up.

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/57580668/1cf7e4fa-1b96-428a-8a86-1eab69e64c9e)
![image](https://github.com/dimdenGD/OldTwitter/assets/57580668/9b40949a-52b0-4b10-98f9-6133c76f6442)

**Browser**
Firefox Developer Edition 115.0b9 (64-bit)

**Comment by Gucci-Slides** [comment]
having same issue on chrome version 114.0.5735.199

**Comment by thepwrtank18** [comment]
I think Twitter so conveniently shut off whatever this relied on.

**Comment by thepwrtank18** [comment]
Is anyone also by chance getting "his request looks like it might be automated. To protect our users from spam and other malicious activity, we can't complete this action right now. Please try again later."?

**Comment by thepwrtank18** [comment]
Profile results now also show "Sorry, that page does not exist". I think Elon's pulling the plug.

**Comment by meetpateltech** [comment]
> Is anyone also by chance getting "This request looks like it might be automated. To protect our users from spam and other malicious activity, we can't complete this action right now. Please try again later."?

Facing same issue right now! (Lots of Twitter users reporting with alternate accounts on twitter too just saw)

**Comment by thepwrtank18** [comment]
Alt account too here.

**Comment by Glazelf** [comment]
+1, timeline works fine but some tweets fail to load. In the example tweet below i'm trying to load the post from Dimden plugging this plugin: https://twitter.com/dimdenEFF/status/1675234201866493952?t=r00A41TeuW5eCxX9Pmm5Tw&s=19
![image](https://github.com/dimdenGD/OldTwitter/assets/35176230/9ebb96de-2bf8-4028-a1fe-588876de5700)

**Comment by polygondev** [comment]
I'm getting the same error, also on Firefox Developer Edition, plus many more

**Comment by dimdenGD** [comment]
Seems that Twitter just broke lot of things, I'll try to fix them asap

**Comment by bitbybyte** [comment]
You'll probably need to do a serious rewrite. Twitter removed pretty much all of the v1.1 API endpoints you're relying on, with the exception of the home timeline which inexplicably still works. This is same behavior seen in old Tweetdeck, new Tweedeck relies on GraphQL same as the modern web client and now has rate limits enforced too.

**Comment by dimdenGD** [comment]
Tweets and profile page now work on beta, you have to manually install if you want. Will take some time before released to Chrome Web Store and Firefox Addons

**Comment by Dacatzgoescodin5267** [comment]
How do i activate beta? since i cant find it

**Comment by dimdenGD** [comment]
You have to manually download zip file and unpack it and installed as unpacked
