### ISSUE TITLE
RT button sometimes doesn't work.

### ISSUE THREAD

**Issue by EZ2Alpa** [dimdenGD/OldTwitter#902]
**Describe the bug**
You may be able to retweet by clicking the retweet button in the tweet field, but sometimes it does not work with no response when you press retweet and it does not mean that you have been retweeted.

**Screenshots**
(In the error log, perhaps this error may be related)
![image](https://github.com/user-attachments/assets/ffd0d8dd-4240-4ceb-bd7b-c14d21a5b216)

**Browser**
Google Chrome 127.0.6533.73 (Official Build)

**Links**
All pages with a tweet field

**OldTwitter version**
v1.8.7.2 (beta)

**2024/08/03 Postscript**
When I go to the tweet details page after retweeting a tweet, it is treated as non-responsive to the retweet, and then when I go back to the tweet section and undo the retweet, the retweet count is set to -1.
![image](https://github.com/user-attachments/assets/a97c9996-dbd1-4c5d-b461-5d87d6f810c3)

**Comment by samiscoolest** [comment]
also experiencing this recently

**Comment by mollyesbian** [comment]
experiencing this too

**Comment by samiscoolest** [comment]
it may be coincidental but im noticing that attempting to retweet videos really doesnt work, it just wont at all unless you switch to new twitter

**Comment by infinitephantasm** [comment]
can confirm i'm also experiencing this as well, bit worried i'm going to end up triggering some kind of bot detection as a result

**Comment by rx65m** [comment]
Same here!

**Comment by skankphone** [comment]
same here

**Comment by EZ2Alpa** [comment]
2024/08/05 Postscript
The beta version has been released, but apparently there is still a bug (aka -1 RT bug) in the UI that makes it look like retweeting is OK, but there is also a bug that was in some other issue.
(I think the retweet button non-response bug has probably been fixed.)
![image](https://github.com/user-attachments/assets/d9dddbd3-194a-4d12-88ac-40b0e241fd46)

> **Describe the bug** You may be able to retweet by clicking the retweet button in the tweet field, but sometimes it does not work with no response when you press retweet and it does not mean that you have been retweeted.
> 
> **Screenshots** (In the error log, perhaps this error may be related) ![image](https://private-user-images.githubusercontent.com/139020260/354622106-ffd0d8dd-4240-4ceb-bd7b-c14d21a5b216.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4ODE2NDksIm5iZiI6MTcyMjg4MTM0OSwicGF0aCI6Ii8xMzkwMjAyNjAvMzU0NjIyMTA2LWZmZDBkOGRkLTQyNDAtNGNlYi1iZDdiLWMxNGQyMWE1YjIxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQxODA5MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzIyY2M5OTgyNDI0MDEyYjk1YTYwMWE0NjViMzBmMDI3MjYzNDRjNTllOWQ0ZGU3MTE5OGU1ZDRmOTVjYzFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SOqkZasxnk6lL6YvGEq9_xu8c5WThAKQNBlD85qn_D8)
> 
> **Browser** Google Chrome 127.0.6533.73 (Official Build)
> 
> **Links** All pages with a tweet field
> 
> **OldTwitter version** v1.8.7.2 (beta)
> 
> **2024/08/03 Postscript** When I go to the tweet details page after retweeting a tweet, it is treated as non-responsive to the retweet, and then when I go back to the tweet section and undo the retweet, the retweet count is set to -1. ![image](https://private-user-images.githubusercontent.com/139020260/354792342-a97c9996-dbd1-4c5d-b461-5d87d6f810c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4ODE2NDksIm5iZiI6MTcyMjg4MTM0OSwicGF0aCI6Ii8xMzkwMjAyNjAvMzU0NzkyMzQyLWE5N2M5OTk2LWRiZDEtNGM1ZC1iNDYxLTVkODdkNmY4MTBjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNVQxODA5MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNmMwNDQ2ZmY5YjFlZjQ5YjI4MTdkMDRlMWYxMWZmZWNkNDI0NjUxMmIxMThhMjAyMDYwZjRiYTE3YTc0YzFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9su4WaZunhni4uQGUAUo6EbkSxA1_rMGPSDtGUB8O9g)

**Comment by rx65m** [comment]
The situation continues to deteriorate.
Presently, neither clicking the RT button nor pressing the T key yields any results.
Both methods have ceased to function entirely for retweeting any account.
Occasionally, tweets appear to be retweeted as usual, but upon refreshing the page, it becomes evident that no retweet has occurred.

**Comment by EZ2Alpa** [comment]
> The situation continues to deteriorate. Presently, neither clicking the RT button nor pressing the T key yields any results. Both methods have ceased to function entirely for retweeting any account. Occasionally, tweets appear to be retweeted as usual, but upon refreshing the page, it becomes evident that no retweet has occurred.

I've seen that happen too... I get the same response when I press the hotkey T key, and it happens quite often when I retweet something and it looks like it's been retweeted, but when I reload it or look at the tweet details page or the tweet section of my profile, it's not retweeted.
(Though it is possible to press the retweet button and have a certain percentage of the tweets be retweeted.)

**Comment by MarisaKirisame-ze** [comment]
This happens to me too. Either way, it's probably better to use YeahTwitter.

**Comment by rx65m** [comment]
Version 1.8.7.3 seems to show less errors like this, after testing it for several hours.
Not perfect, but working better. Happily.
Thank you, @dimdenGD !

**Comment by rx65m** [comment]
Version 1.8.8 is working perfectly fine, so far! 
Thanks again, @dimdenGD !
