### ISSUE TITLE
Search for Shadowbanned accounts

### ISSUE THREAD

**Issue by DeCat4** [dimdenGD/OldTwitter#907]
Twitter shadowbans accounts for arbitrary reasons or because they are too lazy to bring more accessibility features, making these accounts unsearchable.

Would it be possible to make it so these accounts pop up in search results or at least only the ones we follow if it's easier to do? It's genuinely the most frustrating thing for twitter that half the accounts i follow i gotta dig to find them even though i know a portion of their username but i'd need search results to find it.

**Comment by dimdenGD** [comment]
it's not possible, but if they follow you, you can use follow filter

**Comment by DeCat4** [comment]
ah fair enough though how can you use filter in the search bar?

**Comment by dimdenGD** [comment]
You can't, you have to go to your followers page to use it

**Comment by DeCat4** [comment]
ah, by filter are you refering to the ctrl + f filter or is there some button i'm missing? cause i'm going to the https://x.com/username/following page and it just shows the profiles but no filter, sorry if i'm annoying i'm just a bit confused

**Comment by dimdenGD** [comment]
im talking about followers not following

**Comment by DeCat4** [comment]
ah, i misread, thanks for the help.
