### ISSUE TITLE
random errors

### ISSUE THREAD

**Issue by samiscoolest** [dimdenGD/OldTwitter#910]
it kinda just happens consistently when scrolling the feed suddenly, i cant really gauge a reason it happens, it just occurs after scrolling enough
![image](https://github.com/user-attachments/assets/310b5623-ddfd-449a-9d9a-7754d71d9ffb)

**Comment by dimdenGD** [comment]
F12 to see errors in console when it happens

**Comment by samiscoolest** [comment]
this stopped with the latest release
