### ISSUE TITLE
OldTwitter getting rate limited

### ISSUE THREAD

**Issue by Osha31** [dimdenGD/OldTwitter#911]
**Describe the bug**
Seems like Twitter is rate limiting OldTwitter only, regular Twitter functions properly. It seems to only affect retweets as likes behave properly.

**Screenshots**
![vivaldi_BvTY97dTTJ](https://github.com/user-attachments/assets/6b15a2a7-92dd-4dde-bfa4-d0526ba8ae70)

**Browser**
Vivaldi

**OldTwitter version**
v1.8.7.3

**Comment by GreatFunk** [comment]
it also happens on firefox. don't know why?

**Comment by yorunoken** [comment]
should be fixed in the newest version
