### ISSUE TITLE
Twitter throws an error forwarding requests on X

### ISSUE THREAD

**Issue by zillerg** [dimdenGD/OldTwitter#914]
**Issue**
Once you click on the link for x.com(twitter) it throws a pop-up window and then reloads the page continually doing the same process. 
 
 **Message on the pop-up**

>  
> There was an error in initializing security header generator: TypeError: homepageData.match(...) is null
> User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:129.0) Gecko/20100101 Firefox/129.0
> OldTwitter doesn't allow unsigned requests anymore for your account security. Currently the main reason for this happening is social network tracker protection blocking the script. Try disabling such settings in your browser and extensions that do that and refresh the page. Also using OldTwitter from twitter.com domain is not supported.

**Browser**
Latest Firefox Browser(129.0.2). Tested it on the Firefox Developer Edition(also latest version) same result 

**Links**

[https://twitter.com/x/migrate?tok=7b2265223a222f686f6d65222c2274223a313732343336383330377d2210a27848f5cac5c3801d3238eb9f8a]

**OldTwitter version**
Also latest version 1.8.8

**Comment by dimdenGD** [comment]
turn off extension, visit x.com once, turn it back on

**Comment by zillerg** [comment]
I have weird bug on the TwitterDeck, a while ago after I left it open, it would load the recent liked posts for a user(it was around end of July around July 20th) but then if I refreshed the whole site page it would go back to refreshing liked for a user again and not show. Do you know possibly what could be the reason why it glitches like this because it happened couple of times before and then now it stopped, but I haven't tested it yet.

**Comment by dimdenGD** [comment]
Viewing likes was removed by Elon.

**Comment by zillerg** [comment]
Oh, I remember but it was after the announcment and I remember it stopped showing to me right away, but after refreshing after a week it did load for some weird reason, maybe caching did that. I'm not sure.
