### ISSUE TITLE
Screen stays on bird logo whenever I visit an account (not on the main or search pages)

### ISSUE THREAD

**Issue by CoreyMurray** [dimdenGD/OldTwitter#916]
I'm having this strange bug where whenever I go to a Twitter account, the screen stays on the bird logo and doesn't load the account. This doesn't happen on the main page, nor on the search page.

Browser is Google Chrome version 109.0.5414.120

OldTwitter version is 1.8.8

**Comment by dimdenGD** [comment]
Fixed in 1.8.8.2
