### ISSUE TITLE
Profiles not opening in OldTwitter

### ISSUE THREAD

**Issue by ViciousForte0** [dimdenGD/OldTwitter#918]
So the past few hours I haven't been able to open profiles in OldTwitter, I'm using Firefox 129.0.2 (64-bit) on OldTwitter version 1.8.4, I cleared my cache and that didn't fix it so I'm not sure what else to do.

**Comment by brasstax** [comment]
Install the latest version, 1.8.8.2. The release notes say there's specifically a fix for profiles, and loading profiles works for me with this version.

**Comment by ViciousForte0** [comment]
Do I need to use the developer Firefox from now on? I couldn't get it to load on anything but the temporary addon function on the regular Firefox I've had open this whole time and that says I'll have to do that every time I open Firefox for it to work.

**Comment by brasstax** [comment]
As far as I can tell, that's what you'll have to do; either have the dev/nightly version (maybe the ESR version works?), or use the temporary addon function and reinstall it every time. I'm in the same conundrum myself and I'll probably give the ESR version a go to see if that works.

**Comment by ViciousForte0** [comment]
Damn, that's annoying. I don't want to switch off of regular Firefox so I guess I can't use it anymore.

**Comment by dimdenGD** [comment]
How to painlessly switch all your data to Developer edition:

**If you want the most stable version, use Dev, as it gets the same updates as Stable and is not as buggy as Nightly**

1. download dev/nightly
 - <https://www.mozilla.org/en-US/firefox/channel/desktop/>
2. open dev/nightly once to generate a profile folder
3. completely close dev/nightly and normal firefox
4. press windows+r and put in ``%appdata%/mozilla/firefox/profiles``
 - if you've ever wanted to make a manual backup of your entire firefox setup, this is where you'd want to go
5. copy everything from the ``xxxxx.default-release`` folder into the ``xxxxx.dev-edition-default``/``xxxxx.default-nightly``
6. open firefox dev/nightly, and literally everything should be there

7. Go to ``about:config`` in the url bar, and change "xpinstall.signatures.required" to false

you can now install extension permamently in about:addons page
