### ISSUE TITLE
Individual Tweets and Profiles cannot be viewed anymore

### ISSUE THREAD

**Issue by Arcadius2006** [dimdenGD/OldTwitter#92]
**Describe the bug**
OldTwitter cannot view people's profiles, look at individual Tweets (with their replies), or even search

**To Reproduce**
Click on either someone's tweet or their profile picture, it will ALWAYS fail

**Expected behavior**
Everything can be viewed without issue

**Screenshots**
![image](https://github.com/dimdenGD/OldTwitter/assets/93880348/6bcfad78-2154-4cbb-9fd7-35bc65dc1952) ![image](https://github.com/dimdenGD/OldTwitter/assets/93880348/53e6e08d-6228-482b-a18b-a3d2e93652e5) ![image](https://github.com/dimdenGD/OldTwitter/assets/93880348/08a823a4-c484-47c6-8b3a-eed820ae9e07)

**Browser**
Google Chrome Version 114.0.5735.199 (64-bit)

**Comment by TorutheRedFox** [comment]
can confirm

**Comment by polygondev** [comment]
I've also got this issue, seems like everyone has it

**Comment by dimdenGD** [comment]
I'm wokring on a fix

**Comment by dimdenGD** [comment]
Tweets and profile page now work on beta, you have to manually install if you want. Will take some time before released to Chrome Web Store and Firefox Addons

**Comment by Arcadius2006** [comment]
i dont see any links for a beta branch, do i have to compile the thing myself?

**Comment by dimdenGD** [comment]
Depends if you're on Firefox or Chromium, on Chromium you can just download this repo as zip and unarchive and install unpacked

**Comment by Dog1818** [comment]
I downloaded and loaded the latest unpacked version into Chrome and it didn't fix the issue!

**Comment by dimdenGD** [comment]
> I downloaded and loaded the latest unpacked version into Chrome and it didn't fix the issue!

Can you give me link to profile or tweet that didn't work?

**Comment by Dog1818** [comment]
i mean it's all of the profiles. but here's an example https://twitter.com/b0tster

**Comment by dimdenGD** [comment]
Works fine for me. Did you uninstall normal version of OldTwitter before installing beta one?

**Comment by Dog1818** [comment]
i did remove the normal version from my chrome yes. i could always uninstall and reinstall and see what happens.

**Comment by dimdenGD** [comment]
Could you open your Console with F12 and show what errors you get when you do this

**Comment by Dog1818** [comment]
![aaaaa34e](https://github.com/dimdenGD/OldTwitter/assets/138386193/c340fa6c-3ccc-4eb4-a546-c7cb3906506e)
chrome gives me these errors when i load the unpacked folder.

**Comment by dimdenGD** [comment]
These are irrelevant, you need errors from console

**Comment by Dog1818** [comment]
![Screenshot 2023-07-02 164431](https://github.com/dimdenGD/OldTwitter/assets/138386193/06048182-fb68-483c-98e1-51fa071b0b4a)
these are the ones i get from console.

**Comment by dimdenGD** [comment]
You didn't refresh page before screenshotting, "Extension context invalidated" errors are irrelevant

**Comment by Dog1818** [comment]
i've refreshed and the yellow ones are still there buddy 
![Screenshot 2023-07-02 171227](https://github.com/dimdenGD/OldTwitter/assets/138386193/b646b045-f169-4ae2-a079-d104bc83e3d7)

**Comment by dimdenGD** [comment]
Yellow ones are useless warnings, only errors matter

**Comment by Dog1818** [comment]
here are the errors i get on the page i linked earlier 
![Screenshot 2023-07-02 171515](https://github.com/dimdenGD/OldTwitter/assets/138386193/277717e8-78cd-4192-a597-5e810903a1a1)

**Comment by dimdenGD** [comment]
You didn't properly install beta version. This is normal one

**Comment by Dog1818** [comment]
this is the 1.7.1 version i installed from github downloads.

**Comment by dimdenGD** [comment]
You have to use button on main page that says Code and Download as ZIP

**Comment by Dog1818** [comment]
oh i see. thank you!

**Comment by Dog1818** [comment]
yep i got it working now! 
![Screenshot 2023-07-02 172042](https://github.com/dimdenGD/OldTwitter/assets/138386193/6dffe548-fa51-46af-a239-19a8d835aea0)

**Comment by TorutheRedFox** [comment]
just checked, this change on Twitter's side also broke the iOS 6 twitter app

thanks, Elon

**Comment by Nikuw** [comment]
Hey, I tried removing the standard version, cloning the repo and installing from manifest.json in Firefox, but I got this message instead, am I doing something wrong?

![image](https://github.com/dimdenGD/OldTwitter/assets/40671372/0e0688f5-891a-4449-84ef-cb6e71300b21)

**Comment by thepwrtank18** [comment]
How do you install on Firefox?

**Comment by Nikuw** [comment]
I think the manifest.json file needs to be modified, since there's 2 releases posted, one for Chromium and one for Firefox. I'll look into it, since Elon's Twitter is currently so broken for me that I can't even like or tweet anything.

**Comment by Dog1818** [comment]
yeah also it turns out i can't look at full profiles if i'm rate limited

**Comment by Nikuw** [comment]
As I suspected, the manifests are completely different, since Firefox is still using v2. Without the dev's help I have no idea how to fix it (and make it installable in Firefox) without completely breaking the extension, though...

**Comment by dimdenGD** [comment]
You have to use `pack.js` script to build extension for Firefox, you need Node.js for this. I'd say just wait until I release the fix

**Comment by Nikuw** [comment]
Ah, I should have guessed that releases are generated with some kind of script - I guess it's pretty obvious I'm not much of a web dev. Thanks a lot for the tip, I've got it working and I can finally tweet again, and all it took was running `npm i adm-zip` and `node pack.js`.

**Comment by trapsena** [comment]
> You have to use button on main page that says Code and Download as ZIP

tried downloadding from there but when i try to install it i get this error
![image](https://github.com/dimdenGD/OldTwitter/assets/88294045/155c910a-999f-443a-a018-051806b0d9d8)

**Comment by thepwrtank18** [comment]
https://github.com/dimdenGD/OldTwitter/actions

Download from here, extract the zip inside the zip, use that

**Comment by dimdenGD** [comment]
> > You have to use button on main page that says Code and Download as ZIP
> 
> tried downloadding from there but when i try to install it i get this error ![image](https://user-images.githubusercontent.com/88294045/250391329-155c910a-999f-443a-a018-051806b0d9d8.png)

Thanks for reporting, I just fixed this. Try again.

**Comment by thepwrtank18** [comment]
![image](https://github.com/dimdenGD/OldTwitter/assets/57580668/2445a760-e472-434e-95e9-4437c79c3a97)
It broke again

**Comment by thepwrtank18** [comment]
![image](https://github.com/dimdenGD/OldTwitter/assets/57580668/67e65cd3-b95e-439e-83c5-5915aacc037c)

**Comment by dimdenGD** [comment]
works for me, can you give me link to tweet where this happens

**Comment by thepwrtank18** [comment]
https://twitter.com/_taarene/status/1675259174744203272

**Comment by dimdenGD** [comment]
This was fixed

**Comment by thepwrtank18** [comment]
https://twitter.com/RobloxLeakers__/status/1675473062584541184
![image](https://github.com/dimdenGD/OldTwitter/assets/57580668/db849553-22d2-45a2-a671-34f9ee378bb7)
