### ISSUE TITLE
Most of the OldTwitter pages are having trouble displaying.

### ISSUE THREAD

**Issue by EZ2Alpa** [dimdenGD/OldTwitter#920]
**Describe the bug**
The official app also has a problem, and this one often shows up fine, but OldTwitter shows the same error log repeatedly, and most of the pages do not show up with the blue bird symbol.
Especially user pages and Unfollower (Unfollow) are completely dead with no display.

**Screenshots**
![image](https://github.com/user-attachments/assets/0a0d0b15-dd27-44f4-98df-b9a534a40b10)

**Browser**
Google Chrome 128.0.6613.85（Official Build）

**Links**
All pages corresponding to OldTwitter

**OldTwitter version**
v1.8.8.4

**Comment by dimdenGD** [comment]
Fixed in 1.8.9
