### ISSUE TITLE
Account feed fails to load

### ISSUE THREAD

**Issue by bluewarbler** [dimdenGD/OldTwitter#922]
Whenever I go to any individual account, it simply displays the Twitter logo in the center of a white screen and doesn't actually load the page. This does not happen on the home page or on individual tweets, just on individual users' pages.

**Screenshots**
<img width="1790" alt="Screen Shot 2024-08-30 at 3 18 16 PM" src="https://github.com/user-attachments/assets/c1738ff0-7a49-4882-921b-5f9b69c19dec">
(This error repeats ad infinitum)

**Browser**
Firefox 129.0.2

**Links**
https://x.com/basedbinkie

**OldTwitter version**
v1.8.4

**Comment by dimdenGD** [comment]
Last OldTwitter version is 1.8.9
