### ISSUE TITLE
Cant upgrade to 1.8.9. on nightly or normal firefox

### ISSUE THREAD

**Issue by ShinAli21** [dimdenGD/OldTwitter#925]
**Describe the bug**
When trying to upgrade to 1.8.9. by installing the add-on, and error will pop up saying its corrupted and wont update.

**Screenshots**
![Screenshot_68](https://github.com/user-attachments/assets/fa5dfbbc-a39e-486f-b5d9-7bbf9f8dab23)

**Browser**
Include your browsers name and it's version.
Version 129.0.2 (normal firefox) Nightly Version 131.0a1

**Links**

Only appears on firefox

**OldTwitter version**
Version 1.8.4

**Comment by dimdenGD** [comment]
Set xpinstall.signatures.required to false
it says that in installation guide

**Comment by ShinAli21** [comment]
> Set xpinstall.signatures.required to false it says that in installation guide

I have it set to false.

![Screenshot_69](https://github.com/user-attachments/assets/c23e70cf-c41c-4bac-b541-2987b2fe5787)

**Comment by dimdenGD** [comment]
use firefox for developers and uninstall old version
