### ISSUE TITLE
Can't view profiles

### ISSUE THREAD

**Issue by polygondev** [dimdenGD/OldTwitter#93]
**Describe the bug**
Twitter profiles will not load, instead resulting in 'Sorry, that page does not exist' error.

**To Reproduce**
Attempt to visit any profile

**Expected behavior**
Expected to see account contents

**Screenshots**
<img width="1440" alt="Screenshot 2023-07-02 at 19 33 05" src="https://github.com/dimdenGD/OldTwitter/assets/66850658/61c2fc55-1b5b-4592-9c37-35e0a161ddb2">
<img width="1452" alt="Screenshot 2023-07-02 at 18 14 10" src="https://github.com/dimdenGD/OldTwitter/assets/66850658/61911c5a-4287-4fdf-81ba-21db4f56bcbb">

**Browser**
Firefox Developer Edition 115.0b9

**Comment by dimdenGD** [comment]
This was fixed in beta, please wait for the release
