### ISSUE TITLE
Profiles Not Opening or Loading

### ISSUE THREAD

**Issue by peachouji** [dimdenGD/OldTwitter#940]
any time i go to click on a profile, whether it's my own or someone else's, it stays stuck on the twitter logo. i can refresh it a hundred times and it does not budge. this is both on oldtwitter itself and when i click on profile through oldtweetdeck and it goes to open oldtwitter.

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/792c2f28-9e88-4670-a5e6-0f37faad226e">

chrome Version 129.0.6668.59 (Official Build) (64-bit)

**Comment by peachouji** [comment]
i can't even go on dimden's profile to see if they discussed this before 😔

**Comment by dimdenGD** [comment]
extension version?

**Comment by peachouji** [comment]
> extension version?

oop sorry! it's 1.8.4.1. i just redownloaded it after trying to uninstall it and redownload.

**Comment by dimdenGD** [comment]
1.8.4.1 is very old, update
