### ISSUE TITLE
Go to new twitter with context menu item

### ISSUE THREAD

**Issue by Terrails** [dimdenGD/OldTwitter#95]
It would be nice to have an option to go to new twitter within the right click context menu. The user would right click anywhere on current site and press on "Open in new Twitter" so that the current active Twitter URL gets `?newtwitter=true` appended to it.

I am not sure if Chrome has this feature but on Firefox addons can add items to the context menu to do things. ~~Although I am not sure if its possible to do this on site by site basis or if the addon would have to constantly show that item when in context menu even if current active tab is not twitter.~~ Seems like this is possible. From the documentation: `Once a context menu item has been added using contextMenus.create it's displayed in all browser tabs, but you can hide it by removing it with contextMenus.remove.`

**Comment by dimdenGD** [comment]
This won't be added as easy option to switch between old and new Twitter already exists so I don't really see any point in extra complexity and 1 more permission to add:
![image](https://github.com/dimdenGD/OldTwitter/assets/26517362/4fa8fea3-1def-44ab-8683-709cce99b661)  
and  
![image](https://github.com/dimdenGD/OldTwitter/assets/26517362/eb60e5e1-4a92-4522-8716-77d3b73b8f10)
