### ISSUE TITLE
Help, is this a bug or something?

### ISSUE THREAD

**Issue by jexnkath** [dimdenGD/OldTwitter#952]
The extension is not working, only in appearance, because when I want to see the tweets it gets stuck loading and nothing happens :(

![Sin título](https://github.com/user-attachments/assets/90aba9b9-f96b-411c-9c29-51ca2a89cb05)

my browser is chrome version 130.0.6723.59

OldTwitterLayout version is 1.8.9

**Comment by dimdenGD** [comment]
Viewing other peoples likes was removed by Elon months ago, it's not possible to fix that
