### ISSUE TITLE
Profile link color fails to sync and default link color only shows in settings page

### ISSUE THREAD

**Issue by TorutheRedFox** [dimdenGD/OldTwitter#96]
The sync issue is related to CORS (``settings:1 Access to fetch at 'https://dimden.dev/services/twitter_link_colors/v2/set' from origin 'https://twitter.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.``) but I have no idea why the default link color doesn't persist.

**Comment by dimdenGD** [comment]
What browser? Never had issue with CORS since im intercepting these headers

**Comment by TorutheRedFox** [comment]
Ungoogled Chromium

**Comment by TorutheRedFox** [comment]
I'll do some additional debugging on my end see if it's caused here, but I don't think that CORS would cause issues with the default color not persisting across pages

**Comment by dimdenGD** [comment]
Default link color not persisting could only happen if you reload extension and change it after extension context was invalidated

**Comment by TorutheRedFox** [comment]
i'm not doing that though

it does persist in the settings page but in other places i have to override the css variable myself

**Comment by TorutheRedFox** [comment]
although the extension context is invalidating itself because of an error at scripts/helpers.js:845

**Comment by TorutheRedFox** [comment]
there's also this error 
![image](https://github.com/dimdenGD/OldTwitter/assets/15708278/099a3e2c-eb39-43d7-8b01-c2e650c4ecd5)

**Comment by dimdenGD** [comment]
Can you show full error

**Comment by TorutheRedFox** [comment]
![image](https://github.com/dimdenGD/OldTwitter/assets/15708278/4a033866-8e41-4e65-b352-398244da4729)

**Comment by dimdenGD** [comment]
Try downloading and installing again

**Comment by TorutheRedFox** [comment]
only thing that seems to have got fixed is the color box for the profile link color no longer being black and actually being my profile link color from back in the day

**Comment by dimdenGD** [comment]
I'm not sure about color not showing anywhere else but settings page bug, but CORS bug should be fixed in beta

**Comment by TorutheRedFox** [comment]
ok the CORS bug is fixed but yeah the color not showing anywhere else still persists

**Comment by dimdenGD** [comment]
This was fixed
