### ISSUE TITLE
Profiles not loading

### ISSUE THREAD

**Issue by softserve201** [dimdenGD/OldTwitter#969]
The profiles are not loading on the extension. My own profiles not even loading.
Google chrome is my browser
Twitter version 1.8.9

**Comment by ReconCoyote978** [comment]
I tried with the extension disabled, and Twitter web won't load, I think its a Twitter serverside issue

**Comment by ReconCoyote978** [comment]
Nvm, web X.com works, but extension interface ain't working, search function too

**Comment by Lacerta-agilis** [comment]
![image](https://github.com/user-attachments/assets/0ba43d16-dc9f-4a3b-ae24-b506d4b82eab)
Does it look the same way as mine? profile card 'loading', all custom settings don't work (I use 2018 design with hearts and round avatars, and on the setting page that all is still marked as selected)

**Comment by Lacerta-agilis** [comment]
(well, while posting this comment, the website reloaded once again and the issue seems now fixed)
