### ISSUE TITLE
Muted autoplay

### ISSUE THREAD

**Issue by TorutheRedFox** [dimdenGD/OldTwitter#97]
Basically every browser doesn't allow audio to autoplay anyways (and that includes video that's not muted) so an option to do that would be nice

**Comment by Martin1995** [comment]
it would be a great feature to add in because autoplaying videos with sound on is a bit annoying when you just scroll by,...
@dimdenGD I'd appreciate it if you would add this in soon

**Comment by TorutheRedFox** [comment]
> it would be a great feature to add in because autoplaying videos with sound on is a bit annoying when you just scroll by,... @dimdenGD I'd appreciate it if you would add this in soon

and it also makes subesquent autoplay work without having to manually play a video first
