### ISSUE TITLE
Timezone change breaks the entire site

### ISSUE THREAD

**Issue by iilme** [dimdenGD/OldTwitter#972]
**Describe the bug**
In short, I fucked up my time on the computer when setting OldTwitter up, and upon changing it (+1h) everything broke. Clicking on any profile leads to it freezing on the Twitter logo, the main page shows "Loading" as the nickname and "@Loading" as the username, the homepage is frozen in time and no new tweets load, the account icon button is blank and clicking on it to try to change to another account doesn't open the menu.

**Screenshots**
![image](https://github.com/user-attachments/assets/4e9bdaa5-a4b2-49b4-9984-07523b178328) 
![image](https://github.com/user-attachments/assets/bbd6e2c0-ac54-4e33-8224-bd11696fb0fe)

**Browser**
![image](https://github.com/user-attachments/assets/750beee3-7907-4e9d-9993-2e12a94a634e)

**Links**
x.com/home##
x.com/home
x.com/AnyProfileHere

**OldTwitter version**
1.8.9.4

This could be a caching issue, this could be a Supermium issue; i tried restarting my computer, changing the time back, but it seems to have screwed itself up BAD

**Comment by dimdenGD** [comment]
timezone is unrelated, oldtwitter just broke recently, wait for update to come out on chrome web store or get latest version from github manually
