### ISSUE TITLE
The favorite markings is stuck in an infinite loading loop

### ISSUE THREAD

**Issue by Nintendonuts** [dimdenGD/OldTwitter#983]
Hello. Whenever I try to go to a random user's profile on Twitter, and check what are they liking on, I see that the loading times for the favorite markings tab has been for hours and it won't come out. Can anyone help me with this issue that I keep receiving?

![This error](https://github.com/user-attachments/assets/7ab909bc-8c18-4525-8411-841aa989352e)

The name of the browser is Mozilla Firefox and its version is 133.0.3 (64-bit).

Here's the link of an example of a Twitter profile where this occurs: https://x.com/JustinWhang

The version of the OldTwitter extension that I'm running is v1.8.9.7.

**Comment by dimdenGD** [comment]
viewing likes of others has been removed by elon months ago

**Comment by Nintendonuts** [comment]
Oh. I see.
