### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by misternebula** [dimdenGD/OldTwitter#99]
Any search returns "Sorry, that page does not exist."

On Chrome, using artifact from [this run](https://github.com/dimdenGD/OldTwitter/actions/runs/5438247746) (latest master push)

**Comment by misternebula** [comment]
Here are the errors : 
![image](https://github.com/dimdenGD/OldTwitter/assets/41904486/5d7ad751-effb-4322-a2f4-da3d1f9bb451)

**Comment by dimdenGD** [comment]
This was fixed. Please wait until it gets released or install beta manually.
